### ISSUE TITLE
Intermittent Deadlock

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2#1025]
I encountered a deadlock when saving a diagram, but it does not appear to be a graphical editor issue at first glance. This is an intermittent issue which I am unable to reproduce. I captured a thread dump and I have included the portion I believe is relevant below. 

Could this be related to #1024?

I haven't pulled from develop since 2571a4c so feel free to close if this is no longer an issue. 

> "Worker-7" #37 prio=5 os_prio=0 tid=0x000000001fd1c000 nid=0x263c in Object.wait() [0x0000000032dde000]
>    java.lang.Thread.State: TIMED_WAITING (on object monitor)
>         at java.lang.Object.wait(Native Method)
>         at org.eclipse.core.internal.jobs.Semaphore.acquire(Semaphore.java:39)
>         - locked <0x000000076ee393b8> (a org.eclipse.core.internal.jobs.Semaphore)
>         at org.eclipse.core.internal.jobs.OrderedLock.doAcquire(OrderedLock.java:170)
>         at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:106)
>         at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:82)
>         at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:122)
>         at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2188)
>         at org.eclipse.core.internal.resources.Resource.deleteMarkers(Resource.java:796)
>         at org.osate.aadl2.modelsupport.errorreporting.MarkerParseErrorReporter.deleteMessagesImpl(MarkerParseErrorReporter.java:117)
>         at org.osate.aadl2.modelsupport.errorreporting.AbstractErrorReporter.deleteMessages(AbstractErrorReporter.java:56)
>         at org.osate.aadl2.modelsupport.errorreporting.ParseErrorReporterManager.getReporter(ParseErrorReporterManager.java:116)
>         at org.osate.xtext.aadl2.parsing.AnnexParserAgent.afterModelLinked(AnnexParserAgent.java:119)
>         at org.eclipse.xtext.linking.impl.AbstractCleaningLinker.linkModel(AbstractCleaningLinker.java:57)
>         at org.eclipse.xtext.resource.XtextResource.doLinking(XtextResource.java:340)
>         at org.eclipse.xtext.linking.lazy.LazyLinkingResource.doLinking(LazyLinkingResource.java:107)
>         at org.eclipse.xtext.resource.XtextResource.updateInternalState(XtextResource.java:301)
>         at org.eclipse.xtext.resource.DerivedStateAwareResource.updateInternalState(DerivedStateAwareResource.java:169)
>         at org.eclipse.xtext.resource.XtextResource.updateInternalState(XtextResource.java:290)
>         at org.eclipse.xtext.resource.DerivedStateAwareResource.updateInternalState(DerivedStateAwareResource.java:161)
>         at org.eclipse.xtext.resource.XtextResource.update(XtextResource.java:271)
>         at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.doReconcile(XtextDocumentReconcileStrategy.java:150)
>         at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.reconcile(XtextDocumentReconcileStrategy.java:67)
>         at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.doRun(XtextReconciler.java:449)
>         at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.access$3(XtextReconciler.java:429)
>         at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:363)
>         at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:1)
>         at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:37)
>         at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
>         at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.modify(XtextDocument.java:428)
>         - locked <0x000000077ba21940> (a org.eclipse.xtext.resource.DerivedStateAwareResource)
>         at org.eclipse.xtext.ui.editor.model.XtextDocument.internalModify(XtextDocument.java:162)
>         at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.run(XtextReconciler.java:360)
>         at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
> 
>    Locked ownable synchronizers:
>         - <0x000000077be91f58> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
> 
> "Worker-4" #34 prio=5 os_prio=0 tid=0x000000001fd1f000 nid=0x2b68 in Object.wait() [0x0000000032ade000]
>    java.lang.Thread.State: TIMED_WAITING (on object monitor)
>         at java.lang.Object.wait(Native Method)
>         at org.eclipse.core.internal.jobs.Semaphore.acquire(Semaphore.java:39)
>         - locked <0x000000076f91c400> (a org.eclipse.core.internal.jobs.Semaphore)
>         at org.eclipse.core.internal.jobs.OrderedLock.doAcquire(OrderedLock.java:170)
>         at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:106)
>         at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:82)
>         at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:122)
>         at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2188)
>         at org.eclipse.core.internal.resources.Resource.deleteMarkers(Resource.java:796)
>         at org.osate.aadl2.modelsupport.errorreporting.MarkerParseErrorReporter.deleteMessagesImpl(MarkerParseErrorReporter.java:117)
>         at org.osate.aadl2.modelsupport.errorreporting.AbstractErrorReporter.deleteMessages(AbstractErrorReporter.java:56)
>         at org.osate.aadl2.modelsupport.errorreporting.ParseErrorReporterManager.getReporter(ParseErrorReporterManager.java:116)
>         at org.osate.xtext.aadl2.parsing.AnnexParserAgent.afterModelLinked(AnnexParserAgent.java:119)
>         at org.eclipse.xtext.linking.impl.AbstractCleaningLinker.linkModel(AbstractCleaningLinker.java:57)
>         at org.eclipse.xtext.resource.XtextResource.doLinking(XtextResource.java:340)
>         at org.eclipse.xtext.linking.lazy.LazyLinkingResource.doLinking(LazyLinkingResource.java:107)
>         at org.eclipse.xtext.resource.XtextResource.updateInternalState(XtextResource.java:301)
>         at org.eclipse.xtext.resource.DerivedStateAwareResource.updateInternalState(DerivedStateAwareResource.java:169)
>         at org.eclipse.xtext.resource.XtextResource.updateInternalState(XtextResource.java:290)
>         at org.eclipse.xtext.resource.DerivedStateAwareResource.updateInternalState(DerivedStateAwareResource.java:161)
>         at org.eclipse.xtext.resource.XtextResource.update(XtextResource.java:271)
>         at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.doReconcile(XtextDocumentReconcileStrategy.java:150)
>         at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.reconcile(XtextDocumentReconcileStrategy.java:67)
>         at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.doRun(XtextReconciler.java:449)
>         at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.access$3(XtextReconciler.java:429)
>         at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:363)
>         at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:1)
>         at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:37)
>         at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
>         at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.modify(XtextDocument.java:428)
>         - locked <0x000000077ba82778> (a org.eclipse.xtext.resource.DerivedStateAwareResource)
>         at org.eclipse.xtext.ui.editor.model.XtextDocument.internalModify(XtextDocument.java:162)
>         at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.run(XtextReconciler.java:360)
>         at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
> 
>    Locked ownable synchronizers:
>         - <0x000000077bc1e2a8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
> 
> "main" #1 prio=6 os_prio=0 tid=0x0000000002c12800 nid=0x1f70 waiting for monitor entry [0x0000000002b3a000]
>    java.lang.Thread.State: BLOCKED (on object monitor)
>         at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:508)
>         - waiting to lock <0x000000077ba82778> (a org.eclipse.xtext.resource.DerivedStateAwareResource)
>         at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:492)
>         at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:133)
>         at org.eclipse.xtext.ui.editor.outline.impl.AbstractOutlineNode.readOnly(AbstractOutlineNode.java:208)
>         at org.eclipse.xtext.ui.editor.outline.impl.AbstractOutlineNode.getChildren(AbstractOutlineNode.java:99)
>         at org.eclipse.xtext.ui.editor.outline.actions.OutlineWithEditorLinker.findBestNode(OutlineWithEditorLinker.java:143)
>         at org.eclipse.xtext.ui.editor.outline.actions.OutlineWithEditorLinker.findBestNode(OutlineWithEditorLinker.java:144)
>         at org.eclipse.xtext.ui.editor.outline.actions.OutlineWithEditorLinker.findBestNode(OutlineWithEditorLinker.java:144)
>         at org.eclipse.xtext.ui.editor.outline.actions.OutlineWithEditorLinker.selectInTreeView(OutlineWithEditorLinker.java:129)
>         at org.eclipse.xtext.ui.editor.outline.actions.OutlineWithEditorLinker$TextListener.selectionChanged(OutlineWithEditorLinker.java:72)
>         at org.eclipse.jface.text.TextViewer.firePostSelectionChanged(TextViewer.java:2628)
>         at org.eclipse.jface.text.TextViewer.firePostSelectionChanged(TextViewer.java:2576)
>         at org.eclipse.jface.text.TextViewer$5.run(TextViewer.java:2555)
>         at org.eclipse.swt.widgets.Display.runTimer(Display.java:4341)
>         at org.eclipse.swt.widgets.Display.messageProc(Display.java:3419)
>         at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
>         at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2560)
>         at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3815)
>         at org.eclipse.jface.operation.ModalContext$ModalContextThread.block(ModalContext.java:165)
>         at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:369)
>         at org.eclipse.graphiti.ui.editor.DefaultPersistencyBehavior.saveDiagram(DefaultPersistencyBehavior.java:191)
>         at org.eclipse.graphiti.ui.editor.DiagramEditor.doSave(DiagramEditor.java:392)
>         at org.eclipse.ui.internal.SaveableHelper.lambda$0(SaveableHelper.java:154)
>         at org.eclipse.ui.internal.SaveableHelper$$Lambda$576/2109406877.run(Unknown Source)
>         at org.eclipse.ui.internal.SaveableHelper.lambda$3(SaveableHelper.java:271)
>         at org.eclipse.ui.internal.SaveableHelper$$Lambda$543/1080108605.run(Unknown Source)
>         at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:437)
>         at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:353)
>         at org.eclipse.ui.internal.WorkbenchWindow$14.run(WorkbenchWindow.java:2195)
>         at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
>         at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2191)
>         at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:278)
>         at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:259)
>         at org.eclipse.ui.internal.SaveableHelper.savePart(SaveableHelper.java:158)
>         at org.eclipse.ui.internal.WorkbenchPage.saveSaveable(WorkbenchPage.java:3917)
>         at org.eclipse.ui.internal.WorkbenchPage.saveEditor(WorkbenchPage.java:3931)
>         at org.eclipse.ui.internal.handlers.SaveHandler.execute(SaveHandler.java:54)
>         at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
>         at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
>         at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
>         at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
>         at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
>         at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
>         at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
>         at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
>         at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
>         at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:287)
>         at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:527)
>         at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:577)
>         at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:385)
>         at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:331)
>         at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:88)
>         at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
>         at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1271)
>         at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1078)
>         at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
>         at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
>         at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1130)
>         at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1126)
>         at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1547)
>         at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4962)
>         at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:364)
>         at org.eclipse.swt.widgets.Control.windowProc(Control.java:4843)
>         at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:359)
>         at org.eclipse.swt.widgets.Display.windowProc(Display.java:5191)
>         at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
>         at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2560)
>         at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3815)
>         at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
>         at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
>         at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
>         at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
>         at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
>         at org.eclipse.ui.internal.Workbench$$Lambda$14/590414408.run(Unknown Source)
>         at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
>         at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
>         at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
>         at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
>         at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
>         at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
>         at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
>         at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
>         at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
>         at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
>         at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
>         at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
> 
>    Locked ownable synchronizers:
>         - None
>

**Comment by lwrage** [comment]
Do you have the complete thread dump that you can put in a github gist?

**Comment by philip-alldredge** [comment]
No, sorry. If it happens again, I'll post the complete thread dump.

**Comment by lwrage** [comment]
I have a fix for #1024. However, this is likely not related.

**Comment by lwrage** [comment]
@philip-alldredge Is this still an issue?

**Comment by philip-alldredge** [comment]
I have not experienced this recently. I'm fine with closing.
