### ISSUE TITLE
Eliminate all usages of EMFIndexRetrieval

### ISSUE THREAD

**Issue by joeseibel** [osate/osate2#1036]
`EMFIndexRetrieval` is now deprecated. All usages of EMFIndexRetrieval in OSATE should be changed.

blocked by #1089
blocked by #1309

**Comment by philip-alldredge** [comment]
What is the reasoning for deprecating EMFIndexRetrieval. The graphical editor has moved away from EMFIndexRetrieval but still uses something that has many similarities (ScopedEMFIndexRetrieval). Should I be concerned?

**Comment by reteprelief** [comment]
Can you give the user a clue what should be used instead?

**Comment by joeseibel** [comment]
`EMFIndexRetrieval` does not respect project references. `IGlobalScopeProvider` does.

**Comment by lwrage** [comment]
We could also provide a replacement utility class that (a) does the right thing and (b) has a better name as there is no such thing as an EMF index. 
(EMF index was an EMFT project for a while but it was abandoned in 2012. IIRC, its goal was to generalize the Xtext resource description mechanism.)

**Comment by lwrage** [comment]
This class is an abomination. It also breaks non-UI testing, because it uses a UI `ResourceDescriptionsProvider`, which is set via a hack in `org.osate.xtext.aadl2.properties.ui.MyPropertiesActivator`. We should delete the class and never speak of it again.

**Comment by brlarson** [comment]
Okay, Joe/Lutz:  
How do I getAllPackagesInWorkspace using IGlobalScopeProvider?
Some static utility class would be helpful.

**Comment by lwrage** [comment]
The global scope provider doesn't work on the workspace as a whole (and it shouldn't)! The global scope is the current project and all projects it depends on (directly or indirectly).
If you look up elements in the workspace you are ignoring project dependencies, which will likely lead to problems. For example, you can have two projects with the same files in a workspace. If they don't depend on each other there are no name conflicts, even though all (global) names exist twice in the workspace.

**Comment by brlarson** [comment]
Okay, so IGlobalScopeProvider may not be what I need:

How can I find every component with a BLESS annex subclause to generate verification conditions?

(In a second pass, an assume-guarantee VC is generated for every connection between ports with BLESS::Assertion properties, and drop an info marker on each connection that doesn't have them on both ends.)

**Comment by lwrage** [comment]
If you really want to work with the workspace as a whole (why?) you need to inject ResourceDescriptionsProvider, get the resource descriptions and get the exported objects. EMFIndexRetrieval does this, but in the wrong way because it combines dependency injection with static methods, which leads to hacks like the one I mentioned in an earlier comment.

**Comment by lwrage** [comment]
@reteprelief  There are still two usages in smaccm:
- com.rockwellcollins.atc.tcg.util.TcgUtils
- edu.uah.rsesc.aadlsimulator.ui.launch.SimulationTab

**Comment by lwrage** [comment]
The class will be removed in OSATE 2.3.6

**Comment by brlarson** [comment]
How I got all the AADL packages in the workspace w/o EMFIndexRetrieval:

		HashSet<IFile> files = TraverseWorkspace.getAadlFilesInWorkspace();
		for (IFile file : files)
			{
			ModelUnit ir = (ModelUnit) AadlUtil.getElement(file);
			if (ir instanceof AadlPackage)
				{
   ...
