### ISSUE TITLE
AADL Navigator Does not Properly Support Working Sets

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2#1056]
- Selecting Top Level Elements->Working Sets with a working set selected results in only projects that aren't included in a working set appearing. 
    - Working sets do not appear because the org.eclipse.ui.navigator.resources.workingSets contentExtension isn't enabled.
- Unable to add Plugin_Contributions to working set. 

child of #1371

**Comment by lwrage** [comment]
This will be implemented as part of the scalability task.

**Comment by lwrage** [comment]
The AADL navigator implementation is a bit of a mess, in particular the AadlNavigatorLabelProvider is wrong. After fixing it the order of entries doesn't change randomly any longer (see #1120).
