### ISSUE TITLE
Cannot view flow properties in an instance file

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2#1060]
When I open an instance file, I do not see any properties for flow declarations.

I can see some information about a flow in the Properties view.  However, when I open an AADL Properties view on a flow, I get an exception "Updating Property View has encountered a problem.  An internal error occurred during Updating Property View."

**Comment by lwrage** [comment]
Which OSATE version? Do you get a stack trace in the error log or console?

**Comment by lwrage** [comment]
@joeseibel Check for flow specs and e2e flows with and without properties.
