### ISSUE TITLE
IGlobalScopeProvider enhancement

### ISSUE THREAD

**Issue by joeseibel** [osate/osate2#1089]
We should create a custom `IGlobalScopeProvider` which takes an `EClass` instead of an `EReference`. Callers of the global scope should then inject the `Aadl2GlobalScopeProvider` instead of `IGlobalScopeProvider`.

child #1018
needed by #1254

**Comment by lwrage** [comment]
Need a method to look up a type in the global scope given an emf Resource, another given an IProject.

**Comment by lwrage** [comment]
We already have an Aadl2GlobalScopeProvider. It add's methods to check for duplicates, which can likely be done in a better place. Also, these methods use resource descriptions, and that doesn't work in JUnit tests.
