### ISSUE TITLE
Xtext Project Referencing Issues Affecting Graphical Editor

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2#1097]
### Summary
Xtext 2.12 contains an issue that affects the graphical editor. Recommend updating to 2.13 when practical.

### Problem
When a project is referenced which only contains a single AADL resource, references to model elements in that resource fails to resolve if the Xtext document isn't open. This is a problem that mostly affects the graphical editor. It likely affects other cases but we have not verified that. According the the xtext commit log, refactoring seems to be affected.

### Reproduce
- Create two projects: A and B.
- Make A reference B.
- In B: Add a single AADL package to with a data type inside it.
- In A: Add an AADL package with a feature which uses the data type in B as the type.
- Close all Xtext editors.
- Double-click on the feature to select it and bring up the properties view.
- Select the AADL tab.
- The classifier isn't listed because the proxy isn't being resolved. Selecting Choose... and choosing the same type will result in an exception because of resolution issues while checking if there is allready a "with" statement for the package. 

### Cause
This is caused by an issue in org.eclipse.xtext.resource.containers.LiveShadowedAllContainerState in Xtext 2.12. https://github.com/eclipse/xtext-core/commit/8eecbdcd4d5c9dd4c00a348a8aed688d296e3ee8#diff-d0bed40a3a62bdc85d74b7c8aea17034 fixes it. It was released in Xtext 2.13.

When FilterUriContainer is used with a LiveShadowedAllContainerState and the referenced project only has a single AADL package, the result of getContainedURIs and containsURI in LiveShadowedAllContainerState do not agree which causes an issue whe determining if the container is empty when the scope is resolved.

### Workaround
Add a second AADL resource to the referenced project. 

### Fix
Updating to Xtext 2.13 should theoretically fix the issue.
requires #1466

**Comment by lwrage** [comment]
We can't update because xsemantics still requires xtext 2.12.

**Comment by philip-alldredge** [comment]
@lwrage dblouin Do we have a plan for when we will be able to upgrade to a newer version of Xtext so that this issue will be fixed? This was recently reported again as #1497.

**Comment by lwrage** [comment]
There is now an xsemantics version for xtext > 2.12. available. The plan is that the next OSATE version after 2.3.6 will be photon based with xtext 2.14 or 2.15.

**Comment by lwrage** [comment]
Works after switching to Eclipse 2018-12 with Xtext 2.16.
