### ISSUE TITLE
AADL Navigator Re-orders itself

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate2#1120]
## Summary
The AADL navigator's list of projects often re-sorts itself during tool execution. This is confusing and visually frustrating as I lose track of my projects. 

## Expected and Current Behavior
The ordering of projects in the AADL Navigator view should not change if the user is not changing the projects. 

## Steps to Reproduce
I installed OSATE 2.3.2 vfinal and the ALISA examples. Running the SCSCase causes the navigator list to re-order itself several times. 

Here's a video of the problem: https://youtu.be/tjE5eiGDBNY

## Environment

* **2.3.2 vFinal**:
* **Windows 7**:

**Comment by lwrage** [comment]
I've convinced myself that this is an eclipse bug. There are various eclipse bug reports that mention issues with sorting that seem  to stem from race conditions when concurrently sorting and updating the items being sorted.

**Comment by lwrage** [comment]
It seems that the bad behavior is actually caused by our AadlNavigatorLabelProvider, which is severely messed up. Fixing #1056 will also get rid of the re-ordering.
