### ISSUE TITLE
Flow Latency Parameters

### ISSUE THREAD

**Issue by joeseibel** [osate/osate2#1129]
Flow latency analysis should bring up dialog allowing user to modify the parameters before running the analysis. Load default parameters from the preferences. @reteprelief Does this make sense?

**Comment by reteprelief** [comment]
Interesting idea. Check with Lutz - he has a better view of how to make the UI more consistent.

**Comment by lwrage** [comment]
Parameters for flow latency are currently the ones form the preferences. Bring up a dialog that shows all these parameters, initially filled with the preference values. User can modify the values and run with those values. Save dialog values for next flow latency invocation.

Optional:
- Dialog button "Reset to defaults" to get back defaults from preferences
- Dialog button "Save as defaults" to save dialog values into preferences
- Checkbox "Use these values automatically in the future" to not show the dialog again. Then we need a way to get the dialog back, maybe via a checkbox in the preferences.

**Comment by AaronGreenhouse** [comment]
Here is the proposed dialog box for this:

![flow-latency](https://user-images.githubusercontent.com/16961842/45510008-077dce80-b767-11e8-83d8-aa3f27587e54.png)


For comparison, here is the current preference pane for flow latency:

![flowlatencyprefspane](https://user-images.githubusercontent.com/16961842/45510058-28462400-b767-11e8-8ae9-796829d7b918.png)

**Comment by AaronGreenhouse** [comment]
From phone call with Lutz:
- Make clear in the Preference Pane that this are the *default* vaues
- Analysis should remember the dialog values and reuse them the next time.  Only use the preference pane values when the "Restore Defaults" button is pressed.
- Rename the "Save to Preferences" button as "Save as Defaults"
- Still need to do the "Don't show" button

**Comment by AaronGreenhouse** [comment]
Also, this is a test case.  Similar dialog may be used with the fault tree analysis.

**Comment by AaronGreenhouse** [comment]
Finished this.
