### ISSUE TITLE
Need a way to  find unused classifiers in a package

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#1135]
There should be a way to check a single package or all packages in a directory or project for unused elements. This is probably most useful for classifiers.

Currently one has to select each classifier individually and display the references to it.

child of #1371

**Comment by AaronGreenhouse** [comment]
Okay, general principle of operations:
1. Find all the classifiers declared in a package
2. For each classifier, find all references to it.  (Limited to what scope?  Everything, I should think.)
3. If the declaration has no references, create a warning marker.
4. Bonus points: use a quick fix on the warning marker to remove the declaration.

This should be a command in the context menu for a package.  Probably also should be applicable across an entire package (scan all the packages In the project (and the projects it depends on)).

**Comment by AaronGreenhouse** [comment]
Making a test project for this and I just realized the obvious: _the top-level system is always going to be viewed as unused_.  

Do we want some kind of heuristic to avoid flagging this, or do we just let the user sort it out?

**Comment by AaronGreenhouse** [comment]
Basic analysis is done.  Markers are generated.

Problem: What ever mechanism "opens markers" from the problem view doesn't open the URI embedded in the marker I generate.  Soemthing needs to be updated to handle this.

Next step: look into quick fixes.

**Comment by AaronGreenhouse** [comment]
Double-clicking on the marker causes the `XtextEditor` to open on the `.aadl` file, and the `IGotoMarker` implementation it uses tries to use text positions from the marker.  I cannot figure out how to introduce something into the middle that hijacks the process and uses the same mechanism we use in the search results view and AADL Navigator view to jump to URIs.

I'll come back to this after looking at quick fixes.

**Comment by AaronGreenhouse** [comment]
**Quick fixes:** use the extension point `org.eclipse.ui.ide.markerResolution`

Need to implement `IMarkerResolutionGenerator` and specific `IMarkerResolution` classes.  Subclass `WorkbenchMarkerResolution` to allow the applying multiple resolutions at once.

**Comment by AaronGreenhouse** [comment]
Marker resolution is done. 

Need to figure out the editor opening problem still.

**Comment by AaronGreenhouse** [comment]
I got the marker location problem fixed.  I dug around in the Xtext stuff for a while, and I found that it uses `ILocationProvider` instances to get the text location of `EObjects`.  I updated my marker creation to use this to add start and end attributes to the marker.  This makes things work.  I left the URI in the marker as well, because it seems like it should be useful for something.

**Comment by AaronGreenhouse** [comment]
Moved from `org.osate.ui` to `org.osate.analysis.architecture`.  Moved the menu command to be in a new `Model Maintenance` submenu.

Still need to move navigator action over.

**Comment by AaronGreenhouse** [comment]
Navigator action moved over

**Comment by AaronGreenhouse** [comment]
Added help file.

Added autogeneration of `html` from `md`
