### ISSUE TITLE
Potential AnnexParseUtil Thread Safety

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2#1146]
## Summary
While using OSATE(with the graphical editor), the user interface hung. Two thread dumps are attached. They are taken from the same event. Multiple dumps were taken to allow looking for changes in the thread's state.
[d3.txt](https://github.com/osate/osate2/files/1924022/d3.txt)
[d2.txt](https://github.com/osate/osate2/files/1924024/d2.txt)

From my perspective, it looks like the issue is in AnnexParseUtil's usage of the parseResults hash map internally.  The main thread is stuck in a loop in WeakHashMap while trying to put an entry into the map.  I believe this indicates that the data structure is corrupted since the thread doesn't block and is in a seemingly endless loop. I suspect that synchronizing the usage of the map would fix the issue. However, I'm not aware of what could have triggered such behavior. I suspect it is Xtext performing a rebuild while the graphical editor is opening a resource. Unable to confirm.

## Steps to Reproduce
Unable to reliable reproduce. As the time it occurred I performing small changes and saves to various resources and selecting various Eclipse views.

## Environment

* **OSATE Version**:
* **Platform**:  Windows

**Comment by lwrage** [comment]
@philip-alldredge I can't look at the thread dumps. I only get a 404 error when clicking on the links.

**Comment by philip-alldredge** [comment]
@lwrage I updated the post to take the -core out of the URL. That seems to have fixed the links.

**Comment by lwrage** [comment]
I'll synchronize the WeakHashMap.
