### ISSUE TITLE
Old fault trees cannot be opened in new version of OSATE

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#1164]
Heard that in a telecon, need to check if this is really the case. Fault tree was created in OSATE 2.2.2, could not be opened in OSATE 2.3.2.

**Comment by reteprelief** [comment]
Could not recreate the problem starting from 2.3.2 or 2.3.1. If the problem came from RC they did the original fault trees in emfta, which obviously cannot be opened in the new fta implementation.
