### ISSUE TITLE
Support Running OSATE Analysis from Graphical Editor

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2#1201]
<a href="https://github.com/philip-alldredge"><img src="https://avatars2.githubusercontent.com/u/1376364?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [philip-alldredge](https://github.com/philip-alldredge)**
_Wednesday Feb 14, 2018 at 16:34 GMT_
_Originally opened as https://github.com/osate/osate-ge/issues/293_

----

Support running OSATE analysis based on selection in the graphical editor. Should be supported both in the diagram and the outline. For example: Check code-gen pre-requisites.

**Comment by smithdtyler** [comment]
Is this extensible by other plugins?

**Comment by philip-alldredge** [comment]
This issue is for support the analysis included in OSATE. There are existing mechanisms for running other tools from the graphical editor. Please add a question to the OSATE google group and I'll respond there.

**Comment by philip-alldredge** [comment]
Reduced to medium. Many(most?) analysis just require the instance model and instantiation is already supported.

**Comment by philip-alldredge** [comment]
This should be revisited once #841 is implemented.
