### ISSUE TITLE
Bendpoints created by layout algorithm makes manual layout difficult

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2#1210]
<a href="https://github.com/philip-alldredge"><img src="https://avatars2.githubusercontent.com/u/1376364?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [philip-alldredge](https://github.com/philip-alldredge)**
_Tuesday Apr 10, 2018 at 16:26 GMT_
_Originally opened as https://github.com/osate/osate-ge/issues/329_

----

The layout algorithm introduces bendpoints for connections which make manual layout more difficult. One option would be to add a context menu that will remove bendpoints from all the selected connections. 

Consider an option to layout connections without bendpoints.

**Comment by paolo-crisafulli** [comment]
Hi Philip,
I see this issue has been delayed.
Just to let you know that my team and I are still very interested (some team members stick to osate 2.3.0 because of the too many bendpoints in later versions automatic layout).

**Comment by paolo-crisafulli** [comment]
Got it, thank you for your answer.

**Comment by paolo-crisafulli** [comment]
For the record, the issue was created after this discussion:
https://groups.google.com/forum/#!topic/osate/I4pqPhrj-LY

**Comment by philip-alldredge** [comment]
This will be implemented by adding two new commands. 

**Layout->Remove Bendpoints** - Will remove all bendpoints from the selected connections..
**Edit->Select All Connections** - Will select all connections in a diagram.

The combination of these two commands will make it easy to remove all bendpoints from all connections if the user wishes to do so.

**Comment by paolo-crisafulli** [comment]
Thank you, very useful!
