### ISSUE TITLE
Additional flow editing capabilities

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2#1212]
<a href="https://github.com/philip-alldredge"><img src="https://avatars2.githubusercontent.com/u/1376364?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [philip-alldredge](https://github.com/philip-alldredge)**
_Tuesday Apr 24, 2018 at 19:07 GMT_
_Originally opened as https://github.com/osate/osate-ge/issues/333_

----

Implement Support for End to End Flows - https://github.com/saeaadl/aadlv2.1/issues/7
  - Entire end to end flow isn't required. (Just flow source and sink)

requires #675

**Comment by lwrage** [comment]
Partial end to end flows are not supported in OSATE and nobody has complained yet.

**Comment by smithdtyler** [comment]
I would really like the ability to create end to end flows in the graphical editor.

**Comment by philip-alldredge** [comment]
@smithdtyler  While partial end to end flows are not supported, the creation of end to end flows is supported. There are definitely rough edges but no known users preventing its usage.

**Comment by smithdtyler** [comment]
@philip-alldredge I didn't know that, thanks! For anyone else reading this issue, I found instructions for the creating end to end flows in the Graphical Editor section of the OSATE Help menu.

**Comment by philip-alldredge** [comment]
See related #1774

**Comment by philip-alldredge** [comment]
Need to compile a list of all related issues and specific improvements that will be implemented.

**Comment by philip-alldredge** [comment]
@RyanMcilnay keep in mind that beyond editing flows we need a way to:
- Refine flows
- Delete Flows/Delete Refinements

In this context, flows are flow implementations or end-to-end flow specifications.
