### ISSUE TITLE
OSATE does not include Code Generation Annex property set

### ISSUE THREAD

**Issue by rinsley** [osate/osate2#1220]
OSATE includes the ARINC653 property set from the ARINC 653 Annex, and the Data_Model and Base_Types files from the Data Modeling Annex. I would expect the Code_Generation_Properties property set from the Code Generation Annex to also be included, but it is not.

**Comment by lwrage** [comment]
@reteprelief Should this be part of OSATE?

**Comment by reteprelief** [comment]
Yes. It makes sense to include the property set from that Annex.
If we go the other way someone could argue that we should not include the Data Modeling and ARINC653 annex material.
All three are standards.

**Comment by lwrage** [comment]
@reteprelief Can you attach the property set file to the issue, please?

**Comment by reteprelief** [comment]
From the Annex document:

property set Code_Generation_Properties is
Convention: enumeration (AADL, Legacy) => Legacy 
       applies to (subprogram);
--  Under the Legacy convention, no context information 
--  for port variables is generated. 
--  The AADL convention generates such information
Parameter_Usage: enumeration (By_Value, By_Reference)
     		applies to (data access, parameter);
Return_Parameter: aadlboolean => false applies to (parameter);
  	-- if true, out parameter is actually a return parameter
end Code_Generation_Properties;
