### ISSUE TITLE
Incorrect error about feature directions in inverse feature group

### ISSUE THREAD

**Issue by rinsley** [osate/osate2#1233]
I'm getting an error in this snippet of AADL in the AADL text editor:

	feature group OutputGroup
		features
			Out1: out feature;
	end OutputGroup;
	
	feature group OutputGroupInverse inverse of OutputGroup
	end OutputGroupInverse;

	system Sys
		features
			IG1: in feature group inverse of OutputGroup;
			IG2: in feature group OutputGroupInverse;
	end Sys;

IG1 and IG2 should both be valid as "in" direction groups, but IG2 is giving the error "All ports, parameters, feature groups, and abstract features in the referenced feature group type must satisfy the direction specified in the feature group."

**Comment by lwrage** [comment]
There are various edge cases where it is unclear what should be considered a valid model, e.g., feature groups without a type, feature groups with an empty type.
Also, should access features in a feature group be ignored in the validation, or should they result in an error?
