### ISSUE TITLE
Error creating diagram: Unexpected editor: null

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#1245]
<a href="https://github.com/stevevestal"><img src="https://avatars2.githubusercontent.com/u/3299870?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [stevevestal](https://github.com/stevevestal)**
_Wednesday May 16, 2018 at 09:17 EDT_
_Originally opened as https://github.com/osate/osate2-core/issues/1_

----
@stevevestal
## Summary
I went to the Outline view, right-clicked on a system implementation, and selected Create diagram...

I got a pop-up with the name and Structure Diagram selected.  I pressed OK.

After a few seconds delay, I got an error pop-up from org.osate.ge that gave me the title of this issue.  Here is a cut-and-paste of a few lines from the log:
```
!ENTRY org.osate.ge 0 0 2018-05-16 08:13:01.827
!MESSAGE org.osate.ge.internal.ui.handlers.CreateDiagramHandler.execute(): CreateDiagramHandler Started

!ENTRY org.eclipse.e4.ui.workbench.swt 4 2 2018-05-16 08:13:55.005
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.e4.ui.workbench.swt".
!STACK 0
java.lang.NoSuchFieldError: ASYMMETRICAL
	at org.osate.ge.internal.diagram.runtime.layout.ElkGraphBuilder.createElkGraphElementForNonLabelAndUndockedShape(ElkGraphBuilder.java:459)
	at org.osate.ge.internal.diagram.runtime.layout.ElkGraphBuilder.lambda$2(ElkGraphBuilder.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Unknown Source)
        ......
```
## Expected and Current Behavior
Expected a diagram to appear rather than a fatal error pop-up.

## Steps to Reproduce
The model is too large to cut-and-paste here, but I can SAFE it if desired.  I was able to reproduce this.

## Environment

* **OSATE Version**: Nightly test as of the date of this issue
* **Operating System**: Windows 10

**Comment by stevevestal** [comment]
This was because I was installing OSATE into Eclipse that, it turns out, had an earlier version of ELK than was required.  Manually updating to the proper ELK version fixed this problem.
