### ISSUE TITLE
Diagrams are automaticly marked as changed

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2#1246]
## Summary
When I save a diagram, a few seconds later the Zoom Out icon flickers a few times, and the diagram is marked dirty again.  I do not see any visual changes in the diagram itself.  Selecting save causes this behavior to repeat.

## Steps to Reproduce
This always happens for me, but I suspect it might have to do with my configuration.  I am running this as an Eclipse Application from within Eclipse RCP.  (I would rank this low priority/ a curiosity unless it is happening in more typical user configurations.)

## Environment

* **OSATE Version**: OSATE nightly test installed into Eclipse Oxygen RCP with ELK 0.3.0.
* **Operating System**: Windows 10

**Comment by stevevestal** [comment]
Not all diagrams.  Only some.  The only difference I can see is that the ones that auto-dirty are too large (at the default 100%) to fit in any single screen.  Changing the default zoom, or shrinking the window size for the diagram that does not do this, doesn't make any difference.

**Comment by philip-alldredge** [comment]
This should be investigated when looking at similar issues. See #1199.  The more information the better but when we rework how the dirty detection is determined, this issue should be fixed.

**Comment by philip-alldredge** [comment]
Fixed in ebd75e16291c96a3346660cbc35009c94f989b5e
