### ISSUE TITLE
Opening diagram from text editor

### ISSUE THREAD

**Issue by RyanMcilnay** [osate/osate2#1313]
## Summary
Opening a diagram from the text editor always opens the package diagram the first time after opening the text editor.
It should open the associated diagram of the element that is selected in the text editor.

## Steps to Reproduce
1. Open text editor.
2. Right click element.
3. Click <em>Open Diagram</em>.

**Comment by lwrage** [comment]
I think it is good enough if diagrams can be opened from the outline view.

**Comment by philip-alldredge** [comment]
The issue is caused by the evaluation context provided to the handler by Eclipse not having an up to date selection. The issue affects more than just that handler.

**Comment by philip-alldredge** [comment]
Followup: the evaluation context contains a previous selection. Using the current selection for the window results in the selection based on the location of the caret. Neither selection is based on the mouse location. This later behavior is consistent with context menus in the AADL and other eclipse text editors.
