### ISSUE TITLE
Spurious "Rename AADL Project" Eclipse Tasks on file save

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate2#1319]
## Summary
When I save a non-AADL file, I see one or more tasks called "Rename AADL Project" in my Eclipse task status window. 

## Expected and Current Behavior
I don't have any AADL projects in my workspace, so I should not see this task running. 

## Steps to Reproduce
1. Install Eclipse
2. Install OSATE 
3. Create a Java project
4. Edit Java files
5. Observe the task window in Eclipse

## Environment
Eclipse Oxygen 3a
OSATE 2.3.4.v20180531
Windows 7

**Comment by lwrage** [comment]
This is as expected. OSATE installs a resource listener to check if an AADL project was renamed. This kicks in for all changes to resources in the workspace.

**Comment by smithdtyler** [comment]
I'm seeing 10+ concurrent "Rename AADL Project" tasks simultaneously. 
![screen shot 2018-12-03 at 10 40 54 am](https://user-images.githubusercontent.com/8142684/49387701-1e89e800-f6e8-11e8-99fb-135bfb4be6f2.png)

**Comment by lwrage** [comment]
Does this cause any problem?

**Comment by smithdtyler** [comment]
It's hard to tell whether CPU is being eaten up, at a minimum it's
confusing and hides the actual job being run.
