### ISSUE TITLE
Exception when serializing EMV2

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2#1327]
Using the test case below, an exception is thrown. This was found while working with the graphical editor. In the graphical editor's case, the save appears to succeed but it is unclear what the side effects are. 

There are multiple problems demonstrated by the test case. The first error can be resolved by making EMV2AnnexUnparser public. Once that is done, other exceptions will be thrown. The latter exceptions only occur if there are more than one EMV2 subclause in the package.

Interestingly, the test does not fail even though many exceptions are thrown. I believe this is due to the exception being thrown in another thread. I am unaware of a mechanism to test for such errors.

## Steps to Reproduce
1. Run the test case below.

## Test Case
```
package org.osate.core.tests.issues

import com.google.inject.Inject
import com.itemis.xtext.testing.XtextTest
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.junit.Test
import org.junit.runner.RunWith
import org.osate.aadl2.AadlPackage
import org.osate.testsupport.TestHelper

import org.eclipse.xtext.resource.SaveOptions
import com.google.common.io.ByteStreams
import org.osate.testsupport.Aadl2UiInjectorProvider

@RunWith(XtextRunner)
@InjectWith(Aadl2UiInjectorProvider)
class Issue_NEW extends XtextTest {

	@Inject
	TestHelper<AadlPackage> testHelper;
	
	@Test
	def void issueNew() {
		val pkg = testHelper.parseString(aadlText)

		pkg.eResource().save(ByteStreams.nullOutputStream, SaveOptions.newBuilder().format().getOptions().toOptionsMap());
		 
	}
	
	val aadlText = '''
		package issue_new
		public
			system top
				annex EMV2 {**
				**};
			end top;
		
			system top2
				annex EMV2 {**
				**};
			end top2;
		end issue_new;
	'''
}

```

## Environment

* **OSATE Version**: Develop
* **Operating System**:  Windows 10
* **Java Version**: 1.8.0_141

**Comment by lwrage** [comment]
Tests involving annexes must use Aad2UiInjectorProvider.

**Comment by philip-alldredge** [comment]
Okay. Good to know. This issue was originally seen in the graphical editor. The test was just written to make it easier to reproduce.

**Comment by philip-alldredge** [comment]
I have updated the issue to use Aadl2UiInjectorProvider in the test case. However, rerunning the test case while using Aadl2UiInjectorProvider results in the same result.

**Comment by philip-alldredge** [comment]
This can also occur when deleting classifiers in the graphical editor if the model contains EMV annex.

**Comment by lwrage** [comment]
This is also an issue in the use types step of the FHA workflow.

**Comment by lwrage** [comment]
The unparser must be public, other exceptions are from the emv2 formatter.
