### ISSUE TITLE
The model statistics command disappeared

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2#1375]
OSATE used to provide a way to report on the size of an AADL model. This command is no longer available.

**Comment by lwrage** [comment]
It was removed when we reorganized the UI, and I don't think we should add it back in.

**Comment by reteprelief** [comment]
Why not? It is a useful capability to determine the size of a model. See also https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/osate/EUF0FRCJ1xI/RQX-bhHlAQAJ

**Comment by lwrage** [comment]
However, what's the model? A package? A workspace project? A project and it's dependencies (except predefiend stuff)? Everything in the workspace? Everything used in an instance model?
If we provide statistics we should first determine what the plugin should really do. I am pretty sure that we would need to update the existing functionality.

**Comment by reteprelief** [comment]
The most useful measures are those for an instance model. Maybe Tyler has an opinion on measure relative to declarative models (see his post on Google groups).
