### ISSUE TITLE
Unnecessary Plug-in Dependencies

### ISSUE THREAD

**Issue by joeseibel** [osate/osate2#1376]
We should remove all unnecessary plug-in dependencies.

**Comment by lwrage** [comment]
Leave this open. There are likely more dependencies that can be removed.

**Comment by lwrage** [comment]
Found that org.osate.workspace depends on UI plugins. When building/running standalone this pulls in unnecessary UI plugins. Either remove dependency or put contributed AADL into another plugin.

**Comment by AaronGreenhouse** [comment]
Looking at `IAadlProject` interface and its implementation `AadlProject`.  The interface is used within the plug-in, but not really anywhere else.  `OsateCorePlugin.create()` returns an `IAadlProject`, but nothing ever calls it.  Nothing calls the methods in `IAadlWorkpace` that return `IAadlProject`.

The only thing outside the plug-in that uses `IAadlWorkspace` is `OsateCorePlugin.create()` but nothing ever calls it.

**Comment by AaronGreenhouse** [comment]
Nothing outside the plug-in uses `IAadlElement`.

**Comment by AaronGreenhouse** [comment]
Interface `IOpenable` isn't even implemented.

**Comment by AaronGreenhouse** [comment]
Interface `IParent` is only extended by `IAadlWorkspace` which we've already seen is useless.

**Comment by AaronGreenhouse** [comment]
Exception `AadlModelException` is only used by `IAadlElement` and friends.

**Comment by AaronGreenhouse** [comment]
I'm going to get rid of the above classes/interfaces.

**Comment by AaronGreenhouse** [comment]
Also got rid of `OsateCorePlugin.create()`

**Comment by AaronGreenhouse** [comment]
Utility class `ForAllIFile` is completely unused.  Going to delete.

**Comment by AaronGreenhouse** [comment]
`PreferenceInitializer` is referenced in the `plugin.xml` file.  It is used to set the default values for the workspace preference values.  This probably should *not* be in the "internal" package `org.osate.internal.workspace`.

**Comment by AaronGreenhouse** [comment]
Classes `CharOperation` and `CoreUtility` are unused.  Removing.

**Comment by AaronGreenhouse** [comment]
`IResourceUtility` is only used by `ReinstantiateAadl.getCurrentSelection()`.  It uses the method `isInstanceFile`.  This should be changed to have a local test method, or test in more simplified manner.  The `isInstanceFile` method seems heavy-weight.

**Comment by AaronGreenhouse** [comment]
The plug-in contains a copy of `antlr.jar` that is reexports.

**Comment by AaronGreenhouse** [comment]
The plug-in contains the standard predeclared property sets as contributed resource extensions.  These are okay.

**Comment by AaronGreenhouse** [comment]
> The plug-in contains a copy of `antlr.jar` that is reexports.

This is relied upon by `org.osate.annexsupport` and `org.osate.xtext.aadl2`.

**Comment by AaronGreenhouse** [comment]
The plug-in depends on `org.eclipse.ui` because of workbench preferences.  The `getPreferenceStore()` method comes from `AbstractUIPlugin`.   The preference store classes seem to be part of the ui plug-ins.

**Comment by AaronGreenhouse** [comment]
The dependency `org.eclipse.emf.common` doesn't seem to be necessary (at least after removing all the dead classes).

**Comment by AaronGreenhouse** [comment]
`org.eclipse.core.runtime` is needed for `CoreException` in `IResourceUtility`.  Can be removed when this class is dealt with.

**Comment by AaronGreenhouse** [comment]
At this point this package is left with
* The contributed resources
* The bundled `antlr.jar`
* The workbench preference initializer
* The plugin activator.
* The class `IResourceUtility`

As stated above, `IResourceUtility` is only used by `ReinstantiateAadl.getCurrentSelection()`. It uses the method `isInstanceFile`.  What is the right way to test if a file is an instance file?  I searched the rest of the workspace, and everything else is just testing the file extension.  We should update `ReinstantiateAadl` and get rid of `IResourceUtility` which then means we can get rid of the dependencies on `org.eclipse.core.runtime` and `org.eclipse.core.resources`.

The bigger problem is the workbench preferences which unfortunately are tied to the UI.  Clearly these should be separate from the contributed resources. 

Do we really need to be carrying around  `antlr.jar`?

**Comment by AaronGreenhouse** [comment]
`WorkspacePlugin` shows signs of old conventions that are still left around.  
* There are both `SOURCE_FILE_EXT` and `SOURCE_FILE_EXT2`.  Both have the same value.
* There are both `MODEL_FILE_EXT` and `INSTANCE_FILE_EXT`.  Both have the same value.  The code claims that there should be an `.aail2` extension.  `INSTANCE_FILE_EXT` seems to be the surviving extension, and `MODEL_FILE_EXT` seems obsolete.

**Comment by AaronGreenhouse** [comment]
`IResourceUtilty` declares names for resource properties that seem like they should be useful, but no one uses them anywhere:

```
	public static final QualifiedName ResourceWithSyntaxErrors = new QualifiedName("org.osate.ResourceWithSyntaxErrors",
			"BadAadlFile");
	public static final QualifiedName ResourceDerived = new QualifiedName("org.osate.ResourceDerived",
			"IResourceDerived");
	public static final QualifiedName IsInstanceModel = new QualifiedName("org.osate.IsInstanceModel",
			"IsInstanceModel");
```

**Comment by AaronGreenhouse** [comment]
As I said before, the only actual use of anything in `IResourceUtility` outside of itself is in the `ReinstantiateAadl` action handler.  This can be changed to just test the file extension against `WorkspacePlugin.INSTANCE_FILE_EXT` which is what things in the graphics editor and a few others places do.

I'm interested in getting comments on the two above issues (multiple naming conventions and resource properties) before I fully make this change and *remove* the class `IResourceUtility`.

**Comment by AaronGreenhouse** [comment]
Looking `WorkspacePlugin`
* `AADL_PROPERTIES_FILE` is never referenced
* `AADL_PROJECT_FILE` is never referenced
* `AADL_PACKAGES_DIR` is referenced, but I don't understand it's function
* `PROPERTY_SETS_DIR` is never referenced

**Comment by AaronGreenhouse** [comment]
We should separate the workbench preference stuff from the contributed resources.  Ideally I would keep the contributed resources in `org.osate.workbench` and move the workbench preferences to an existing plug-in.  The plug-in `org.osate.ui` is the obvious choice, but most of the workbench preferences references come from `org.osate.xtext.aadl2.ui` and I don't know if it is okay for that plug-in to depend on 'org.osate.ui`.

**Comment by AaronGreenhouse** [comment]
Marking `CharOperation`, `CoreUtility`, and `ForAllIFile` as `@Deprecated`

**Comment by AaronGreenhouse** [comment]
Copied `IResourceUtility.isInsanceFile()` to `org.osate.ui.handlers.ReinstantiateAadl` to remove it's one use.
.

**Comment by AaronGreenhouse** [comment]
Marked `AADL_PROPERTIES_FILES`, `AADL_PROJECT_FILE`, `AADL_PACKAGES_DIR`, and `PROPERTY_SETS_DIR` as `@deprecated`.

**Comment by AaronGreenhouse** [comment]
Removed dependency on `org.eclipse.ui`.  Had to fiddle with a method in `CoreUtility` to make this work.

**Comment by AaronGreenhouse** [comment]
Also moving `antlr.jar` to `org.osate.core`.  Everything that needs it already depends on `org.osate.core`.

**Comment by AaronGreenhouse** [comment]
Removing dependencies on `org.osate.workspace` from
* `org.osate.annexsupport`
* `org.osate.core`
* `org.osate.ocarina`
* `org.osate.xtext.aadl2`
* `org.osate.xtext.aadl2.ui`

**Comment by AaronGreenhouse** [comment]
Actually left the dependencies of `org.osate.ocarina` alone because that is in a different repository.
