### ISSUE TITLE
Confusing error message when installing an already installed OSATE component

### ISSUE THREAD

**Issue by joeseibel** [osate/osate2#1386]
The **Additional OSATE Components Discovery** does not filter components that are already installed. If the user tries to install a component which is already installed, an error dialog with an unhelpful message is displayed.
<img width="595" alt="osate_components_error" src="https://user-images.githubusercontent.com/1824701/42782643-86ab0b24-8917-11e8-846e-0728e97c8df3.png">
The error log contains a stack trace:
```
java.lang.RuntimeException: Operation details
	at org.eclipse.papyrus.infra.discovery.ui.internal.common.PrepareInstallProfileJob.resolve(PrepareInstallProfileJob.java:159)
	at org.eclipse.papyrus.infra.discovery.ui.internal.common.PrepareInstallProfileJob.run(PrepareInstallProfileJob.java:109)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```
We should gray out installed components in the discovery dialog or at least catch the exception and show a meaningful error message.

**Comment by lwrage** [comment]
The Mylyn Connector Discovery has a better dialog that can filter installed components.

**Comment by joeseibel** [comment]
TODO:
- [ ] Build `org.osate.discovery` and put the built jar file online.
- [ ] Point the directory xml file to the jar file.
- [ ] Put the directory xml file online.
- [ ] Point the `org.eclipse.equinox.p2.ui.discovery.commands.ShowBundleCatalog` menu entry to the discovery xml file.
- [ ] Move the `ShowBundleCategory` menu entry from `org.osate.discovery` to `org.osate.ui`.
- [ ] Remove `org.osate.discovery` from the OSATE product.
- [ ] Delete project `org.eclipse.papyrus.infra.discovery`.
- [ ] Delete project `org.eclipse.papyrus.infra.discovery.ui`.
- [ ] Remove unneeded files from project `org.osate.discovery`.
