### ISSUE TITLE
AADL Navigator: Add node that shows project dependencies

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#1463]
The node should expand direct project dependencies. Operations should allow adding and removing dependencies. (Undo!)
Could use drag and drop to add dependency. (Check for cycles!)
child of #1371

**Comment by lwrage** [comment]
Simpler approach for editing project dependencies:
Add context menu to dependencies node ("Modify dependencies...") that opens the corresponding project properties page.

**Comment by AaronGreenhouse** [comment]
1. Just show the depended upon projects.
2. Allow editing of dependencies
