### ISSUE TITLE
OSATE Graphical Editor should move bend points when both ends are moved together

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate2#1476]
When I select a group of objects in an AADL diagram and move them, anchor points on flows and connections between the objects don't move with them. By anchor points I'm referring to "turns" in the line connecting the two objects.

When _both_ objects connected by a flow/connection/etc are moved, all anchor points on that flow/connection should move too.

**Comment by philip-alldredge** [comment]
To clarify things: this affects when the container itself isn't moving. For example, when two subcomponents move, the connection isn't updated. However, when the containers is moved then the connections are updated appropriately. Is this correct?

**Comment by philip-alldredge** [comment]
I think we are in agreement.  Your example is the same as I (attempted) to describe in my comment. I was trying to clarify the case where the issue occurs. However, your example does a good example at illustrating it.

**Comment by philip-alldredge** [comment]
We also need to consider how the implementation of this affects the alignment tools and other tools that perform shape movement.
