### ISSUE TITLE
Export Diagram should auto-crop to the a bounding box of the components in the diagram

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate2#1477]
Every time I export an AADL diagram from OSATE I have to  manually crop the white space around my components. OSATE should auto-crop the generated diagram to make a bounding box around the AADL components, perhaps with 10px buffer.

**Comment by philip-alldredge** [comment]
Due to how this is implemented. The behavior is unlikely to be changed in the near future.  In many cases, there is a single top level element. In that case you can select it and then select "Selected" when exporting the diagram to automatically do the cropping.
