### ISSUE TITLE
Setting a modal path to in-mode does not reflect change

### ISSUE THREAD

**Issue by RyanMcilnay** [osate/osate2#1493]
## Summary
When setting a modal path to **in-mode** using the graphical editor **AADL** properties view, no change occurs.  The in-mode looks like it is set and then removed simultaneously.
We suspect it has something to do with the latest changes made for #1449.

## Steps to Reproduce

1. Create type classifier
2. Create mode, feature, and flow spec
3. Select the flow spec
4. Open properties view
5. Click the mode in the in-mode section

```aadl
package Test
public
	abstract t
		features
			feat: in feature;
		flows
			f_sink: flow sink feat;
		modes
			m1: mode;
	end t;
end Test;
```

## Environment

* **OSATE Version**: 2.3.5 Release
* **Operating System**: Windows 10

**Comment by philip-alldredge** [comment]
This is a regression from 2.3.4.  I suspect it has something to do with out Xtext updates the resource after changes to the model. The model change does not cause a change in the AADL source.

@RyanMcilnay please open an issue for creating an automated test to detect such regressions.
