### ISSUE TITLE
Instance model generator does not include end to end flow instances and gives no error

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2#1508]
From Jerome:
We are finishing a project using SCADE Architect and OSATE. The following model is a complete model exported from SCADE Architect
 
Root system is in A_SystemDefinition, you may instantiate System implementation FlightControlSystem.impl
it triggers 6 warnings we think are legitimate. 
 
when trying to run the latency analysis plug-in, the tool reports nothing: no error, and no report are generated
this seems like a buggy behavior
- either the warning in instantiation are errors that prevent to run the plug-in, and we should have an error message
- or the warning can be ignore, and something could be calculated, as we do have a end-to-end flow.
 
Can you recommend on any solution here ? I’ll work on the model to address warnings, but I’m curious first to know why we get this strange behavior
we tested with OSATE 2.3.2 to 2.3.5 
[FlightControlSystem.zip](https://github.com/osate/osate2/files/2364838/FlightControlSystem.zip)

From Peter:
There is a problem in the instantiation. When processing the second connection to the third flow spec something goes wrong and the instantiator does not record the end to end flow instance.

**Comment by lwrage** [comment]
This was an issue with the model.
