### ISSUE TITLE
Range values in Alisa expression language partially supported

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2#1555]
Users can define a range value as a property or property constant value and then reference the property (constant) as value for a 'val' variable. However, users cannot declare the range value directly as value of a 'val' declaration.
	ExpectedLatencyRange : constant AADL_Project::Time_Range => 12 ms .. 20 ms;

		val ExpectedLatencyRange = #MyConstants::ExpectedLatencyRange
		val ExpectedRange = 12ms .. 20ms  -- error message on ..

**Comment by lwrage** [comment]
Range values must be enclosed in square brackets.
