### ISSUE TITLE
Flows in Subprogram Groups

### ISSUE THREAD

**Issue by joeseibel** [osate/osate2#1563]
The standard specifies that subprogram groups cannot have flows, yet the grammar allows flows in subprogram group types. The following model should produce an error:
```
package Test
public
  subprogram group sg
    features
      f: feature;
    flows
      src: flow source f;
  end sg;
end Test;
```
The grammar already prevents flows in subprogram group implementations.

**Comment by lwrage** [comment]
Fixed in 17ac6cf88643d912b666057497f23d60fddeb071
