### ISSUE TITLE
Value not of units type

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2#1574]
## Summary
Were you asking about the "not of units type" issue earlier?  I can't see if you closed that.  See attached, which I just got with 2.3.5.

![valuenotofunitstype](https://user-images.githubusercontent.com/3299870/46689654-02753900-cbc6-11e8-9a63-5c386d3969db.jpg)

## Steps to Reproduce

No known way to do this repeatably, but I thought I'd let you know this does still appear to be possible.

## Environment

* **OSATE Version**: 2.3.5
* **Operating System**:  Windows 10

**Comment by lwrage** [comment]
This is different from #731. The error message there was _Couldn't resolve reference to UnitLiteral 'ms'._ This is related to validation.

**Comment by lwrage** [comment]
@stevevestal Do you still see this behavior? I cannot reproduce it.
