### ISSUE TITLE
Developer environment setup is failing.

### ISSUE THREAD

**Issue by lgwagner** [osate/osate2#1576]
## Summary
The OSATE developer environment setup is failing on the Perform Setup Tasks step due to an unresolved dependency.

![image](https://user-images.githubusercontent.com/2699181/46690392-c3e07e00-cbc7-11e8-8270-3296fff2e766.png)

## Expected and Current Behavior
Expected behavior: the developer environment setup works.

Current behavior: Previous attempts to install the environment have succeeded without issue. When attempting to install the environment for some collaborators on the DARPA CASE program, this failure was encountered. This has been reproduced by 2 other collaborators in Windows (64-bit) setup environments.

Final error:
 ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: artificial_root 1.0.0.v1539108049715 requires 'de.libutzki.xtext.nodemodeloutline.feature.feature.group 0.0.0' but it could not be found

## Steps to Reproduce

Following the instructions at: http://osate.org/setup-development.html
Failures occur on step 7 on the above instructions, when performing setup tasks.

## Environment
JRE: Java 1.8.0_181
Eclipse Installer 1.9.0 Build 3652
Every other option is set as shown in the instructions linked above.

**Comment by lwrage** [comment]
A repository reference was missing in the setup file.
You can finish the installation by following these steps:
1. Start OSATE
2. Open the git perspective
3. pull from repository osate2
4. Run the updated setup (Help -> Perform Setup Tasks... -> Finish)

**Comment by lgwagner** [comment]
Thank you!
