### ISSUE TITLE
Subprogram and Subprogram Group Access Icons are Reversed

### ISSUE THREAD

**Issue by dpgluch** [osate/osate2#1590]
## Summary
Subprogram and subprogram group access arrows are backwards within the graphical editor.

## Expected and Current Behavior

Expected: Slide with graphic showing standard access icons is attached.
![slide](https://user-images.githubusercontent.com/24554086/46831041-45731000-cd70-11e8-90ad-41adc6869fd0.png)

Current Behavior: Output from graphic editor is attached. Both access icons on T2 are requires access. (subprogram & subprogram group) 
![editor](https://user-images.githubusercontent.com/24554086/46831123-89feab80-cd70-11e8-8ed7-776c9ee77780.JPG)

## Steps to Reproduce
1. load the AADL text
2. produce the graphic

```aadl
subprogram compute_it
end compute_it;
	
	
	thread T1
  features
    shared_sub: provides subprogram access compute_it;
end T1;
thread implementation T1.impl
  subcomponents
    my_sub: subprogram compute_it;
  connections
    c1: subprogram access my_sub <-> shared_sub;
end T1.impl;

thread T2
		features
			ext_sub: requires subprogram access compute_it {
						Subprogram_Call_Rate => [Value_Range => 2.0 .. 2.0;
									Rate_Unit => perDispatch;
									Rate_Distribution => Fixed;];
					};
			ext_subgroup: requires subprogram group access;
	end T2;

process P2T
--		features
--			P2T_new_feature: out data port;
	end P2T;

process implementation P2t.basic
	subcomponents
		T1: thread T1.impl;
		T2: thread T2;
	connections
		saConn: subprogram access T1.shared_sub <-> T2.ext_sub;
		
end P2t.basic;
```

## Environment

* **OSATE Version**: present in 2.3.5 through to the latest 2.3.6 testing (10/11/2018) version
* **Operating System**: Windows 7 Enterprise

**Comment by philip-alldredge** [comment]
What is the source for that example slide? The behavior of the graphical editor is consistent with the with the standard. Reference: AS5506C D.2 (29). This appears to be an error with the example slide.

**Comment by dpgluch** [comment]
Hi Philip,

I am a bit confused. The slide is from the SEI AADL course and has been unchanged for years. I have always used the convention shown in the slide.

I don’t have immediate access to the standard document you referenced. Is it the standard from 2011 “SAE Architecture Analysis and Design Language (AADL) Annex Volume 1:Annex A: Graphical AADL Notation, Annex C: AADL Meta-Model and Interchange Formats, Annex D: Language Compliance and Application Program Interface Annex E: Error Model Annex”?

I have a draft version of AS5506/1 for the graphic editor (2006). I think it was a preliminary version for the release. It is not as clear as it should be. Maybe the final version is similar.  Could you send me an excerpt?

The convention for subprograms we use follows the data access provides – requires connection structure, e.g. from a data component to a requires access feature possibly with an intervening provides access.

Unless something has changed recently that I missed, there is a disconnect.

I will try to locate a copy of the standard you mentioned (I know I had one somewhere)  but since I am remote,  I may need to connect with Peter to figure this out.

Dave

**Comment by lwrage** [comment]
The slide is wrong. Unfortunately the standard is inconsistent! For bus and data access the symbols point _away from_ the shared subcomponent, but for subprogram (group) access the symbol points _toward_ the shared component.
@reteprelief FYI
