### ISSUE TITLE
ALISA executes code that is part of models

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#1604]
ALSIA currently executes Java and Python code that is part of a model. While convenient, this is a problem from a security point of view.
Execution of such code should at least require explicit user permission.
child of #1570

**Comment by reteprelief** [comment]
While Java or Python code is prototyped it resides in the same workspace as the models. It is constructed as plugin project.
Once stable that project can be made part of an OSATE installation.

In case of Resolute code, that code is interpreted. Users just need to be aware that Resolute supports call out to (external) Java code.

**Comment by lwrage** [comment]
If we want to keep this functionality we need a way to prevent execution of java/python that wasn't written on the local machine. Maybe we can generate a unique ID in OSATE (per workspace, installation, or computer) that must be included in the script. The script would be executed only if the ID in the script matches the ID in OSATE.
