### ISSUE TITLE
Flow latency analysis no longer returns analysis result structure

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#1605]
Currently results are returned as EList<Result>.
All analyses should always return the results in an AnalysisResult structure.

**Comment by reteprelief** [comment]
It does return the AnalysisResult structure. Check out the class LatencyAnalysisService.

**Comment by lwrage** [comment]
@reteprelief I only noticed that the previously available methods in the ...Switch class now return ELists. If the API is supposed this new class then javadoc needs to be added there and the old methods should no longer be public to avoid confusion about what is API and what isn't.

**Comment by lwrage** [comment]
see previous comment
