### ISSUE TITLE
Extended Classifier Cycles Cause GE Lock-Up

### ISSUE THREAD

**Issue by RyanMcilnay** [osate/osate2#1620]
## Summary
Creating a cycle of extended classifiers locks the graphical editor up.  Seems to only happen when at least one classifier has an implementation with multiple children.

## Steps to Reproduce
1. Create a type classifier with 2 features
2. Create another type classifier
3. Create an implementation
4. Set first classifier to extend second classifier
5. Set the second classifier to extend the first classifier

```aadl
package pkg
public
	abstract a1 extends a2
		features
			f2: in feature;
			f1: in feature;
	end a1;

	abstract a2 extends a1
	end a2;

	abstract implementation a1.impl
	end a1.impl;
end pkg;
```

## Environment

* **OSATE Version**: 2.3.5 Release
* **Operating System**: Windows

**Comment by RyanMcilnay** [comment]
@lwrage This bug was found during testing for latest release.

**Comment by lwrage** [comment]
That model also kills the text editor. The issue is an infinite loop in `org.osate.xtext.aadl2.validation.Aadl2JavaValidator.sortNamedElements()`
