### ISSUE TITLE
AADL Navigator: New AADL package is not inserted in correct order

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#1622]
## Summary

Creating a new AADL package inserts it as the first element in the project.

## Expected and Current Behavior

The common navigator framework tries to insert the new package in the correct location but our sorters seem to be wrong. We currently refresh the navigator (see #1608) to force sorting but this is not the correct solution.

## Environment

* **OSATE Version**: 2.3.6
* **Operating System**: all

**Comment by lwrage** [comment]
Check if setting parent fixes the issue.

**Comment by lwrage** [comment]
Setting parent has nothing to do with this.

**Comment by lwrage** [comment]
(@philip-alldredge FYI) The real issue is that `org.osate.ge` registers a label provider for `IResource` with highest priority (`navigatorContent` `org.osate.ge.navigatorContent`) but without a sorter. As a result, new folders and files are contributed by this `navigatorContent` and sorted by priority order, so they are added at the top.
The label provider only considers `*.aadl_diagram` files, so we need to add that to the enablement of the `navigatorContent`.

**Comment by philip-alldredge** [comment]
On a related note. What is the policy for removing deprecated functionality? Is there a recommended time limit? That label provider is used for legacy diagrams which use UUIDs as the file names. Once such a diagram is opened, it is converted and renamed. At some point it will be removed. Do we have a best practice/recommendation for how many versions to wait before removing such functionality?

**Comment by lwrage** [comment]
@philip-alldredge 
Does this really do anything for UUID file names? The check `isApplicable()` matches `*.aadl_diagram`. Also, is the `innerLabelProvider` ever set?

Do you remember which version of OSATE introduced the new file name convention for diagrams?

**Comment by philip-alldredge** [comment]
@lwrage Yes, it does convert UUID file names as long as they have the .aadl_diagram extension.  It doesn't appear that innerLabelProvider is ever used.  How the GE actually determines the name based on the UUID is in the DefaultDiagramService. If the filename isn't a UUID then it just returns the filename.

According to the release notes version 2.2.3 (August 21th, 2017) was when stopped using UUIDs for new diagrams. The file format changed and the user is prompted to rename if opening older diagrams.

**Comment by lwrage** [comment]
@philip-alldredge Ah, ok, somehow I thought you meant file names consisting of just a UUID without extension.
