### ISSUE TITLE
EMV2 ErrorType qualified name is incomplete

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2#1634]
## Summary
If getQualifiedName() is called on an ErrorType, it just returns the name. Similarly, getNamespace() returns null for ErrorType instances. Qualified names would be useful to allow showing the full references to an error type in the graphical editor.

**Comment by keh181** [comment]
@philip-alldredge I have submitted a pull request ( PR #2548 ) that should resolve this issue. If you could take a look at it and let me know whether it fixes the issue for you that would be great.
