### ISSUE TITLE
Why is required bus access treated differently than bus subcomponents?

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2#1639]
## Summary

A bus that is accessed via a "requires access" declaration is treated differently than a bus declared as an internal subcomponent.  Shouldn't a bus object be a bus object regardless of how it is made visible within an implementation?

## Expected and Current Behavior
I think both declarations below should be legal.  A similar example can be constructed for data objects.

## Steps to Reproduce

```aadl
	system Example
		features
			externalBus: requires bus access;
	end Example;
	
	system implementation Example.Impl
		subcomponents
			internalBus: bus;
		properties
			-- Why is this declaration legal
			Actual_Connection_Binding => (reference (internalBus));
			-- but this one is not?
			--Actual_Connection_Binding => (reference (externalBus));			
	end Example.Impl;
```

## Environment

* **OSATE Version**: nightly test
* **Operating System**: Windows 10

**Comment by lwrage** [comment]
This behavior is in line with the standard: Property `Actual_Connection_Binding` is defined as a reference to a processor, virtual processor, bus, virtual bus, device, system, or  memory _component_ as in your first example. In your second example the value is a reference to a feature, so OSATE marks it as an error.
