### ISSUE TITLE
Signature match in classifier substitution check is not implemented.

### ISSUE THREAD

**Issue by rob-edman** [osate/osate2#1660]
## Summary

This is more of a feature request than a bug. The signature match option for the Classifier_Substitution_Rule is supposed to match when "the original type has a subset of features of the substitute type". In the current versions of OSATE, this match is not implemented and attempting to use the signature match option produces the info:

"Signature Match checking in classifier substitution of refinement check not implemented yet."

Provided sample model contains matching and non-matching system implementations. Inline comments should be self explanatory. 

```
package classifier_test
public
	data good_data
	end good_data;
	
	abstract sample_abstract_foo
		features
			matching: in data port good_data;
	end sample_abstract_foo;
	
	system sample_system
		properties
			-- pick your classifier match here
			-- Classifier_Substitution_Rule => Classifier_Match;
			-- Classifier_Substitution_Rule => Type_Extension;
			Classifier_Substitution_Rule => Signature_Match;
	end sample_system;	
	
	process nonmatching_process
	end nonmatching_process;
	
	process signature_matching_process
		features
			matching: in data port good_data;	
			foo: in data port;
			bar: out data port;
	end signature_matching_process;

	system implementation sample_system.base
		subcomponents
			abs: abstract sample_abstract_foo;
	end sample_system.base;
	
	system implementation sample_system.matching extends sample_system.base
		subcomponents
			abs: refined to process signature_matching_process; -- this should have no errors when using Signature Matching
	end sample_system.matching;
	
	system implementation sample_system.nonmatching extends sample_system.base
		subcomponents
			abs: refined to process nonmatching_process; -- this should produce an error or warning when using Signature Matching
	end sample_system.nonmatching;
end classifier_test;
```

## Environment
Reproduced in Linux 4.15.0-39-generic #42-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
OSATE 2.3.5-vfinal and OSATE 2.3.6-vfinal

**Comment by lwrage** [comment]
@rob-edman It is unlikely that we will implement this in OSATE.

**Comment by lwrage** [comment]
Supported substitution rules are documented at http://osate.org/osate-roadmap.html#roadmap-for-aadl-language-support
