### ISSUE TITLE
Font scaling calculation for diagrams is wrong on Linux

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#1661]
## Summary

The current calculation decreases the font size for higher resolution displays.

## Expected and Current Behavior

After upgrading to Eclipse 2018-09 as the basis for OSATE fonts in diagrams on my laptop are shown in smaller size. It turns out that the dpi calculation in SWT was changed for GTK >= 3.22.0 to report the real screen dpi based on resolution and screen size. The previous version reported 96 dpi (incorrect), now it is 158 dpi, which is the correct value.

The calculation in https://github.com/osate/osate2/blob/d16b8208969b4e86903bbbf7daaf3449f6f23caf/ge/org.osate.ge/src/org/osate/ge/internal/graphiti/diagram/TextUtil.java#L47
is wrong as it decreases the font size for resolutions > 96 dpi.

## Environment

* **OSATE Version**: 2.4.0 SNAPSHOT
* **Operating System**: Kubuntu 18.04 with GTK 3.22.30

required by #1466

**Comment by lwrage** [comment]
Changing form 96/dpi to dpi/96 results in too large fonts. There is an X dpi setting (which is set to 96 dpi), but there seems to be no way to get that setting using a public OS independent method in SWT.

It seems the best solution would be to
- fix the calculation
- add a preference setting that allows the user additional control of font scaling and change the calculation to unscaledFontSize * device.getDPI().y / 96.0 * <scaling factor from preference>.

**Comment by lwrage** [comment]
Need to test on Windows and macOS.

**Comment by lwrage** [comment]
Are shape sizes in the GE given in pixels or diagram units that are mapped to pixels based on DPI?

**Comment by philip-alldredge** [comment]
Shapes are in diagram units which are effectively pixels. 

Text can be scaled by the OS, Low Level UI Toolkit(GTK/Win32), or SWT depending on settings, environment variables, and operating system and eclipse version.

**Comment by lwrage** [comment]
So the automatic diagram layout depends on the size of the labels, which makes sense.

Is the "correct" way to deal with a higher resolution display, then, to automatically decrease the font size (as it is done today) and have the user increase the diagram zoom level until the labels are readable? Is the diagram layout independent of the zoom level?

**Comment by philip-alldredge** [comment]
Yes. In general, shapes are resized to accommodate their labels.

Yes, the intended way of dealing with higher resolution display and/or custom text sizes at the OS level is to automatically decrease the font size so that the result of rendering the entire diagram is the same on all platforms. This isn't entirely possible because SWT doesn't support floating point font sizes.

Yes, it is intended that the user will need to adjust the zoom level until the diagram is readable.  Zoom level only affects the user's display of the diagram and does not affect the diagram itself.

**Comment by lwrage** [comment]
Physical measurements show that font scaling is automatically applied on Linux/2018-09/GTK>=3.22.0. If the GE font scaling is NOT applied, label and font sizes are as expected. With the GE font scaling the scaling factor (96/158 in my case) is applied twice, resulting in the tiny fonts.

**Comment by lwrage** [comment]
On macOS the reported DPI is not the physical DPI, e.g., a laptop with retina display (2560x 1600) reports a DPI of 72x72.
