### ISSUE TITLE
Abstract feature prototypes produce error in type declaration

### ISSUE THREAD

**Issue by dpgluch** [osate/osate2#1665]
## Summary

Prototypes for features produce an error in the original type declaration for an extension using prototype binding.
## Expected and Current Behavior

Get the error message " Couldn't resolve reference to Feature Classifier 'incoming' " in the example from the standard that is included here. The same message results for similar examples in the AADL course. For the course example included here there is the error message "Couldn't resolve reference to Feature Classifier 'comm' for the filtered out feature in the type declaration for filter but  the prototype binding seems to work in the extension declaration for filter2.
## Steps to Reproduce

1. Use examples below 
2. 
3.

```aadl
--This is an example from the standard:
package AbstractFeaturesStandard
public
abstract flowComponent
prototypes
dt: data;
incoming: in feature;
features
 insignal: in feature incoming;
 outsignal: out data port dt;
end flowComponent;
end AbstractFeaturesStandard;

-- This is a course example, where there is the error message "Couldn't resolve reference to Feature Classifier 'comm' for the filtered out feature in the type declaration for filter but  the prototype binding seems to work in the extension declaration for filter2.
thread filter
  prototypes
    comm: feature;
  features
    raw: in feature;
    filtered: out feature comm;
end filter;

data rdata
end rdata;

thread filter2
  extends filter
      (comm => out data port MyData)
      features
      raw: refined to in data port rdata;
end filter2;

data MyData
end MyData;
```

## Environment

* **OSATE Version**: Appears in OSATE 2.4.0 testing and in the OSATE 2.3.6  and OSATE 2.3.5 releases.
* **Operating System**:  Windows 7

**Comment by lwrage** [comment]
The AADL code is wrong. If you want to reference a feature prototype you need to use the `prototype` keyword, e.g., `insignal: in prototype incoming;`, see section 8.1 in the AADL 2.2 standard.
The change in the standard was introduced to syntactically distinguish 

- a declaration of an abstract feature referencing a classifier prototype `f: in feature classifierproto;` from
- an abstract feature declaration that references feature prototype `f: in prototype featureproto;`. 

The example in the standard needs to be updated to the new syntax.

**Comment by dpgluch** [comment]
Lutz,

Got it thanks.

Have a great holiday season.

Dave
