### ISSUE TITLE
Wrong feature group type validation

### ISSUE THREAD

**Issue by AaronGreenhouse** [osate/osate2#1671]
Suppose I have the feature groups `FG1`, `IG1`, and `FG2`:

```
	feature group FG1
		features
			f1: out event port;
	end FG1;
	
	feature group IG1
		features
			g1: in event port;
		inverse of FG1
	end IG1;
	
	feature group FG2 extends FG1
		features
			f1: refined to out event port;
			f2: out event port;
	end FG2;
```

Now I want to declare an inverse feature group of `FG2`

```
	feature group IG2 extends IG1
		features
			g2: in event port;
		inverse of FG2
	end IG2;
```

OSATE marks `IG2` with an error "Feature group features list count differs from that of its inverse".  In order to make OSATE happy, `IG2` needs to have 2 features, such as:

```
	feature group IG2 extends IG1
		features
			h: in event port;
			g2: in event port;
		inverse of FG2
	end IG2;
```

But this is complete nonsense because because now `IG2` really has three features.  The problem is caused by the refined feature in `FG2`.  It's being counted as a new feature by the verifier.

**Comment by joeseibel** [comment]
This isn't simply an issue of counting refined features. The validator currently looks at the owned features and the inverse's owned features. It assumes that diamond inheritance is happening, but fails when there is no diamond.

In the following case, IG2 does extend anything. The validator should accept this model, but doesn't.
```
package inverse_only
public
  feature group FG1
    features
      f1: out event port;
  end FG1;

  feature group FG2 extends FG1
    features
      f2: out event port;
  end FG2;

  feature group IG2
    features
      g1: in event port;
      g2: in event port;
    inverse of FG2
  end IG2;
end inverse_only;
```

In another example, IG2 extends a feature group which is not an inverse of FG1. The validator should also accept this model.
```
package not_diamond
public
  feature group FG1
    features
      f1: out event port;
  end FG1;

  feature group FG2 extends FG1
    features
      f2: out event port;
  end FG2;

  feature group FG3
    features
      f3: out event port;
  end FG3;

  feature group IG3
    features
      g3: in event port;
    inverse of FG3
  end IG3;

  feature group IG2 extends IG3
    features
      g1: in event port;
      g2: in event port;
    inverse of FG2
  end IG2;
end not_diamond;
```

**Comment by joeseibel** [comment]
Here are graphs showing each example's feature group type relationships. Solid lines represent `extends` and dashed lines represent `inverse of`.

Aaron's example in original post:
![first_example](https://user-images.githubusercontent.com/1824701/55978403-c185dc00-5c5d-11e9-9930-dd53f2fd4ac3.png)

inverse_only:
![inverse_only](https://user-images.githubusercontent.com/1824701/55978622-348f5280-5c5e-11e9-9d4b-ab443608a147.png)

not_diamond:
![not_diamond](https://user-images.githubusercontent.com/1824701/55978633-3a853380-5c5e-11e9-8394-9ca9eb553556.png)
