### ISSUE TITLE
Help text describing how to find Plugin Contributed Properties in OSATE

### ISSUE THREAD

**Issue by joeseibel** [osate/osate2#1686]
We should create a help text page describing the Plug-in Contributions node in the navigator. This request is coming from Alex. He would like to be able to point people to a help page when they ask him questions about how to see all of the available core and plug-in properties.

**Comment by lwrage** [comment]
This should be part of the AADL Navigator help.

**Comment by joeseibel** [comment]
Existing help in **OSATE Core Documentation** -> **Getting started** is outdated.
