### ISSUE TITLE
Too much underlining after unused classifier analysis

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#1704]
The warning for an unused classifier is associated with the classifier as a whole. As a result the complete classifier declaration is underlined in the text editor.
Only the name should be underlined.

**Comment by AaronGreenhouse** [comment]
Changed `FindUnusedClassifiersJob` to generate markers using the text bounds from `ILocationInFileProvider.getSignificantTextRegion` instead of `ILocationInFileProvider.getFullTextRegion`.
