### ISSUE TITLE
Classifier Information: Non-standard "link with editor" icon

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#1707]
The classifier view has a link with editor icon. For consistency with other uses in OSATE/Eclipse the tool text should just be "Link with Editor" and there should not be a separate icon that indicates no linking. Help text in getting started needs to be updated to match any change.

**Comment by AaronGreenhouse** [comment]
Fixed the tool tip text.

Found the "less fancy" icon in `org.eclipse.ui.workbench.texteditor` as `link_to_editor.png`

**Comment by AaronGreenhouse** [comment]
updated the user guide
