### ISSUE TITLE
Invoke interface without preference switches for Latency Analysis got lost

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2#1710]
When moving AnalysisResult returning methods from LatencyAnalysisService to FlowLatencyAnalysisSwitch methods just taking a component instance or end to end flow instance got lost. Used by plugin method registry.

**Comment by lwrage** [comment]
I assume this method uses the OSATE preference settings: Should such a method even exist? It may be better not to provide it at all because the result depends on something that is neither part of the model nor part of any ALISA specification.

**Comment by reteprelief** [comment]
It does not use the preference settings. It uses the default settings that are documented as part of the analysis.
I could leave the method out and instead have an entry in the method registry with those parameters supplied. Or we could argue that they should not even be set there and users have to list them on every verification activity call.
Furthermore, one of the parameters is SOM. The method passes in ‘null’. If I have to do this in the registry or verification activity I do not have a way of expressing ‘null’.
