### ISSUE TITLE
Memory leak in AADL workspace build

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate2#1726]
## Summary
Java heap usage grows with each OSATE workspace build and cannot be garbage collected, eventually resulting in an OutOfMemoryException. 

I created a minimum working example here: https://github.com/smithdtyler/osatememoryleaker

To run the example,
* import com.example.osate.leaker into an Eclipse RCP/RAP workspace with OSATE installed (or with the OSATE sources).  
* Run as -> Eclipse Application
* Import the Aircraft project (or just create it from new -> Example)
* Run JVisualVM, select the test workspace
* Click the button contributed by the leaker project

Watch:

![screen shot 2019-03-05 at 8 49 52 am](https://user-images.githubusercontent.com/8142684/53814169-c0f27b00-3f24-11e9-8e0d-b62a33709d72.png)

* **OSATE Version**: 2.4.0
* **Operating System**: Windows 7

**Comment by smithdtyler** [comment]
I have suspicions about the cause of this problem (but didn't want to pollute the top level issue description). Memory Analysis Tool (MAT) suggests a couple of likely problem spots:

_156 instances of "org.eclipse.xtext.util.OnChangeEvictingCache$CacheAdapter", loaded by "org.eclipse.xtext.util" occupy 190,713,528 (64.20%) bytes. These instances are referenced from one instance of "java.util.WeakHashMap$Entry[]", loaded by "<system class loader>"_

MAT reports this on a heap dump generated after approximately 156 calls to 

```
 ResourcesPlugin.getWorkspace().build(IncrementalProjectBuilder.FULL_BUILD,
	            new NullProgressMonitor());
```

**Comment by lwrage** [comment]
@smithdtyler There's a branch 1726_try_xtext_2.17 in osate/osate2 that includes xtext 2.17.
Note that you need a separate eclipse installation to use that branch. There's a setup file called osate2_1726.setup for that. I started OSATE from the dev environment and could build 1000 times without OOM. Memory usage reported by Linux still increased during the test. VisualVM won't start for me so I couldn't look at the heap in detail.
Please test and report back.

**Comment by lwrage** [comment]
It's an issue in AnnexParseUtil. It has been around for years but now is the first time it caused an OOM. AnnexParseUtil has a HashMap that caches parse results. uses a field of the value as the key!
