### ISSUE TITLE
Export Problem

### ISSUE THREAD

**Issue by RusherCircle** [osate/osate2#1736]
## Summary
We want to add new features based on osate. I configured the osate development environment according to the official osate documentation. But the exported product is incomplete and I need your help. I want to know the following questions:
1. Is osate based on the eclipse rcp project or other types of projects?
2. On your own computer, how to publish the project as a rich client or plugin？

* **OSATE Version**:
* **Operating System**: <!--  #Windows-- >

**Comment by lwrage** [comment]
We use maven/tycho for building OSATE. To add new features you need to configure the involved pom files accordingly. As this is not a bug but a question, please post your questions on the OSATE google group.
I can give you better answers there if you provide more details, e.g., how did you create your product, what is missing, did you add a plugin or feature?
