### ISSUE TITLE
Instantiator binds connection to the same index of a bus array

### ISSUE THREAD

**Issue by epydemia** [osate/osate2#1737]
## Summary

When using arrays of bus, instantiator does not behave correctly.

## Expected and Current Behavior
With reference to the AADL example  code pasted below:
When instantiated I expect to have the following situation:
conn1[1] (equivalent to d[1] <-> a[1].da) bound to bus b1[1]
conn1[2] (equivalent to d[2] <-> a[2].da) bound to bus b1[2]

The current behavior is the following
conn1[1] bound to bus b1[**2**]
conn1[2] bound to bus b1[2]

## Steps to Reproduce

1. Copy/Paste AADL code in OSATE
2. Instantiate the system implementation s.i
3. Check that in the instances (.aaxl2 file) that both the connections a[1].da --> d[1] and a[2] --> d[2] are bound to bus[2]. 

```aadl
package pkg
public
    abstract aType
        features
            da: requires data access;
    end aType;

    system s
    end s;

    system implementation s.i
        subcomponents
            d: data[2];
            a: abstract aType[2];
            b1: bus[2];
            
        connections
            conn1: data access d <-> a.da {connection_pattern => ((one_to_one));} ;

        properties
            Actual_Connection_Binding => (reference (b1[1])) applies to conn1[1];
            Actual_Connection_Binding => (reference (b1[2])) applies to conn1[2];
            

    end s.i;
end pkg;
```

## Environment

* **OSATE Version 2.4.0**:
* **Operating System**: Windows 10

**Comment by lwrage** [comment]
This is a limitation of the instantiator. Properties cannot be associated with individual connections in a connection array.

**Comment by lwrage** [comment]
It's actually not a limitation in the implementation but a bug in the validation (see #1746). The applies to clause should be rejected because AADL doesn't have connection arrays. Connection patterns define connection instances between elements of arrays but these connection instances don't form an array of connections (what would the indices be if it's not a one-to-one pattern?).
