### ISSUE TITLE
None statement in requires modes

### ISSUE THREAD

**Issue by joeseibel** [osate/osate2#1738]
The following does not parse, but is supported by the standard:

```aadl
package requires_modes_none
public
  system s1
    requires modes
      none;
  end s1;
end requires_modes_none;
```

**Comment by lwrage** [comment]
This is probably not worth fixing. Is this different from `modes: none;` except the additional keyword?

**Comment by joeseibel** [comment]
Exactly the same. The problem is in this grammar snippet:
```
((derivedModes?=RequiresModesKeywords
 ((ownedMode+=Mode)+))
|
 ('modes' ((ownedMode+=Mode | ownedModeTransition+=ModeTransition)+ | (noModes?='none' ';')))
)?
```

As you can see, `none;` is supported in `modes`, but not `requires modes`.

Unfortunately, this snippet appears in all of the separate component type grammar rules: `AbstractType`, `SystemType`, `ProcessType`, etc.

**Comment by joeseibel** [comment]
Listed as unsupported in https://github.com/osate/website/commit/5f7213692b530de043a766866932171bc50e70cf.
