### ISSUE TITLE
Update license for OSATE

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#1740]
Unified license text and source header are available.

**Comment by jjhugues** [comment]
As discussed with Lutz: there is no direct way to apply existing tools for this
- we have multiple languages used here, we need to adapt header box accordingly
- most tools use regexp matching, but we have existing copyright headers with various formats

If we were to do this, we would need first to remove all header boxes through scripting; then configure Eclipse to apply all header boxes.

**Comment by lwrage** [comment]
Also, some files contain a standard eclipse license header these **must** stay as they are because they are (maybe modified) copies of 3rd party code.

**Comment by jjhugues** [comment]
Yes, you are right. These should be considered separately. By "all header boxes", I meant OSATE specific ones

**Comment by jjhugues** [comment]
This extends to other places

here is an excerpt from the text from About OSATE -> OSATE icon
copyright years is wrong, and list of authors incomplete

"by Feiler, Greenhouse, Wrage, Delange

Version: 2.5.0-SNAPSHOT -- Build id: 2019-05-12

(C) Copyright Carnegie Mellon University, 2005–2015. 
"

if you click on plugin details, we have either "Software Engineering Institute" or "CMU/SEI" or "providerName" (for fault tree.design and generation).

**Comment by lwrage** [comment]
- [ ] Source code files
- [ ] Root files
- [ ] feature.xml - use a license feature?
- [ ] about
- [ ] uml/ecore files
