### ISSUE TITLE
Enable text wrapping for labels in diagram view

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate2#1759]
## Summary
Right now labels are always shown on a single line. That means "my_super_verbose_term" takes up a lot of horizontal space in my diagram and forces me to have _very_ wide diagrams. I'd like to be able to wrap the text by re-sizing the default label bounding box (similar to the text box behavior in powerpoint). 

Continuing my example, I'd like to be able to have the option to turn

```
my_super_verbose_term
```

into

```
my_super_
verbose_term
```

I'm using OSATE Version 2.4

**Comment by philip-alldredge** [comment]
Closing. This will not be implemented. Wrapping is achievable but there are cases where it will cause other labels to shift. The changes introduced as part of #1183 will change the behavior to truncate text but will not wrap. The new behavior is intended to avoid disruptive changes to layout when a name's length increases. Performing a full diagram layout will continue to size a component to the required length.
