### ISSUE TITLE
AADL text editor removes text from model without user deleting it

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2#1787]
OSATE 2.4.1

I was editing a file that contained AADL text with Syntax errors.
When I did a save it threw away some of the text with the syntax errors.

Example: I copied into a property set 
	val TempIncreaseRate : Isolette_Properties::Temperature_Change_Type = 1.0 Fdeg_Minute
	val TempDecreaseRate : Isolette_Properties::Temperature_Change_Type = 1.0 Fdeg_Minute
	
	val ThermoAccuracy : Isolette_Properties::Temperature_Type = 0.1 Fahrenheit
	
	val ThermostatFailureRate : real = 10.0e-5
	val ThermostatMonitorFailureRate : real = 10.0e-5
	val InfantExposureHazardRate : real = 10.0e-9
and then fixed the first statement to become a property constant. 
It then turned the end packname into end val (the next incorrect thing and threw away yhte rest of the inserted text.

This happened twice today.

**Comment by reteprelief** [comment]
It does not do it consistently so it is hard to reproduce.

**Comment by lwrage** [comment]
Looks like the auto edit functionality in our text editor. We need the exact sequence of user actions, e.g. where's the cursor, which key is pressed when, etc.

**Comment by reteprelief** [comment]
Ok. I'll try to track that.

**Comment by reteprelief** [comment]
It happens when I have text with syntax errors and allow the editor to fill in the with clause.
For example I insert multiple val statements and fix the first one to be a property constant. Since it refers to a property set and that was tagged with a warning about missing with clause I used the auto fill. The rest of the text was then thrown away.

**Comment by lwrage** [comment]
Do you mean "quick fix" (instead of "auto fill")? What exactly was the property set text before inserting and where did you insert?

**Comment by reteprelief** [comment]
Quickfix

**Comment by AaronGreenhouse** [comment]
Okay, I just saw this happen.

I have `test.aadl`

````
property set test is
	myConst : constant aadlinteger => 10;
	myType : type range of aadlinteger 1 .. 20;
	
	myProp : test::myType applies to (all);
end test;
```

I have `test2.aadl`

```
property set test2 is
	myProp2: test::myType applies to (all);
val ThermostatFailureRate : real = 10.0e-5
val ThermostatMonitorFailureRate : real = 10.0e-5
val InfantExposureHazardRate : real = 10.0e-9
	myProp2a: aadlinteger applies to (all);
	myProp2b: aadlinteger applies to (all);
	myProp2c: aadlinteger applies to (all);
	myProp2d: aadlinteger applies to (all);
end test2;
```

Obviously, `test2.aadl` has serious syntax errors.  But the first line has an error that the property set `test` is not listed in a `with` clause.  If I use the quickfix on the marker to "add test to the with clause", the file transforms for

```
property set test2 is
	with test;

	myProp2: test::myType applies to (all);
end val;
```

**Comment by AaronGreenhouse** [comment]
The `TextEdit` object created by Xtext while recording the changes made by the `ISemanticModification` during the quick fix is the source of the problem.  I think the root of the problem though is that the erroneous/unparsable text that follows the first property declaration is not stored anywhere in the model.  At least I cannot find it anywhere.

If this is the case, I'm not sure how to fix this.

**Comment by reteprelief** [comment]
Do not allow Quickfix action to take place if the text has parsing errors.

**Comment by AaronGreenhouse** [comment]
This is probably a general issue.  Probably all our quickfixes should check for syntactic correctness.

**Comment by AaronGreenhouse** [comment]
It's not trivial to find out if the source text that the model is associated with has syntax errors.  Basically you need to run the XText validator over the model and search for errors in the results.  Presumably this would have already been done at some point before getting to the QuickFix generator, but the results are not accessibile.  Even the general list of markers and Issues is not easily available.

Ideally, we would check in the 'fix' methods of `PropertiesQuickfixProvider` whether the resource the issue comes from has syntax errors and then not even add the fix to the acceptor.   But as there is no good way to find out the syntax error status of the resource, this cannot be done.

Yet another place where Xtext seems to have made things more difficult instead of easier.

**Comment by AaronGreenhouse** [comment]
Should probably just note on the User Manual that the quick fixes are dangerous to use if the file as syntax errors.
