### ISSUE TITLE
Compilation errors on fresh development environment

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2#1794]
- Created fresh development environment per instructions on osate.org.
- Received errors in org.osate.aadl.modelsupport and org.osate.analaysis.flow.tests projects.
- Those projects are configured to use Java 1.6 and 1.7 compliance levels but use functionality introduced in later versions of java.

## Environment
* **OSATE Version**: master
* **Operating System**: Windows

**Comment by yoogx** [comment]
Which JDK did you use? I could not compile OSATE on Windows 10 with JDK 1.21, but succeeded with JDK 1.8u212
