### ISSUE TITLE
Performance issue when editing AADL text

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2#1832]
## Summary
When editing a modestly-sized model (around 2500 semicolons), the text editor will hang for several seconds every few editing gestures. 

## Expected and Current Behavior
What I would expect is that I could do basic text typing and deleting without significant pauses every few key clicks.

## Steps to Reproduce
I SAFEd Lutz the model.  Open JCA Demo Design/packages/JCA_Demo_AH64D_Design.aadl, go anywhere in the file and then repeatedly enter a few line feeds, a few backspaces to delete, repeat a few times.  You will see pauses lasting a few seconds every few keystrokes.  Other gestures, such as selecting a text segment, can also be suspended for several seconds.

## Environment

* **OSATE Version**:  2.4.1
* **Operating System**: Windows 10

**Comment by lwrage** [comment]
Waiting for profiler license...

**Comment by lwrage** [comment]
Could be related to scope providers being called during linking.

**Comment by lwrage** [comment]
Found nothing obvious and easily fixable so far. 
According to an EclipseCon Europe presentation a prority for Xtext in 2020 is to increase performance. We will wait the next Xtext releases to see if the situation improves.

**Comment by lwrage** [comment]
Experimental fix merged. Disabled by default, see this [Google group post]( https://groups.google.com/forum/#!topic/osate/TUMAAbaEUWs) for instructions to enable it.

**Comment by lwrage** [comment]
Removed configuration option. The cache is now always turned on.
