### ISSUE TITLE
Documentation missing for semantic analysis of connection binding consistency

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2#1852]
We have two semantic analyses related to bindings. One checks whether binding constraints are met by binding actuals.
The second one checks connection binding consistency, i.e., it points out connections that do not have an explicit connection binding and analyses like bandwidth analysis derive it. It also points out when there is a logical connection between application components which are bound to hardware components, but the hardware components are not connected by a bus.

They are both useful, esp. the second one and should be documented in the online help.

**Comment by lwrage** [comment]
The binding constraint checker documentation was not included by accident.

@reteprelief Did we ever have documentation for the connection binding consistency check?

**Comment by lwrage** [comment]
@reteprelief I assume you are the only one who has an idea what exactly this analysis should do.
