### ISSUE TITLE
Wrong button size in 'Create End to End Flow Specification' wizard

### ISSUE THREAD

**Issue by edwardsandberg** [osate/osate2#1856]
## Summary

The buttons in the wizard are too small so the labels cut off the text. See screenshot [here.](https://i.imgur.com/82PmFs7.png) I saw this behavior on Ubuntu and OSX.

## Environment

* **OSATE Version**: 2.5.0
* **Operating System**: macOS 10.14 and Ubuntu 18.04

**Comment by lwrage** [comment]
@edwardsandberg The fonts in your screenshot look rather big. Do you use any font/display scaling or non-default font sizes?
