### ISSUE TITLE
Behavior Annex syntax highlighting

### ISSUE THREAD

**Issue by Etienne13** [osate/osate2#1864]
## Summary

This is a follow up on issue #891: when the BA name resolver finds errors in the BA subclause, the syntax highlighting is disabled.

## Expected and Current Behavior

Syntax highlighting is switched of in the following example because of an error in the BA subclause: timout should not be in the dispatch condition.

```aadl
 package test_891
public
	
process processA
end processA;

thread threadA
end threadA;
	
process implementation processA.impl
    subcomponents
      tA: thread threadA;
    annex behavior_specification {**
    states
    s0: initial complete final state;
    s1: state;
    transitions
    s0 -[ on dispatch timeout ]-> s1;
    **};
 end processA.impl;
	
end test_891;

```

## Steps to Reproduce

On the previous example, 
1. comment the transition: syntax highlighting appears
2. uncomment the transition: syntax highlighting disappears

From what I could see in the code, the problem comes the order in which syntax highlighter and name resolution are executed. Name resolution is executed first and in case of an error in the BA subclause the AnnexParserAgent class, lines 241 to 243 assigns the parsed annex object to null.
Then the syntax highlighter is called but when retrieving the parsed annex object, it is null and then the syntax highlighter does nothing.

I guess the syntax highlighter should be called before the parsed annex object is set to null.

## Environment

* **OSATE Version**: 2.5.0
* **Operating System**: Linux

**Comment by lwrage** [comment]
Closed via PR #1875
