### ISSUE TITLE
Making parameter connections in graphical editor fails

### ISSUE THREAD

**Issue by jjhudak** [osate/osate2#1865]
## Steps to Reproduce

1.
2.
3.

```aadl
Paste your model here
```

## Environment

* **OSATE Version**:
* **Operating System**:

**Comment by jjhudak** [comment]
Attached is example model illustrating the problem.  Open the diagram associated with thread implementation ComposeAircraftStatus.impl and attempt to make parameter connection among parameter ports.  
-Selecting source parameter and extending pointer shows dotted connection...then clicking on destination parameter results in dotted connection vanishing.  AADL text editor does not show any connections.
- Go to  thread implementation ComposeAircraftStatus.impl  and un-comment the three parameter
 connection statements.  Save and open the drawing-the connections are shown.

[GraphicalEditorParamaterConnectionBug.zip](https://github.com/osate/osate2/files/3347133/GraphicalEditorParamaterConnectionBug.zip)

**Comment by philip-alldredge** [comment]
When I try to make a connection the "no" symbol appears when hovering over the destination port. This indicates that validation is failing for some reason. Need to look into why.

**Comment by jjhudak** [comment]
Hi Phillip:
I forgot to mention I am using OSATE  2.5.0.  Interesting, as I don’t see the word ‘no’ appear in my version.  (unless it is so quick I just don’t notice it…)  will double check
John

**Comment by philip-alldredge** [comment]
It doesn't have the word no in it. It's a small icon that indicates that the connection isn't valid. If you click when it appears, then nothing happens. Unfortunately, this isn't a behavior we can customize at this time.

**Comment by philip-alldredge** [comment]
@lwrage @jjhudak an issue was found that can cause additional problems creating parameter connections. Fixed with #1902. It would be nice if this can make it in 2.5.1 since it is a relatively non invasive change.
