### ISSUE TITLE
Instantiation error, regression (NPE)

### ISSUE THREAD

**Issue by Etienne13** [osate/osate2#1867]
## Summary

The instantiation of the main system implementation in the example bellow worked with OSATE 2.4.0. With OSATE 2.5.0, iinstantiation fails. The execution trace I had suggest it is a NPE.

## Steps to Reproduce

From example bellow, try to instantiate main.impl

```aadl
package test_inst_NPE
public
	
	memory mem
  	end mem;

	data Integer
	end Integer;
	
	thread sender
  	features
    	p: out event port;
    end sender;
	
	system implementation main.impl
		subcomponents
			the_proc: process p.impl;
			the_mem: memory mem;
		properties
			Actual_Memory_Binding => (reference (the_mem)) applies to the_proc.c11;
	end main.impl;

	system main
	end main;

	process implementation p.impl
		subcomponents
			the_sender: thread sender;
			c11: data Integer;
		modes
			m1: initial mode;
			m2: mode;
			m1 -[the_sender.p]-> m2;
	end p.impl;

	process p
	end p;

end test_inst_NPE;
```

## Environment

* **OSATE Version**: 2.5.0
* **Operating System**: Linux

**Comment by lwrage** [comment]
This looks like a duplicate of #1839. Could you test with the nightly testing build, please?

**Comment by Etienne13** [comment]
Indeed, it is the same issue and it has been solved in the testing build. Sorry about the duplication.
