### ISSUE TITLE
Unable to install of OSATE 2.5.0 from update site categories

### ISSUE THREAD

**Issue by Etienne13** [osate/osate2#1868]
## Summary

I can easily install OSATE 2.4.0 from the update site category using the following URL:
OSATE - https://osate-build.sei.cmu.edu/download/osate/stable/2.4.0/updates/

Using either 
https://osate-build.sei.cmu.edu/download/osate/stable/

or
https://osate-build.sei.cmu.edu/download/osate/stable/2.5.0/updates/

or event the 250.tgz archive did not work, unless I removed the category grouping.

## Steps to Reproduce

Try to install osate 2.5.0 from the update site; the message that appears is "There are no categorized items". If I uncheck the box "Group Items by category" I find osate 2.5.0.

## Environment

* **OSATE Version**: 2.5.0
* **Operating System**: Linux

**Comment by lwrage** [comment]
The category.xml file was missing.
