### ISSUE TITLE
Call Resolute via a proper API

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#1889]
We have code that allows calls to Resolute in org.osate.assure.util.ResoluteInterface.java. As it requires Resolute classes for compilation it should be moved to the resolute feature so it would be installed together with Resolute. If resolute is not installed the code is not executed in OSATE. Project org.osate.smaccm.stubs should be deleted.
There are a couple of other classes which depend on Resolute classes.

**Comment by reteprelief** [comment]
Can you tell me where Collins is keeping SMACCM nowadays? Github tells me that the repository is archived.

**Comment by reteprelief** [comment]
I found the new location

**Comment by jjhugues** [comment]
As discussed with Lutz, we need to

- [ ] Evaluate eventual compatibility issues with latest Resolute plugins
- [ ] Provides a mechanism to register Resolute as an ALISA verification method instead of hardcoding it
- [ ] Define a strategy to have this full capability restored

**Comment by lwrage** [comment]
done
