### ISSUE TITLE
The ReqSpec documentation indicates URI as reference to external documents but does not provide syntax details

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2#1917]
The online help states:
DocReference ::= URI to an element in an external document

Currently the accepted  syntax of the document reference is (not quite a URI):
( folder ‘/’ )* file ‘.’ ext [ ‘#’ ID ('.' ID)* ]

**Comment by yoogx** [comment]
I ran into that as well

Actually, we could follow this recommendation to open directly some MS documents
https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee559408(v=office.14)

We could open a word document, but not reach directly to a specific section

Something similar exists for PDF, this time with capability to link to a specific page or a comment (not a section number)
https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdf_open_parameters.pdf

e.g. http://example.org/doc.pdf#page=1&comment=452fde0e-fd22-457c-84aa-2cf5bed5a349
