### ISSUE TITLE
Abstract features allow all component classifiers

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2#1926]
OSATE doesn't produce a warning or error when the classifier for an abstract feature is invalid.

8.1 (L5) of the standard restricts the unique component classifier of abstract features to be abstract, data, bus, virtual bus, subprogram, or subprogram group. 

For the graphical editor's sake, when this is fixed, it would be helpful to have an interface in the meta-model that can be used to identify valid classifier types rather than just a validation rule. The graphical editor currently uses FeatureClassifier to determine what classifiers the user can select.

```
package feature_test
	system test_system 
	
	end test_system;
	
	system test
		features
			test_new_feature2: in feature test_system;
	end test;
end feature_test;
```

**Comment by lwrage** [comment]
@philip-alldredge Could you explain a bit more what method you'd like to have, i.e., on which meta classes should it be available, what parameters (if any) should it have, and what should the return type be?

**Comment by philip-alldredge** [comment]
@lwrage 
- Would like a method on `AbstractFeature` for setting the classifier using a parameter that is restricted to valid classifier categories. AbstractFeature's `setAbstractFeatureClassifier` uses `FeatureClassifier` which allows passing invalid classifiers. I'd like to see that method modified or a new one added that provides a type safe interface. 
- Would like an `EClass`  available through the `Aadl2Package` which will be a supertype of all valid feature classifiers `EClass` for the abstract feature.
