### ISSUE TITLE
Subprogram access features should be allowed as flow specification ends

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2#1936]
The standard allows flow end point to be subprogram access.

- [x] Update meta-model, grammar, name resolution, validation, content assist, etc
- [x] Update graphical editor

This implements saeaadl/aadlv2.2#39

**Comment by lwrage** [comment]
10.1 (N2) only allows "a parameter of a subprogram access feature" but not subprogram access features as such, so OSATE seems to be correct.

**Comment by reteprelief** [comment]
issue#1937 deals with not processing subprogram access . parameter.

For this one I put in an errata for V2.2 (https://github.com/saeaadl/aadlv2.2/issues/39). 
The justification for also allowing just a reference to the subprogram access is that the subprogram may not have an in parameter but an out parameter (or vice versa). So in one direction we could not point to a parameter.

**Comment by lwrage** [comment]
I'd prefer not to make such changes in OSATE before they have been approved by the committee. Otherwise I'm all for it.

**Comment by reteprelief** [comment]
Ok.
John Hudak is doing some modeling with remote subprogram calls for his IDT work. That's what triggered the sequence of issues. Issues 1937 and 1941 are more relevant at this time.
