### ISSUE TITLE
Connection binding property with abstract component as reference value gives erroneous error message

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2#1946]
The reason is that abstract is not listed as category in acceptable reference values. 
In the applies to we do not have to explicitly list abstract while for specifying the reference type we do. This means, the target of binding properties can be abstract component without explicit specification.
[AbstractBinding.txt](https://github.com/osate/osate2/files/3501493/AbstractBinding.txt)
Allowing abstract is useful because we may have defined an abstract platform component.

The issue is relevant for connection, memory, and processor bindings. Function binding, which was introduced later, already has it correct.

**Comment by lwrage** [comment]
This is also a language issue that should be looked at by the standard committee.

**Comment by reteprelief** [comment]
I have entered an issue for V2.2 on this topic.
