### ISSUE TITLE
Unable to find update site for product OSATE 2.5.1

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2#1949]
## Summary
When I do a Help > Check for updates on the product OSATE 2.5.1, I get the message

No repository found at http://download.eclipse.org/technology/nebula/snapshot.

## Environment

* **OSATE Version**: product 2.5.1
* **Operating System**: Windows 10

**Comment by lwrage** [comment]
I cannot reproduce this with a fresh installation of OSATE 2.5.1. Checking for updates again, I get the error. Somehow this repo gets added when checking for updates. This doesn't look like an OSATE issue but some misconfiguration on the Eclipse side. You need to manually disable this repository in the preferences to get rid of the error message.
