### ISSUE TITLE
Can't install FACE to AADL translator when OSATE is started from the development environment

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2#1960]
## Summary
I followed the instructions at https://osate.org/setup-development.html.  That all seemed to work and successfully build OSATE.  I then Ran as an Eclipse application (after checking the "Support software installation in child process" box in the Run as ... configuration tab) and tried to install the FACE AADL translator.  I got the attached error

![FACE_AADL_missing_required_items](https://user-images.githubusercontent.com/3299870/63299185-cc4f1e00-c29a-11e9-8ba4-27063ff637a5.png)

## Expected and Current Behavior
I have been able to do this in the past with an earlier Eclipse development configuration.

## Steps to Reproduce
The above is how I got this (although I did not attempt to do it all from scratch a second time).

## Environment

* **OSATE Version**: osate git repository, I presume
* **Operating System**: Windows 10

**Comment by stevevestal** [comment]
I can also get an error by cloning the face2aadl repository and building that.  In this case, the error is on the pom.xml in the face2aadl project.

Could not find artifact org.eclipse.xtend:xtend-maven-plugin:jar:${xtext.version} in central (https://repo.maven.apache.org/maven2)	

Failure to find org.eclipse.xtend:xtend-maven-plugin:jar:${xtext.version} in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

**Comment by lwrage** [comment]
We can reproduce the installation issue. I suspect an underlying eclipse issue as the missing plugin is present. We won't try to fix this. The build issue should be discussed on the google group.
