### ISSUE TITLE
K ormore calculates failure probability wrong

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2#1976]
Use the test case issue1837 and change the failure probability of a node to 0.2.
For the case 2 ormore we should get .104: 
1 - Rs with Rs = 2*R*R - 2 * R*R*R with R = 1 - 0.2

However, I get a negative number (-0.41)

**Comment by reteprelief** [comment]
I used info from the following links for the formula above.
http://reliawiki.org/index.php/Fault_Tree_Diagrams_and_System_Analysis voting or gate 

http://reliawiki.org/index.php/RBDs_and_Analytical_System_Reliability k-out-of-n Parallel Configuration

**Comment by jjhugues** [comment]
Peter, agreed about the negative value
But the value you get if for 2 out of 3. 
2 or more out of 3 should be ( (2 out of 3) or (3 out of 3), hence 0.112 = 0.104 + 0.2^3

**Comment by jjhugues** [comment]
Oh, I may have interpreted that to strictly. @reteprelief can you please confirm?

**Comment by reteprelief** [comment]
Jerome,
the voting OR gate section of http://reliawiki.org/index.php/Fault_Tree_Diagrams_and_System_Analysis states that "In a Voting OR gate, the output event occurs if or more of the input events occur. "

http://reliawiki.org/index.php/RBDs_and_Analytical_System_Reliability is a little confusing as it calls the logic k-out-of-n and presents it as success logic. The text states "This type of configuration requires that at least components succeed out of the total parallel components for the system to succeed."
The fail logic would be 1 - Psuccess. I interpreted this as n-k ormore failures.

**Comment by reteprelief** [comment]
The formula for 2 ormore of 3 failure would be P1*P2*(1-P3) + P1*(1-P2)*P3 + (1-P1)*P2*P3 + P1*P2*P3 which leads to P1*P2 + P2*P3 + P1*P3 - 2*P1*P2*P3. For all components with the same P it would be 3*P*P - 2*P*P*P where P is the failure rate.

**Comment by reteprelief** [comment]
Just noticed the multiply symbol is interpreted as Italic on/off :-) Only one actually shows.

**Comment by reteprelief** [comment]
Jerome,
when I assign different values to the three Modules in you test case I still do not get the right numbers.
When they are the same the numbers are ok.
Example: 
in TMR_Archetype.impl EMV2 annex
properties
    emv2::OccurrenceDistribution => [ProbabilityValue => 0.1; ] applies to ^Module_1@Failure;
    emv2::OccurrenceDistribution => [ProbabilityValue => 0.2; ] applies to ^Module_2@Failure;
    emv2::OccurrenceDistribution => [ProbabilityValue => 0.3; ] applies to ^Module_3@Failure;

The result should be .098 but is .064
From http://reliawiki.org/index.php/RBDs_and_Analytical_System_Reliability:
Hardware drive example:
The reliability of HD #1 is 0.9, HD #2 is 0.88 and HD #3 is 0.85, all at the same mission time. (Failure rates 0.1, 0.12, 0.15). The result should be 0.0414 but is 0.03376

**Comment by jjhugues** [comment]
Translating old BASIC stuff remembered me I had to double check indexes. This should now be settled. Thanks for your reviews @reteprelief

**Comment by lwrage** [comment]
Fixed via PR #1982
