### ISSUE TITLE
Element hidden during rename

### ISSUE THREAD

**Issue by RyanMcilnay** [osate/osate2#1992]
## Summary
Shortcut to hide element is active during direct edit of element.
Entering an 'h' during rename causes the element to be hidden.

**Comment by philip-alldredge** [comment]
@lwrage just so your aware of it. This is the current stable version. If someone renames something in the diagram editor by clicking on the name and directly editing it and uses the `h` key then the diagram element is removed. The current workaround is to rename things using the `Rename...` of the context menu in the graphical editor or outline.
