### ISSUE TITLE
Instantiation of feature connection instances fails with nested components

### ISSUE THREAD

**Issue by Etienne13** [osate/osate2#1998]
## Summary

Instantiation of feature connections works when features are not connected to subcomponents but fails otherwise: no connection instance appears in the instance model.

## Steps to Reproduce

1. Instantiate system implementation s.impl below. The instance model contains one connection instance.
2. Uncomment the content of p1.impl
3. Re-instantiate system implementation s.impl. The instance model does not contain any connection instance. I think it should.

```aadl
package IssueFeatureConnection
public
	with Base_Types;
	
	feature group fg
		features
			d_f: out data port Base_Types::Integer;
			d_f2: out data port Base_Types::Integer;
	end fg;
	
	feature group fg_b inverse of fg
	end fg_b;
	
	process p1
		features
			fg_f: feature group fg;
	end p1;
	
	process implementation p1.impl
--		subcomponents
--			t1: thread t1;
--		connections
--			c: feature group t1.p -> fg_f;
	end p1.impl;
	
	thread t1
		features
			p: feature group fg;
	end t1;
	
	process p2
		features
			p: in data port Base_Types::Integer;
			p_b: feature group fg_b;
	end p2;
	
	process implementation p2.impl
		subcomponents
			t2: thread t2;
		connections
			c: port p -> t2.p_t;
	end p2.impl;
	
	thread t2
		features
			p_t: in data port Base_Types::Integer;
	end t2;
	
	
	system s
	end s;
	
	system implementation s.impl
		subcomponents
			p1: process p1.impl;
			p2: process p2.impl;
		connections
			c1: feature p1.fg_f.d_f -> p2.p;
	end s.impl;
	
	
end IssueFeatureConnection;
```

## Environment

* **OSATE Version**: 2.5.2
* **Operating System**: Linux, ubuntu 18.04 with Java 12

**Comment by lwrage** [comment]
Resolution of reach down fails for connection up the hierarchy where both ends have the same feature group type. In this case there's nothing to resolve.
Need to check if this is handled correctly for going down the hierarchy.
