### ISSUE TITLE
Infinite loop when building workspace

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2#2007]
## Summary
Very occasionally, when I do a Project clean all projects, OSATE 2.5.2 product gets in an infinite loop.  The status bar just bounces back-and-forth on progress, e.g., in this instance 14% then 16% then 14% then 16% ...  Task manager shows high CPU usage.

## Steps to Reproduce
Unfortunately, this is sporadic.  Stopping and restarting usually results in a successful build.  There were build errors, in this case associated with a missing project dependence, though I'm not sure that had anything to do with it.

## Environment

* **OSATE Version**: 2.5.2 product
* **Operating System**: Windows 10
[jstackdump.txt](https://github.com/osate/osate2/files/3681893/jstackdump.txt)

**Comment by lwrage** [comment]
Do you have cyclic project dependencies?

**Comment by lwrage** [comment]
I was able to reproduce the issue and debug.
It turns out that the job that updates project references when a project is renamed is kicked off even though there was no renamed project. This repeatedly interrupts the build job, which then reschdules itself. This goes on ad infinitum.
