### ISSUE TITLE
Support displaying properties on flow implementations and end to end flow specifications.

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2#2019]
Properties for flow implementations and end to end flow specifications are currently not displayed. This is due to them not being part of the diagram. Only highlighting is supported.

Need to consider how support can be added and whether such flows should be better integrated with the overall diagram.

Standard 10.2.(8) page 196:
> Flow specifications can have component implementation specific and mode specific property values. The respective property associations can be declared in the properties subclause of the component implementation or as property association with the flow implementation declaration.

It appears that properties on flow implementations should be treated as if it was assigned to flow specification.  Is that the correct interpretation? If so, how are they deconflicted in cases there are multiple flow implementations with the same properties. Does it make sense to display it that way in the diagram or to treat them as part of the flow implementation.

**Comment by stevevestal** [comment]
The first idea that pops into my head is, as an end to end flow implementation is selected and deselected for high-lighting (a nice feature, BTW), associated properties appear and disappear.

**Comment by philip-alldredge** [comment]
@stevevestal where would you like them displayed? At the containing implementation? One one(random?) connection which is part of the implementation? In a legend of some sort?

**Comment by philip-alldredge** [comment]
Thanks for the background information. I'm not sure what would be the easiest solution at the moment. Anytime we are adding things to the diagram there is a chance it would mess up the diagram layout unless it is treated as an overlay of some sort. An overlay has the potential to obscure things. An overlay may not be that bad though as long as it was move-able.  Not sure how practical such an implementation would be. 

Unfortunately, I don't see anything that would be a quick fix.
