### ISSUE TITLE
Adding property associations can result in diagrams being changed

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2#2020]
Which properties are displayed in a diagram is set for the entire diagram. Because of this, adding a property to an element displayed in the diagram will result in the diagram changing the next time it is opened. This can cause the diagram to not look as intended because of diagram element sizes changing.

Need to consider whether this is appropriate behavior. We recently reworked the diagram configuration system to reduce cases where diagrams are updated automatically to reflect new model elements. This is very similar.

@lwrage what are your thoughts? In the past you seemed less happy with things being automatically added to the diagram.

**Comment by lwrage** [comment]
@philip-alldredge I'll need to think about this.

**Comment by philip-alldredge** [comment]
@lwrage what were your thoughts?

**Comment by lwrage** [comment]
Is it possible to display property values in a separate layer such that they are not part of the layout?

**Comment by philip-alldredge** [comment]
Unless I'm misunderstanding you, no, that is not feasible without rethinking how property values are visualized. In many cases the property values are text labels that are contained inside the element for the shape to which they apply.  They are inherently considered part of the shape and must be considered when determining the size of the shape.

![example](https://user-images.githubusercontent.com/1376364/71987569-1908a680-31f4-11ea-9712-d7906cfdafd2.png)

**Comment by philip-alldredge** [comment]
If we want to change the behavior, I'd suggest the approach below.
- Adjust the behavior of the graphical editor so that the AADL Properties listed in the Configure Diagram settings would only be automatically added on initial element creation. This is similar to how other diagram elements behave now.
- If an AADL property exists in the 
- Add the ability to add/remove single property associations to the diagram. This would be an added capability but necessary if all property associations aren't being shown.
- Add menu option to add all configured properties. This would add any that match the criteria in the diagram configuration but are not currently in the diagram.

As far as I recall, there shouldn't be any layout issues associated with automatically removing a property value that no longer has an association but that could be done either way.

Even with these changes could be broken in a few cases. For example if a property value is represented as connections(references) then adding another reference would add another connection. There might be other cases if the representation of the property value swapped from being a connection to being a label. However, the cases I can imagine that occurring are such that I don't think it would cause any real problems because the diagram is already being changed.

I haven't given much thought about how easily implementable this approach is but it would make the behavior more consistent with the other changes. Although, there are times when I miss the old behavior and I'm sure i would miss property values being automatically added in some cases.

**Comment by lwrage** [comment]
Is there a possibility to display properties in a textbox that has scrollbars if needed? Then for automatic layout the textbox size would adapt, but otherwise if would show a scrollbar if the text doesn't fit any longer.

**Comment by philip-alldredge** [comment]
Not at this time. But we aren't really slotted to resolve this in the immediate future anyways. 

Once we are using GEF5/JavaFX, I believe it would be feasible. The labels at the top could be grouped together and placed in some sort of container. The scrollbar or the box could be shown only when it's cutoff(depending on how appealing it looks).
