### ISSUE TITLE
Aggregate data port support in graphical editor

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2#2023]
Aggregate data ports and connections are not fully supported in the graphical editor. 

@reteprelief and @lwrage I do not recall seeing any mention of visualizing aggregate data ports in the standard. Recommendations?

**Comment by lwrage** [comment]
I don't think this is necessary. Aggregate data ports are not fully supported in model instantiation and analysis, either.

**Comment by philip-alldredge** [comment]
In that case, I'm going to close the issue.
