### ISSUE TITLE
Outline view loses its context menu

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#2050]
## Summary

Every once in a while the context menu in the outline view disappears. It appears again after a restart.

## Steps to Reproduce

1. Close all editors
2. Open an AADL file, say P.aadl. -> The context menu in the outline view works.
3. Open another AADL file, say Q.aadl, leaving P.aadl open. -> The context menu in the outline view works.
4. Switch to the editor tab for P.aadl. -> The context menu does not appear any more.

## Workaround

Close and reopen the text editor. Only the outline view for editor opened last will work.

## Environment

* **OSATE Version**: 2.6.0
* **Operating System**: all

**Comment by jjhugues** [comment]
I have a workspace that also exhibits this weird behavior
Closing the outline and reopening it restores it

**Comment by lwrage** [comment]
This is not an OSATE issue as it happens for Xtend files, too.

**Comment by joeseibel** [comment]
See https://github.com/eclipse/xtext-eclipse/issues/1252

**Comment by lwrage** [comment]
Looks like it will be fixed as soon as we upgrade to the next eclipse version.
