### ISSUE TITLE
Add dialog proposing to save files prior to instantiation

### ISSUE THREAD

**Issue by jjhugues** [osate/osate2#2083]
Currently, one can instantiate a system with unsaved files. This can create inconsistent results from the user perspective.

A check could be added to look for open files, and a pop-up be raised to propose saving all files prior to process.

**Comment by AaronGreenhouse** [comment]
UI Spy: **ALT+SHIFT+F1**

**Comment by AaronGreenhouse** [comment]
Two main problems for this:
1. How to find out what files are open and need to be saved.
2. How to use the same dialog box that Eclipse already uses (for example when you have open files and select a launch configuration.)

**Comment by AaronGreenhouse** [comment]
According to the UI Spy the dialog in question is `org.eclipse.debug.internal.ui.launchConfigurations.SaveScopeResourcesHandler.ScopedResourcesSelectionDialog`.

Seems to be part of a large operation.

Technically we should rely on this because it's in an "internal" package?

**Comment by AaronGreenhouse** [comment]
This method or a clone of it is handy (from `SaveScopeResourcesHandler`):

```
	/**
	 *
	 * Builds the list of editors that apply to this build that need to be saved
	 *
	 * @param projects the projects involved in this build, used to scope the searching process
	 * @return the list of dirty editors for this launch to save, never null
	 */
	protected IResource[] getScopedDirtyResources(IProject[] projects) {
		HashSet<IResource> dirtyres = new HashSet<>();
		IWorkbenchWindow[] windows = PlatformUI.getWorkbench().getWorkbenchWindows();
		for (IWorkbenchWindow window : windows) {
			IWorkbenchPage[] pages = window.getPages();
			for (IWorkbenchPage page : pages) {
				IEditorPart[] eparts = page.getDirtyEditors();
				for (IEditorPart epart : eparts) {
					IResource resource = epart.getEditorInput().getAdapter(IResource.class);
					if (resource != null) {
						for (IProject project : projects) {
							if (project.equals(resource.getProject())) {
								dirtyres.add(resource);
							}
						}
					}
				}
			}
		}
		return dirtyres.toArray(new IResource[dirtyres.size()]);
	}
```

**Comment by lwrage** [comment]
There's `org.eclipse.ui.ide.IDE.saveAllEditors(IResource[], boolean)`, which is API.

**Comment by AaronGreenhouse** [comment]
Yes, was just about to add that here!

**Comment by AaronGreenhouse** [comment]
Not clear we can directly resume their dialog box... Annoying.

**Comment by AaronGreenhouse** [comment]
Also see: `org.eclipse.ui.internal.SaveablesList.MyListSelectionDialog`

**Comment by lwrage** [comment]
Why can't we reuse the existing dialog?

**Comment by AaronGreenhouse** [comment]
It's a non-`public` inner class of `SaveScopeResourcesHandler`.  

But looking at `org.eclipse.ui.internal.SaveablesList.MyListSelectionDialog`, which is basically the same thing, we just need to make a very simple subclass of `ListSelectionDialog`

So this easy.

**Comment by AaronGreenhouse** [comment]
The List selection dialog is given 
* a new `ArrayContentProvider()` for the content provider
* a new `WorkbenchPartLabelProvider()` for the label provider

**Comment by AaronGreenhouse** [comment]
![Screen Shot 2020-03-10 at 4.22.11 PM.png](https://images.zenhubusercontent.com/5cc7040c07a4ab52d27abe58/927df5a6-ab16-446b-8432-4e6120ff9366)

I don't think we need the "always save..." option at the bottom

**Comment by lwrage** [comment]
`org.eclipse.ui.ide.IDE.saveAllEditors(IResource[], boolean)` doesn't have that checkbox. It's used, for example, when closing a project that has files open in an editor.
I would prefer not to create our own dialog.

**Comment by AaronGreenhouse** [comment]
@lwrage Good catch.  I didn't see this one.  Looks like what we need.

**Comment by AaronGreenhouse** [comment]
Updated the instantantiate and reinstantiate handlers to use `org.eclipse.ui.ide.IDE.saveAllEditors()`

**Comment by lwrage** [comment]
Closed via PR merge, the description in the PR was wrong so it was not closed automatically.
