### ISSUE TITLE
Unexpected XText version change when installing updates from 2.6.0-vfinal update site

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate2#2097]
I downloaded and installed the Windows x86_64 OSATE 2.6.0-vfinal release of OSATE from osate.org. 

I extracted it and checked Help -> About -> Plugins and saw xtext 2.19 installed.

<img width="732" alt="Screen Shot 2019-12-05 at 1 40 47 PM" src="https://user-images.githubusercontent.com/8142684/70267831-da02b380-1764-11ea-8b62-4b64b2512550.png">
 

I did help -> install new software -> and added an update site: https://osate-build.sei.cmu.edu/download/osate/stable/2.6.0-vfinal/updates/

I selected the available features and clicked "install"

After the install completed and I restarted OSATE, Help -> About -> Plugins reported most xtext plugins were now at version 2.20.

This breaks some of our tools, because we have dependencies on xtext 2.19. 

<img width="691" alt="Screen Shot 2019-12-05 at 1 34 39 PM" src="https://user-images.githubusercontent.com/8142684/70267751-ad4e9c00-1764-11ea-981d-bb6de9197e45.png">

**Comment by lwrage** [comment]
This should not have happened. Please export the list of all update sites in your installation and attach it here. Did you add any other update site?

Maybe we lost the Xtext version dependency that should have prevented 2.20 from installing.  

BTW, What you did was completely unnecessary. The update site is for installing into an existing Eclipse installation. There are no OSATE updates available there.

**Comment by lwrage** [comment]
I cannot reproduce this. I tried with a fresh 2.6.0 installation, and it installs the source features but does not update Xtext.

**Comment by smithdtyler** [comment]
For reference: 

```
shasum -a 256 osate2-2.6.0-vfinal-win32.win32.x86_64.zip

cac1146f9c7bf967174264bddb831433f35568d12308b40d8ca7c0979654327e  osate2-2.6.0-vfinal-win32.win32.x86_64.zip
```

**Comment by smithdtyler** [comment]
> BTW, What you did was completely unnecessary. The update site is for installing into an existing Eclipse installation. There are no OSATE updates available there.

We noticed this behavior because installation of _other_ OSATE plugins seems to also prompt the xtext version change. We tried to install a plugin and it failed because of the xtext version. To rule out the _other_ plugin as an issue, I tried installing OSATE 2.6.0 from the update site to see if simply installing anything from an update site caused xtext to update. 

> I cannot reproduce this. I tried with a fresh 2.6.0 installation, and it installs the source features but does not update Xtext.

I just tried again (using the .zip file with checksum noted above) and saw the same behavior. More screenshots below:

![Screen Shot 2019-12-06 at 8 30 06 AM](https://user-images.githubusercontent.com/8142684/70330747-c9554a80-1803-11ea-9c10-7c5272095be9.png)

![Screen Shot 2019-12-06 at 8 28 49 AM](https://user-images.githubusercontent.com/8142684/70330739-c4909680-1803-11ea-8cf5-74b014064864.png)

![Screen Shot 2019-12-06 at 8 29 53 AM](https://user-images.githubusercontent.com/8142684/70330783-db36ed80-1803-11ea-91b6-09bc2eef43c6.png)

![Screen Shot 2019-12-06 at 8 33 31 AM](https://user-images.githubusercontent.com/8142684/70330762-d2deb280-1803-11ea-8980-e9c8ff8650fd.png)

**Comment by smithdtyler** [comment]
It's probably not related, but here is my .log file from this morning's test. I unzipped OSATE, launched it, added the OSATE 2.6.0 update site, and installed the plugins shown in the screenshots above. 

```
!SESSION 2019-12-06 08:24:53.140 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_111
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.equinox.p2.core 4 0 2019-12-06 08:30:10.606
!MESSAGE Provisioning exception
!STACK 1
org.eclipse.equinox.p2.core.ProvisionException: No repository found at http://download.eclipse.org/elk/updates/releases.
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:396)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:661)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:110)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:105)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.doLoad(LoadMetadataRepositoryJob.java:126)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.runModal(LoadMetadataRepositoryJob.java:110)
	at org.eclipse.equinox.internal.p2.ui.sdk.PreloadingRepositoryHandler$1.runModal(PreloadingRepositoryHandler.java:84)
	at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:190)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
!SUBENTRY 1 org.eclipse.equinox.p2.metadata.repository 4 1000 2019-12-06 08:30:10.606
!MESSAGE No repository found at http://download.eclipse.org/elk/updates/releases.

!ENTRY org.eclipse.equinox.p2.core 4 0 2019-12-06 08:30:11.168
!MESSAGE Provisioning exception
!STACK 1
org.eclipse.equinox.p2.core.ProvisionException: No repository found at http://download.eclipse.org/technology/nebula/snapshot.
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:396)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:700)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:110)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:105)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.doLoad(LoadMetadataRepositoryJob.java:126)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.runModal(LoadMetadataRepositoryJob.java:110)
	at org.eclipse.equinox.internal.p2.ui.sdk.PreloadingRepositoryHandler$1.runModal(PreloadingRepositoryHandler.java:84)
	at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:190)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
!SUBENTRY 1 org.eclipse.equinox.p2.metadata.repository 4 1000 2019-12-06 08:30:11.168
!MESSAGE No repository found at http://download.eclipse.org/technology/nebula/snapshot.

```

**Comment by smithdtyler** [comment]
> This should not have happened. Please export the list of all update sites in your installation and attach it here. 

Here's the list from the initial OSATE install with no changes made:
[initial_list.xml.txt](https://github.com/osate/osate2/files/3932781/initial_list.xml.txt)

With the OSATE update site added:
[with_osate_update.xml.txt](https://github.com/osate/osate2/files/3932784/with_osate_update.xml.txt)

and after installing the OSATE source plugins:
[post_update.xml.txt](https://github.com/osate/osate2/files/3932785/post_update.xml.txt)


> Did you add any other update site?
No.

**Comment by lwrage** [comment]
This is strange: I fired up a fresh Win10 VM, and there I can reproduce the issue. 

On Linux it does not update Xtext. Check for updates doesn't, either. It refuses to install any Xtext 2.20 feature when I try.

FYI: The update site you added (.../2.6.0-vfinal/updates/) is the same as the one already in the list (.../2.6.0/updates/), 2.6.0 is a symlink to 2.6.0-vfinal. I didn't add the second one, so that's not the reason for the funny behavior.

**Comment by smithdtyler** [comment]
@lwrage Do you need any further information from me?

**Comment by lwrage** [comment]
I'll try to add explicit dependencies on other Xtext 2.19 plugins to prevent the upgrade.

**Comment by AaronGreenhouse** [comment]
I tried this on OS X with a fresh OSATE2 download.
* XText starts as 2.19
* I update, which should just install the ALISA and OSATE source code
* after update, XText is at 2.20

**So this is broken on OS X.**
