### ISSUE TITLE
Deletion of device in graphical editor does not remove corresponding connection in text

### ISSUE THREAD

**Issue by jjhudak** [osate/osate2#2117]
## Summary
In an implementations, a system with a FG is connected to a device with a corresponding FG.  In the graphical editor, if you delete the device, the associated connection vanishes. (seems reasonable).   If you then go to the corresponding textual representation, the device subcomponent is gone, but the connection still is present (should be deleted?), and is marked with an error (as it should).  In this example, I cannot think of any reason why the connection statement still should remain in the connections subclause.  

## Expected and Current Behavior
Expected behavior: in the graphical view of a implementation, if the device with a single FG connection to another system is removed, along with its connection, I expect the connection in the textual representation to be removed as well.

Current behavior:  The connection remains in the connections subclause in the textual representation and is marked with an error.

## Steps to Reproduce

1. Use the attached model, in the implementation  mycar.cruisecontrol, delete the throttle actuator in the graphical editor and observe results in graphical and textual representations
2.
3.

```aadl
Paste your model here
```

## Environment

* **OSATE Version**: 2.6.0, 2.6.1
* **Operating System**: 
Windows 10
[session3_solution.zip](https://github.com/osate/osate2/files/3975137/session3_solution.zip)

**Comment by philip-alldredge** [comment]
This is a subset of #1206. The general solution is a difficult problem.  However, a limited capability could be implemented without too much difficulty if it was limited to only deleting elements in the same component implementation that contains the subcomponent. That is, if it did not look at extended implementations at this time. 

Thoughts?

**Comment by jjhudak** [comment]
Hi Phil:
I didn’t realize it was part of another issue.  Yes, I didn’t consider the related issues in deleting.  Maybe the simple case as you pointed out would be reasonable.  Would have to balance out the amount of work and all the places the rework would need to be done.
Perhaps just putting up a info box that the user will have to manually remove all related connections?  Yes, they would eventually discover it but at least  they were warned.

John
