### ISSUE TITLE
Graphical editor: management of bend points

### ISSUE THREAD

**Issue by jjhugues** [osate/osate2#2118]
I had to reorganize a complex AADL model generated from diagrams. The management of bendpoints could be improved to reduce user intervention.

For the moment, if a bendpoint exists, and you move the component, this bendpoint is kept even though it is no longer relevant. This forces the user to remove it (right-click -> remove bendpoint) for each connection. 

One could imagine two solutions:
- when a component is moved, suppresses all bendpoints (either always, configurable, or by shift + mouse)
- have an option in right-click -> Layout to remove all bendpoints for all connections, not just the selected one

**Comment by lwrage** [comment]
We should look at how other editors handle bend points, e.g., UML/SysML tools, Visio, etc.

**Comment by jjhugues** [comment]
I did a quick test with the Papyrus UML editor. When creating bendpoints (in use case diagram), bendpoints are kept, and the articulation is done on the bendpoint that is closest to the element you move. You can change bendpoints on selected links only.

**Comment by philip-alldredge** [comment]
The recommended approach to remove all bendpoints is to:
- Edit->Select All Connections
- Edit->Layout->Removal Bendpoints

I'm not convinced we need a special menu option to combine those two operations.

MagicDraw appears to removes in the cases I've experimented with. Visio preserves bendpoints under some cases and removes them under others. However, both of those software have better individual layout capabilities.  While I'm sure our bendpoint handling can be improved we'll need to decide when a bendpoint isn't relevant and exactly how it should be improved.

**Comment by jjhugues** [comment]
Ok, I missed the Select All Connections entry in the top menu.
right-click are far more convenient, I almost never use the top ones

I agree we may not want a combined menu, but having a way to select all elements of a specific category would be great, not just connections. I had similar concerns when reorganizing buses or devices

**Comment by philip-alldredge** [comment]
I opened a new issue(#2129) for the selection capabilities. We'll still need more detail about the desired behavior of the bendpoint management.

**Comment by philip-alldredge** [comment]
@jjhugues what would you like to see for bendpoint management besides selection options being added to the context menu?

**Comment by jjhugues** [comment]
On second thought, I am not sure: 
- do I want a right click then select all bend points, or 
- right click then remove all bend points. 

I cannot think of a use case where I would want to select all then move them or do another action.

I agree management of bendpoints is a complex issue. In my case, I just want a quick way to remove them when arranging large models

**Comment by philip-alldredge** [comment]
I don't believe bendpoints are currently selectable, they are juts movable and removeable. Connections on the other hand are selectable. There are other cases where a user may want to select all connections. Those cases include things like adjusting the style or any of the model editing operations. In the latter case, it is more unlikely unless the diagram is fairly limited.

**Comment by yoogx** [comment]
You are right; I meant
- select all connections
- or a short cut "remove all endpoints"

both address my need

**Comment by philip-alldredge** [comment]
I'd rather not add a combination shortcut unless it become apparent it is really worth it is. #2129 will cover adding the selection commands to the context menu. I suggest closing this issue.

**Comment by jjhugues** [comment]
Thanks @philip-alldredge I am OK with your suggested resolution
