### ISSUE TITLE
Visualization and editing of behavior annex state automata

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2#2130]
Visualization and editing of behavior annex state automata, except for expressions.

The high-level state machine will be displayed and edited in the OSATE graphical editor alongside other AADL model elements. Behavior specifications will be represented by a behavior diagram element. Like other model elements, the user will be able to set the “in modes” clause and other attributes using the Eclipse Properties view. States, transitions, and variables will be represented inside the behavior specification element.

The label for behavior specification diagram element will be based on the containing classifier and the mode(s) to which they apply. If the diagram element is contained within a classifier, the label may be shortened to avoid redundancy. 

A Behavior Specification diagram type will be introduced which will show states and transitions by default. 

Additionally, adjust setup to stop hiding the `org.osate.ge.ba` project and start including it with OSATE.

Ensure copy and pasting works for BA elements.

**Comment by philip-alldredge** [comment]
Will need to adjust setup to stop hiding the BA project.

**Comment by RyanMcilnay** [comment]
Create tests for BA work.

**Comment by philip-alldredge** [comment]
Blocked on #2550
