### ISSUE TITLE
findPropertyDefinition returns null if no property associated to the context

### ISSUE THREAD

**Issue by Etienne13** [osate/osate2#2151]
## Summary

I am trying to retrieve a property definition in the source code of the behavior annex. The snippet below illustrates how I am proceeding: I get a PropertiesLinkingService object and call findPropertyDefinition on it. This method takes as parameter a context (_baParentContainer in my code). I noticed that the result of findPropertyDefinition if there is no property "Dispatch_Protocol" associated to the context (_baParentContainer). I don't understand why. I guess the context is used to speed up the search; but I don't understand why it is strictly necessary (the property definition exists irrespective of any context). So I guess the method could even work without context (null, or defining another method in that case).

```java
PackageSection[] contextsTab =AadlBaVisitors.getBaPackageSections(_ba);
PropertiesLinkingService pls = Aadl2Visitors.getPropertiesLinkingService(contextsTab[0]) ;
    
Property dispatchProtocolProperty = pls.findPropertyDefinition(_baParentContainer, "Dispatch_Protocol");
    
```

## Steps to Reproduce
1. On the following AADL model, call findPropertyDefinition on the object representing threadA; the result should not be null; 
2. comment the property association and call again findPropertyDefinition. 
3. The result is null.

I would expect the result not to be null, irrespective of the existence of the property association.

```aadl
thread threadA
properties
  Dispatch_Protocol => Periodic;
end threadA;
```

## Environment

* **OSATE Version**: 2.6.0 (I expect the problem to persist on 2.6.1) 
* **Operating System**: Linux

**Comment by lwrage** [comment]
The linking service is for name resolution _only_. To find an arbitrary property definition use Aadl2GlobalScopeUtil.get().

**Comment by Etienne13** [comment]
Thanks for the reply, I will close the issue as I am no longer able to reproduce it.
