### ISSUE TITLE
StartUp task errors setting up an OSATE dev env

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2#2153]
## Summary
When setting up an OSATE development environment as described on the osate.org page, things seemed to go as expected until the newly installed eclipse ran its startup task.  

## Expected and Current Behavior
Following the instructions several months ago for 2019-03 worked.  When the startup task executes this time, I get the following errors.

![osate2-2019-12-startup-errors](https://user-images.githubusercontent.com/3299870/71924045-d5f6f680-3153-11ea-98a1-bf7c3d848111.png)

## Steps to Reproduce
Tried it twice, recurred for me.

```aadl
Paste your model here
```

## Environment

* **OSATE Version**: github
* **Operating System**: Windows 10

**Comment by lwrage** [comment]
The interesting part of the error message is cut off. I think the google group is a better place to discuss this.

**Comment by schwerdf** [comment]
I am also unable to provision an environment this way, although I get a different error message that I think is a legitimate problem with the setup file. Will discuss further on the Google Group.

**Comment by lwrage** [comment]
@stevevestal You can cut and paste the error message from the Window in the screenshot. You can also get to the error message after you've dismissed the dialog: Start the newly installed eclipse: Main menu -> Navigate -> Open setup log

**Comment by stevevestal** [comment]
Attached is from Navigate -> Open setup log.  Note this is different than the error messages that show up in the Eclipse updater failed tasks popup (what I posted earlier was the end of that error log, other than a "took 6 seconds, there were failed tasks" sort of P.S.   August also posted to the google group per your request, pointing at a specific issue.

[setuplog.txt](https://github.com/osate/osate2/files/4035857/setuplog.txt)

**Comment by lwrage** [comment]
Your git clone is not the latest version (your sources still require Xtext <= 2.17, but we've updated to 2.20). You need to switch to the master branch and pull before installing the latest dev environment.
