### ISSUE TITLE
Abstract component and on dispatch

### ISSUE THREAD

**Issue by jjhugues** [osate/osate2#2154]
The BA parser has now and extension of D.3 (L5) that forbids abstract components to have on dispatch.

abstract components cannot contain a dispatch condition in any of its transitions: they cannot be dispatched (extention of Behavior Annex D.3.(L5) legality rule).	

This seems too strong, abstract components exist for the purpose of specification, they will be later refined. 

This rules forbids the construction of abstract functions that would later be refined as an entity that can be dispatched. Can you turn this into a warning or info ?

**Comment by Etienne13** [comment]
This is correct, I did not think of the special case of abstract components where the dispatch_protocol property cannot be applied but dispatch condition may be specified. I will add a special case in the code for abstract components.
