### ISSUE TITLE
Value constant not accepted for behavior annex

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2#2184]
## Summary
When trying to specify an initial value constant for a behavior annex variable, a parse error occurs. This could be the result of having a bad version of the standard. Using a draft from 2017-02. The grammar on page 9 shows that a value_constant can be specified.

## Steps to Reproduce
1. Paste model 
2. Receive error `unterminated behavior variable (missing ending ';')`

```aadl
package ba_test
public
	with Base_Types;

	process top
		features
			o1: out data port Base_Types::Integer_32;

		annex behavior_specification {**
          variables
            tmp :  Base_Types::Integer_32 :=1;
          states
            a : initial final state;
          transitions
            t : a -[]-> a {
              o1 := tmp
            };
        **};
	end top;

	
end ba_test;
```

## Environment

* **OSATE Version**: Nightly
* **Operating System**: Windows

**Comment by Etienne13** [comment]
In the latest version of the BA, we opted for the usage of the Initial_Value property associated to variables as a way to model the initialization of these variables. The rationale was to follow the same initialization method as the core standard.

The initialization of your tmp variable should be modeled as follows:
```aadl
tmp :  Base_Types::Integer_32 {Initial_Value => 1;};
```

The behavior plugin does not support these property associations yet, but I have started working on it.

**Comment by philip-alldredge** [comment]
Sounds like the draft document I was looking at is out of date and I need an updated version of the BA spec. Is "AS5506/3" the correct document? 

When you say "support" these property associations, what do you mean? I thought the BA plugin just provided parsing support/meta-model support.

**Comment by Etienne13** [comment]
By "support" I meant that the parser, and meta-model for property associated to behavior variables is not implemented yet (wip).

**Comment by philip-alldredge** [comment]
Okay. Thanks for the clarification! I'm going to close this since the syntax I was using was invalid.

**Comment by philip-alldredge** [comment]
@Etienne13 
I'm reopening this because the latest version of AS5506/3 published by the SAE include the value constant as part of the grammar. Issued on 2017-08 "Superseding AS5506/2 Annex D".

**Comment by Etienne13** [comment]
Yes, I double checked and you are right. Both ways of initialization (using a direct affectation := or using property associations) should be supported.
