### ISSUE TITLE
In GE, action to change the orientation of buses

### ISSUE THREAD

**Issue by Etienne13** [osate/osate2#2198]
## Summary

Setting the layout of the graphical representation of a hardware platform is not very easy, and I think buses components are mostly responsible for this. I was wondering if it would be feasible to have an action to change the orientation of buses components to rotate them by 90°. I think it would help the organization of a HW platform description.

Then, it would be handy to be able to connect buses using any part of their edges. Same for the bindings. 

## Environment

* **OSATE Version**: irrelevant
* **Operating System**: irrelevant

**Comment by philip-alldredge** [comment]
@Etienne13 can you clarify the problem. Are you also intending the label of the bus to be vertical. Can you provide a mockup example of how you think it should look? I don't understand the meaning of your last paragraph.

**Comment by Etienne13** [comment]
@philip-alldredge I am not intending the label to be vertical. You will find a mockup example with this [link](https://mem4csd.telecom-paristech.fr/blog/wp-content/uploads/2020/02/issue_bus_orientation.pdf). My last paragraph is illustrated in the mockup example using the red lines: it would be handy to be able to use any edge of a bus component as a connection (or binding) endpoint.

**Comment by philip-alldredge** [comment]
Thanks for the example.

**Comment by philip-alldredge** [comment]
Fixed by dbefc8b. The editor now adjusts the graphic for buses depending on width and height.
