### ISSUE TITLE
Behavior annex plugin throws an error if subprogram call action refers to something else than a subprogram classifier

### ISSUE THREAD

**Issue by Etienne13** [osate/osate2#2200]
## Summary

If a BA subclause contains a subprogram call action that refers to something else than a subprogram classifier (e.g. subprogram access or subprogram subcomponent) the plugin throws an error.

## Steps to Reproduce

1. create a package with the following example
2. the BA plugin throws an error on subrogram access call

```aadl
package BA_example1
public

data number
end number;

subprogram mul
features
  x : in parameter number;
  y : in parameter number;
  z : out parameter number;
end mul;

subprogram cube
features
  x : in parameter number;
  y : out parameter number;
  mul : requires subprogram access mul;
end cube;
subprogram implementation cube.ba
annex behavior_specification {**
  variables tmp : number;
  states s : initial final state;
  transitions t : s -[]-> s { mul!(x,x,tmp); mul!(tmp,x,y) };
**};
end cube.ba;

end BA_example1;
```

## Environment

* **OSATE Version**: 2.7.0
* **Operating System**: Linux

**Comment by lwrage** [comment]
@Etienne13 Please remember to assign an estimate of 1 and a milestone to issues that will be fixed. Otherwise the issue will not show up in the release notes. See https://github.com/osate/osate2/wiki/OSATE-Development-Guidelines#managing-issues
