### ISSUE TITLE
Bus load analysis of feature groups is broken

### ISSUE THREAD

**Issue by AaronGreenhouse** [osate/osate2#2246]
The method `BusLoadAnalysis.calcBandwidthKBytesps()` is currently:

```
	private double calcBandwidthKBytesps(ConnectionInstanceEnd cie) {
		double res = 0;

		// TODO-LW add other cases
		if (cie instanceof FeatureInstance) {
			FeatureInstance fi = (FeatureInstance) cie;
			double datasize = GetProperties.getSourceDataSize(fi, GetProperties.getKBUnitLiteral(fi));
			double srcRate = GetProperties.getOutgoingMessageRatePerSecond(fi);
			res = datasize * srcRate;
			EList<FeatureInstance> fil = fi.getFeatureInstances();
			if (fil.size() > 0) {
				double subres = 0;
				for (Iterator<FeatureInstance> it = fil.iterator(); it.hasNext();) {
					FeatureInstance sfi = it.next();
					subres = subres + calcBandwidthKBytesps(sfi);
				}
				if (subres > res) {
					if (res > 0) {
						errManager.warningSummary(fi, null, "Bandwidth of feature group ports " + subres
								+ " exceeds feature group bandwidth " + res);
					}
					res = subres;
				}
			}
		}
		return res;
	}
```

It intends to check feature groups, that is, that the bandwidth requirements of the features in the feature group are less than the bandwidth budget of the feature group itself.  This is, of course, a good idea.  But it. doesn't work (anymore) as written because

* The input to the method `cie` comes the endpoint of a connection instance.  The instance model no longer creates connection instances between feature groups.  (All the feature group connections are made individually).
* This, the attempt to get the children of the feature instance `fi.getFeatureInstances()` will always return an empty list.

Fixing this is pretty easy, I think.  For each connection bound to the bus, check to see if the source of the connection is contained in another feature.  This way analysis can recursively build up a list of feature group features that "make use of the bus."  Then basically the same code as above can be used to check them.

**Comment by AaronGreenhouse** [comment]
Some example models I made originally for Issue #2205 but then I realized this was broken.

```
package PortGroupConnections
public
	with SEI;

	data D1
		properties
			Data_Size => 8 Bytes;
	end D1;

	data D2
		properties
			Data_Size => 16 Bytes;
	end D2;

	data D3
		properties
			Data_Size => 24 Bytes;
	end D3;

	feature group FG
		features
			out1: out data port D1;
			in2: in data port D2;
			out3: out data port D3;
	end FG;

	system S1
		features
			out1: feature group FG;
	end S1;

	system S2
		features
			in1: feature group inverse of FG;
	end S2;

	bus B
	end B;

	system Top
	end Top;

	system implementation Top.simple
		subcomponents
			sub1: system S1;
			sub2: system S2;
			theBus: bus B;
		connections
			conn1: feature group sub1.out1 <-> sub2.in1 {
				Actual_Connection_Binding => (reference (theBus));
			};
	end Top.simple;

	system implementation Top.good_fg extends Top.simple
		properties
			Communication_Properties::Output_Rate => [Value_Range => 800.0 .. 1000.0; Rate_Unit => PerSecond;] applies to sub1.out1;
			Data_Size => 64 Bytes applies to sub1.out1;
			
			Communication_Properties::Output_Rate => [Value_Range => 800.0 .. 1000.0; Rate_Unit => PerSecond;] applies to sub1.out1.out1;
			Communication_Properties::Output_Rate => [Value_Range => 800.0 .. 1000.0; Rate_Unit => PerSecond;] applies to sub2.in1.in2; -- really an output port
			Communication_Properties::Output_Rate => [Value_Range => 800.0 .. 1000.0; Rate_Unit => PerSecond;] applies to sub1.out1.out3;
			
			SEI::BandWidthCapacity => 80.0 kbytesps applies to theBus;	
			
			SEI::BandWidthBudget => 72.0 kbytesps applies to conn1;
	end Top.good_fg;

	system implementation Top.bad_fg extends Top.simple
		properties
			Communication_Properties::Output_Rate => [Value_Range => 400.0 .. 500.0; Rate_Unit => PerSecond;] applies to sub1.out1;
			Data_Size => 64 Bytes applies to sub1.out1;
			
			Communication_Properties::Output_Rate => [Value_Range => 800.0 .. 1000.0; Rate_Unit => PerSecond;] applies to sub1.out1.out1;
			Communication_Properties::Output_Rate => [Value_Range => 800.0 .. 1000.0; Rate_Unit => PerSecond;] applies to sub2.in1.in2; -- really an output port
			Communication_Properties::Output_Rate => [Value_Range => 800.0 .. 1000.0; Rate_Unit => PerSecond;] applies to sub1.out1.out3;
			
			SEI::BandWidthCapacity => 80.0 kbytesps applies to theBus;	
			
			SEI::BandWidthBudget => 72.0 kbytesps applies to conn1;
	end Top.bad_fg;
end PortGroupConnections;
```

**Comment by AaronGreenhouse** [comment]
The declarative model will only have the feature group connection, not the individual connections.  So the feature group can get the `BandwidthBudget` and `BandwidthCapacity` property associations.  There isn't any way to reference the individual connections.  _So when the model is instantiated the individual connections will get the `BandwidthBudget` and `BandwidthCapacity` property associations of the feature group connection._  That is not very useful.

The nesting of feature groups can be determined by looking at the nesting of the `FeatureInstances`.  (Although the `ConnectionInstance` objects reference the source `Connection` object in the declarative model, this cannot be used to get the hierarchy because it fails to capture nested feature groups.)

The data size and messaging rates come from the property associations of the source features, however, so that is helpful.  It is straightforward to compute the actual usage of the connections that come from a single virtual connection and sum them up as the actual data usage of the feature group.  The the actual for the feature group can be compared against the budget and capacity as normal.  

* The different features in the feature group can have different messaging rates, and that is okay.

The question is what to do with the messaging rate and data size of the feature group itself.

* I'm not sure if it makes sense to compute the data volume of the feature group from them, because what does it mean for the feature group to have a messaging rate if the sub features have their own, possibly different, messaging rates?
* Is the `Data_Size` of the feature group treated as overhead?  Does this make sense, it really depends on what a feature group is supposed to represent.
* If the feature group is really just meant to be a "bundle of wires" then neither the data size or messaging rate properties have any meaning for the feature group.

**Comment by AaronGreenhouse** [comment]
The semantics of feature groups is not defined enough to know what do with this right now.

Marking as "stuck"

**Comment by rajtuli** [comment]
Is the Bus load analysis the only analysis that is broken due to this issue?

**Comment by lwrage** [comment]
@rajtuli The bus load analysis as such works. It's one specific piece of functionality where it is not clear if that ever made sense.

**Comment by lwrage** [comment]
@AaronGreenhouse It sounds like this feature group analysis functionality simply doesn't make sense. Is so this issue should be closed as invalid.

**Comment by rajtuli** [comment]
@AaronGreenhouse and @lwrage In my experience if a system implementation which uses feature groups is setup for bus load analysis then flow analysis fails if the flow to be analyzed runs through connections bound to a bus.  If should be noted that the flows also run through feature groups.  Is this expected behavior?

**Comment by lwrage** [comment]
@rajtuli Do you have a model with feature groups where the bus load analysis fails? Can you share it, please?

**Comment by AaronGreenhouse** [comment]
Per @lwrage, closed as invalid.
