### ISSUE TITLE
Is the function of transforming aadl file into xml file removed in this version?

### ISSUE THREAD

**Issue by Peterlcc** [osate/osate2#2254]
Hi ! I am a new user of osate . I used the function transforming aadl file into xml file when I at the aadl file editor view in osate 2.2.2. But I cant't find it in the lastest version 2.7. Is it removed ? Or is it in somewhere else that I couldn't notice?
Thanks.

**Comment by lwrage** [comment]
Could you post questions on the [OSATE google group](https://groups.google.com/forum/#!forum/osate), please?

**Comment by Peterlcc** [comment]
ok.I will do it. Thank you.
