### ISSUE TITLE
Errors with Nested Dot Notation for Flow Path Declaration

### ISSUE THREAD

**Issue by jslu1** [osate/osate2#2285]
When creating an internal flow path between an in-port and an out-port, it is not easy to create a nested dot notation in the flow path declaration that describe that this particular flow path includes only the specific data element typed to the interfaces. 

For example, if input_1 is typed to a data implementation (data X.impl) that has 2 subcomponents (data A.impl and data B) and the implementation of data A.impl includes subcomponents (data C and data D), it is currently not possible to create a nested dot notation to represent a flow path that is only specific to data C to represent it going from input_1 to output_1. The code shown below would be the ideal nested dot notation that should annotated in the type declaration of the component but it currently results in an error.

  Flows
               F1: flow path input_1.X.A.C -> output_1.Y;

Will there be a future tool update to facilitate  nested dot notations for the data structures and its sub-structures? The issue was seen when using OSATE v2.6.

## Environment

* **OSATE Version 2.6v:
* **Operating System Windows 10

**Comment by lwrage** [comment]
This is not supported in OSATE because it does not conform to the AADL version 2.2 standard: Flows can reference features, features contained in a feature group, and subprogram parameters, but they cannot reference elements of data types associated with ports.

**Comment by lwrage** [comment]
@jslu1 I have moved this issue to saeaadl/aadlv2.2#54 because a fix in OSATE would first require a change in the AADL language standard. This will require discussion of your use case, i.e., what exactly do you want to model and analyze, are there alternative ways to model this in AADL, etc. Could you comment on saeaadl/aadlv2.2#54 to add more detail, please?
