### ISSUE TITLE
Configuration flag for deactivating an annex

### ISSUE THREAD

**Issue by jjhugues** [osate/osate2#2288]
In some cases, one may want to deactivate an annex from the regular parsing phase. For instance apply analyses that do not depend on them

One may imagine a configuration parameter for that, that would simply deactivate the corresponding registered parser

An open question could be: how about analysis? We could have a warning if EMV2 is disabled when trying to run FHA or FTA

**Comment by lwrage** [comment]
We need the following:

- [ ] A preference dialog that lists the installed annexes with a checkbox that allows deselecting the annex
- [ ] Modification of parser, validator, etc, to check is processing of some annex is disabled.

**Comment by asazonova** [comment]
@jjhugues did you intend the flag to be project specific (project A can use annex B,  but project C can NOT use annex B) or is the flag should be applied to all projects (if annex B flag is unchecked, then it can NOT be used in project A and project C)

**Comment by asazonova** [comment]
@AaronGreenhouse Do you know if it is possible to access preferences from stand alone java programs (jar files) that you can run from command line to process aadl file?

**Comment by yoogx** [comment]
The flag should be project specific

**Comment by AaronGreenhouse** [comment]
@asazonova I don't know for sure, but I think it would probably work.  The core Workspace preference and project properties data structures are not UI-specific.

**Comment by asazonova** [comment]
@lwrage 

for workspace preference, we use final IPreferenceStore store = OsateCorePlugin.getDefault().getPreferenceStore();
for project preference, we use 
                 final IScopeContext context = new ProjectScope(project);
		final Preferences prefs = context.getNode(PREFS_QUALIFIER);

This Preferences prefs object does not have a method to set a default value. However, unlike workspace preference, for projects we set the preference explicitly with 	prefs.putBoolean(annexExtensionId.toLowerCase(), value); - see implementation below:
   	@Override
		public void putBoolean(String key, boolean value) {
			wrapped.putBoolean(key, value);
		}

this one does not have a check if oldValue == newValue, which is good for us, it will just set the preference to false without ignoring it

Conclusion,
- workspace preference has a default of true and only resets the value if it has changed. Here, setting a default value guarantees that we can turn off the preference and it will be set to false. 
- project preference does not have a default value, but it is capable of setting a value to false on first try. So if the value is set, then we can use that, if the value is not set then we use 'true' as a preference is turned on (this also assumes that the flag 'use project preferences' is turned on for this specific project)

**Comment by asazonova** [comment]
Add screenshots and explanation how to use this feature to Advanced section of help (org.osate.help)

**Comment by lwrage** [comment]
- [ ] Help text is not visible in product
- [ ] Screenshots for help need to be updated
