### ISSUE TITLE
'in modes' clause on behavior specification stopped working in OSATE 2.7.1.

### ISSUE THREAD

**Issue by schwerdf** [osate/osate2#2295]
The following specification works in OSATE 2.7.0 and earlier, but causes a syntax error in OSATE 2.7.1. The specific error is on the behavior specification's `in modes` clause: "Couldn't resolve reference to mode 'normal'." But when autocomplete is activated inside the parentheses of the `in modes` clause, both the component's modes show up in the list.

```
  thread group threadB
    features
      output: out event data port message_pm;
  	modes
  		normal: initial mode;
  		fast: mode;
  end threadB;
  
  thread group implementation threadB.impl
      annex behavior_specification {**
         states
            s0: initial state;
            s1: final state;
        transitions
            s0 -[ ]-> s1 {output:=1};
    **} in modes (normal);
```

**Comment by lwrage** [comment]
This used to work, but only by accident.

**Comment by smithdtyler** [comment]
So behavioral cannot be modal?

**Comment by smithdtyler** [comment]
> This used to work, but only by accident.

I am confused - is the AADL source in the example legal? We are relying on this functionality.

**Comment by Etienne13** [comment]
@lwrage I confirm that the Behavior Annex document specifically mentions that BA subclauses can be mode specific using the **in modes** statement.

**Comment by lwrage** [comment]
There's no question that it is a bug (note the "bug" label at this issue). There's already a PR that fixes the name resolution. 

Any annex subclause can be modal as specified in the AADL 2.2 standard section 4.8.
