### ISSUE TITLE
Annex instantiation invoked before properties and connection patterns

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2#2299]
The annex instantitators are called before the core instance models adds connection instances from patterns and before it adds property instances.

The EMV2 instantiation works with connection instances and depends on binding properties to be present in the instance model.

**Comment by lwrage** [comment]
@reteprelief Could you fix that in connection with the EMV2 instantiation? This doesn't have to be a separate pull request, I think.

**Comment by reteprelief** [comment]
ok. Will do.
