### ISSUE TITLE
Bus Load analysis throws exception if the "instances/reports" directory is missing

### ISSUE THREAD

**Issue by AaronGreenhouse** [osate/osate2#2307]
The bus load analysis throws an exception before running if the `reports` directory under the `instances` directory is missing.  Ironically, this happens when trying to create the necessary output files and directories before analysis begins.  Clearly I missed a level of directories.

**Workaround:** Before analysis make sure the `reports` directory exists.  You can create it in the workspace by hand if needed.

**Comment by AaronGreenhouse** [comment]
Fixed `NewAbstractAaxlHandler` to _recursively_ ensure that all the directories above the output directory exist.  Only partially did this before.

**Comment by lwrage** [comment]
Could you also fix the "excepting starting" messages, please? I don't think we need a separate issue for that. IIRC, "excepting" occurs in two files.

**Comment by AaronGreenhouse** [comment]
@lwrage Oops, yeah, meant to do that.

Fixed in `NewAbstractAaxlHandler` and `InstantiationHandler`.  Original misspelling was in `InstantiationHandler`, was copy-and-pasted into the other class.
