### ISSUE TITLE
Remove support for Graphiti file format

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2#2324]
OSATE 2.2.3(August 21, 2017) introduced a new file format. In the release notes we included a message

> The file format used by previous versions of the Graphical Editor has been deprecated. Support for opening such diagrams will be removed in a subsequent release. When opening a legacy diagram, the user will be prompted to convert the file. The new file format is more compact and contains more reliable linkages with the AADL model.

I think it is time to remove support from OSATE. If removed, the user will need to open in the last version of OSATE that supports the file format and convert there. At that point, the user will be able to open the file in the current OSATE.

**Comment by philip-alldredge** [comment]
@lwrage do you have any objection to this change? For clarity: this only affects diagrams produced Before OSATE 2.2.3. These diagrams are those created back when the graphical editor named everything based on a UUID and the editor was much more limited. The editor will retain compatibility with diagrams created since then.

**Comment by lwrage** [comment]
@stevevestal @smithdtyler @schwerdf What's Adventium's opinion on this? 
I noticed today that the JCA Demo model version I have still has old-style diagrams in it.

**Comment by stevevestal** [comment]
I haven't looked at that model since last year, when we were using it to do some testing on our ARINC 653 tools.  I don't recall if we did any diagram configuration to make things prettier than you get if you just regenerate them (which gives pretty decent automated layout).  My opinion is, I ought to see if that model runs on the latest OSATE.  But that's just an opinion, not an action :-)

**Comment by philip-alldredge** [comment]
Keep in mind that at the time of that release the graphical editor didn't support styles and selecting exactly what appears int he diagram. I believe the only customization of the diagram is the layout and setting the number of nesting depth for the diagram. 

If/when we remove support, the user will still be able to upgrade the diagrams by opening an older version to convert the format.

**Comment by lwrage** [comment]
I think it is important that after the removal no old "official" example models get distributed that contain diagrams which can no longer be opened in the latest OSATE version. So somebody needs to update the diagrams in the JCA model, etc.
Should get feedback from Sholom and Alex.

**Comment by philip-alldredge** [comment]
Which model are you referring to?  Is it available somewhere?
