### ISSUE TITLE
Fan-in for data ports should be forbidden

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#2356]
## Summary

OSATE should forbid fan-in for data ports.

## Expected and Current Behavior

When multiple connections exist (in a mode) to a data port this should be an error. This should be check on the declarative model as much as possible as well as on the instance model.

## Steps to Reproduce

1. Open the model below in the AADL text editor.
2. There should be an error on the data port.

```aadl
package P2
public
	
	system S
	end S;
	
	system implementation S.i
		subcomponents
			a1: abstract A;
			a2: abstract A;
			b: abstract B;
		connections
			c1: port a1.aout -> b.bin;
			c2: feature a2.aout -> b.bin;
	end S.i;
	
	abstract A
		features
			aout: out data port;
	end A;
	
	abstract B
		features
			bin: in data port;
	end B;

end P2;
```

## Environment

* **OSATE Version**: 2.7.1
* **Operating System**: all

**Comment by AaronGreenhouse** [comment]
Rule (L11) in Section 9.2:

> A data port cannot be the destination of more than one semantic port connection unless each semantic port connection is contained in a different mode.

**Comment by AaronGreenhouse** [comment]
Checking in the instance model is much easier, so I will start with that.

Checking in the declarative model is not perfect, but we should catch the obvious cases like the above.

As stated above, this should be an _error_.

**Comment by AaronGreenhouse** [comment]
Added instance model checking to `ValidateConnectionSwitch`.  Added unit tests.

Added declarative model checking to `Aadl2JavaValidator` as the new method `checkInDataPortConnections(ComponentImplementation)`.

Still needs unit tests.

**Comment by AaronGreenhouse** [comment]
Added new unit tests and updated the existing ones affected by the new errors

**Comment by AaronGreenhouse** [comment]
After discussion with @lwrage we decided to remove the declarative model checking because it can be misleading and confusing.
