### ISSUE TITLE
Internal error occurred during instantiation

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2#2363]
I know it's weird, but I'll provide this example anyway since it did generate an internal error popup when HasSink.Example is instantiated.

## Expected and Current Behavior
Instantiation Handler (hidden) is encountering a problem.

## Steps to Reproduce
Instantiate HasSink.Example

```aadl
package TestSink
public
	
	system HasSink
		features
			inp: in data port;
		flows
			inSink: flow sink inp;
	end HasSink;
	
	system implementation HasSink.Example
		subcomponents
			recurse: system HasSink;
		connections
			con: port inp -> recurse.inp;
		flows
			inSink: flow sink inp -> con -> recurse.inSink;
	end HasSink.Example;
	
end TestSink;
```

## Environment

* **OSATE Version**: 2.7.1 product
* **Operating System**: Windows 10

**Comment by lwrage** [comment]
I cannot reproduce the error in the development version, instantiation works as expected.. Could you test with the nightly build, please?

**Comment by lwrage** [comment]
I tried with the latest nightly build (20200611) and it works for me, too.

Do you get anything in the error log?

**Comment by stevevestal** [comment]
I restarted and did a clean/build and the problem went away.  It is common to see things happen that disappear with a clean/build.  Close as unable to reproduce, I guess.
