### ISSUE TITLE
Fix renaming of refined elements

### ISSUE THREAD

**Issue by RyanMcilnay** [osate/osate2#2394]
## Summary
While using the graphical editor, performing a rename on an element that is refined causes the refined element to be removed/unrefined and leaves an error artifact on the text editor.

## Expected and Current Behavior

The expected behavior is that the refined element and the element being refined will reflect the rename action performed.

The current behavior is that the refined element being renamed is removed/unrefined and leaves an error artifact on the text editor.

## Steps to Reproduce

Using the provided model:
1. Copy the model into an AADL Package
2. Open the sys.impl2 diagram
3. Select the refined subcomponent "ss" in  System Implementation "sys.impl2" on the diagram
4. Perform a rename operation

```aadl
package test
public

system sys
end sys;

system implementation sys.impl1
subcomponents
	ss: system;
end sys.impl1;

system implementation sys.impl2 extends sys.impl1
subcomponents
	ss: refined to system;
end sys.impl2;

end test;
```

## Environment

* **OSATE Version**: 2.8.0
* **Operating System**: Windows 10

**Comment by philip-alldredge** [comment]
@RyanMcilnay can you clarify this. Is this a graphical editor bug or a core issue bug?
