### ISSUE TITLE
Qualified names removed from EMV2 type aliases

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2#2398]
## Summary
When making a change to the error model library via the EMF model,  the produced error annex library source may remove qualified names to point incorrect error types.

## Expected and Current Behavior
When making a change to the error model, references should serialize to the correct qualified names.

## Steps to Reproduce
1. Create model with the following packages.
2. Make a change to the `typelib` error model library.
3. `t1_alias` no longer reference the correct `t1`.

```aadl
package typelib
public
	annex EMV2 {**
		error types
			t1: type;
			t2: type;
			t1_alias renames type other_typelib::t1;
			t2_alias renames type t2;
			t3_alias renames type other_typelib::t3;
		end types;
	**};
end typelib; 
```

```aadl
package other_typelib
public
		annex EMV2 {**
		error types
			t1 : type;
			t3 : type;
		end types;		
		**} ;
end other_typelib;
```

## Example Resulting Model 
```aadl
package typelib
public
	annex EMV2 {**
		error types
			t1: type;
			t2: type;
			t1_alias renames type t1; -- THIS IS INCORRECT
			t2_alias renames type t2;
			t3_alias renames type other_typelib::t3;
			new_error_type: type;
		end types;
	**};
end typelib; 
```

**Comment by lwrage** [comment]
Bug in the emv2 cross-reference serializer. It always prefers local names if present even if the reference is to another package.
