### ISSUE TITLE
Copying and pasting of elements that have a source and/or destination cause exceptions

### ISSUE THREAD

**Issue by RyanMcilnay** [osate/osate2#2411]
## Summary

Copying elements from one container component to another such as mode transitions, connections, and flow specifications cause exceptions.

## Expected and Current Behavior

Elements should be pasted into the destination component, instead, an exception is being thrown.

## Steps to Reproduce

While viewing the package diagram:
1. Right click connection "c" in sys.impl
2. Select "Copy" from the context menu
3. Right click on sc.impl
4. Select "Paste" from the context menu

```aadl
package CPBug
public
	system sys
	end sys;

	system implementation sys.impl
	subcomponents
		ss1: system sc.impl;
		ss2: system sc.impl;
	connections
		c: port ss2.o -> ss1.i;
end sys.impl;

	system sc
	features
		i: in data port;
		o: out data port;
end sc;

	system implementation sc.impl
end sc.impl;
end CPBug;
```

## Environment

* **OSATE Version**: 2.8.0
* **Operating System**:  Windows 10

**Comment by philip-alldredge** [comment]
This is caused by the recent refactoring. During it, we tightened the rules and checks regarding relative references. This is often being caused by transient or model errors.
