### ISSUE TITLE
Which class has the function of transforming aadl to xml？

### ISSUE THREAD

**Issue by Peterlcc** [osate/osate2#2432]
## Summary

Hi , I am a new osate user. First of all, I want to thanks for your work on osate which is a good tool for aadl. I find the good function of transforming aadl to xml in it. I hope I can call some api or copy the special class file into my little program. But I failed to debug osate2.2.2 source code and the latest code in local , so I want to ask this question that where I can find the core code of transforming aadl to xml.

I'm looking forward to your reply.

**Comment by lwrage** [comment]
Don't use the issue tracker to ask questions, please.
