### ISSUE TITLE
Error Type cyclical extensions cause the text editor to lock up

### ISSUE THREAD

**Issue by RyanMcilnay** [osate/osate2#2455]
## Summary

Cyclic extensions between error types cause the text editor to lock up occasionally.

Information that might help find the issue:
I have noticed in the small example model that is pasted below, if both the Cyclic_Error_Types::a and ErrorLibrary::AboveRange properties of the in propagation are removed, the editor does not lock up.

## Steps to Reproduce

1. Copy and paste the model below into the text editor.
2. Uncomment line 19: b: type extends a;

```aadl
package Cyclic_Error_Types
public
system sys
	features
			i: in data port;
	end sys;

	system implementation sys.impl
		annex EMV2 {**
			error propagations
				i: not in propagation {Cyclic_Error_Types::a, ErrorLibrary::AboveRange};
			end propagations;
		**};
	end sys.impl;

	annex EMV2 {**
		error types
			a: type extends b;   
			--b: type extends a;
		end types;
	**};
end Cyclic_Error_Types;
```

## Environment

* **OSATE Version**: 2.8.0
* **Operating System**:  Windows 10

**Comment by keh181** [comment]
@RyanMcilnay Would you be able to provide more information or another model for this issue? I was unable to reproduce the behavior you described above.

**Comment by philip-alldredge** [comment]
@keh181 do you have the outline open?  I was able to reproduce the issue Ryan described by following the steps he provided.  If the outline isn't open then the UI remains responsive but "Xtext validation" runs in the background and appears to be stuck.

Attached is a stack trace from the threads which appears to be most relevant. It was captured while the outline was open. It appears to be a deadlock.

[deadlock_stacktrace.txt](https://github.com/osate/osate2/files/5365722/deadlock_stacktrace.txt)

**Comment by keh181** [comment]
@philip-alldredge I am not sure if I originally had the outline open, but I can now get it to reproduce. Thank you for the stack trace and extra information.
