### ISSUE TITLE
Instantiation can be started while workspace is building

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#2456]
## Summary

It is possible to start instantiation while the workspace is building. In that case unresolved references, etc, lead to errors.

## Expected and Current Behavior

The instantiation should wait until the build is finished.

## Environment

* **OSATE Version**: 2.8.0
* **Operating System**: Win 10

**Comment by AaronGreenhouse** [comment]
I wasn't able to make anything bad happen by doing this, but I have figured out how to make the instantiation jobs wait for the builder to finish.

**Comment by AaronGreenhouse** [comment]
This needs to branch from the Issue #841  branch so that everything that instantiates can take advantage of the waiting.

**Comment by AaronGreenhouse** [comment]
This is more complicated than it initially seems.
 
I added 

```
			/* Wait for any builds to finish: Taken from DebugUIPlugin.launchInBackground(). */
			final IJobManager jobManager = Job.getJobManager();
			try {
				jobManager.join(ResourcesPlugin.FAMILY_MANUAL_BUILD, subMonitor.split(1));
				jobManager.join(ResourcesPlugin.FAMILY_AUTO_BUILD, subMonitor.split(1));
			} catch (InterruptedException e) {
				/* just continue. */
			}
```

to the start of `AbstractInstantiationJob.runInWorkspace()`.  Two things:

1. It definitely blocks the job, and the progress display says that it is waiting for "Build" to complete.

2. The problem is that something about the job cause the "Build" job to wait as well, so they become deadlocked. 

I took the join calls back out of the `AbstractInstantiationJob` and tried things. The instantiation jobs cause the build to pause.  Not sure why, perhaps because they lock output directory for file creation?

**Comment by AaronGreenhouse** [comment]
@lwrage Suggests looking at this <https://www.eclipse.org/forums/index.php/m/1816939/#msg_1816939> regarding job priorities.

**Comment by AaronGreenhouse** [comment]
Had to do the following in `AbstractInstantiationEngine.instantiate()`

1. Create a job that waits for the build to finish.  This job doesn't require any resources.
2. When the builder is finished it creates and schedules the rest of the real instantiation jobs and the results collection job.
3. This job waits for the results job to finish before it finishes
4. The method `instantiate()` waits for this job to finish before collecting its results and returning them.

The key things here seem to be
* Not requiring any resources.  When I tried to have the instantiation jobs wait for the builder directly, the builder would suspend and wait for them.  If I removed the resource requirement as a test (it would be wrong to remove it for real) then the builder didn't suspend.  I have no idea how the builder is creating this behavior.
* I tried to changing the jobs to have the `BUILD` priority, but that didn't matter.

There is definitely some Eclipse magic at work here that I don't understand, but I ahve been able to make this work, I think.

Also, starting a build while the instantiation is already running causes the build to wait for the instantiation to finish.  Again, I have no idea why this is the case and how the builder is doing this.  There may magic in the Eclipse job scheduler itself?

**To do:** Still to need to check that cancellation works correctly.

**Comment by AaronGreenhouse** [comment]
Cancellation is okay

**Comment by AaronGreenhouse** [comment]
Some things learned about the builder:
* The automatic builder class is `AutoBuildJob`
* Running a task with `Workspace.run()` causes an interrupt and reschedule of the auto build
* The auto build periodically checks if a job with a conflicting rule is waiting to run (that is, is being blocked by the auto build).  If so, the auto build interrupts and reschedules itself.
