### ISSUE TITLE
Help text for Example wizard does not respect dark mode

### ISSUE THREAD

**Issue by jjhugues** [osate/osate2#2465]
The help text that accompanies examples does not respect dark mode, see attached screenshot.
Tested on mac

![Image 9-29-20 at 10 29 AM](https://user-images.githubusercontent.com/50238921/94572284-d635a580-023e-11eb-8408-794e1805703c.jpg)

**Comment by lwrage** [comment]
That seems to be a bug in SWT: https://bugs.eclipse.org/bugs/show_bug.cgi?id=548960
