### ISSUE TITLE
Add a way to disable unused contributed property sets and packages

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#2474]
## Summary

All property sets and packages contributed by plug-ins are added to each build by default. Many models only need the predeclared properties and maybe the EMV2 library. To increase performance the user should have the option to exclude unnecessary contributions.

## Expected and Current Behavior

There should be a checkbox in the preference setting for overriding plugin-contributions. Unchecking disables the contribution. Also disable via context menu in navigator. 

Disabled contributions should be greyed out in the navigator.

Investigate if it is possible to auto-enable if a disabled contribution when it is used in a model.

Also disable overridden contributions.

## Environment

* **OSATE Version**: 2.8.0
* **Operating System**: all

**Comment by AaronGreenhouse** [comment]
You will need to update `AadlContributionContentProvider.getChildren()`.  Currently you will see code there where it looks to replace one URI with an overridden URI.  You will want to add a section that filters out URIs.
