### ISSUE TITLE
Annex parser throws exception on BA block beginning with LF.

### ISSUE THREAD

**Issue by schwerdf** [osate/osate2#2497]
## Summary
When opening the attached model file in OSATE, the text-editor window appears as a blank screen with the words, "String index out of range: -1".

The debugger reveals that the cause of this is a `StringIndexOutOfBoundsException` rising from [this line](https://github.com/osate/osate2/blob/2d572c2a992dd60d9ae7eed0033c4588d5fa0047/core/org.osate.xtext.aadl2/src/org/osate/xtext/aadl2/parsing/AnnexParserAgent.java#L281), when parsing a block in which the first character is a LF and `endOfLine` is thus equal to 0.

Model file (attached rather than pasted, to ensure transmission character-for-character):
[BAParserBug.tar.gz](https://github.com/osate/osate2/files/5483945/BAParserBug.tar.gz)

## Environment

* **OSATE Version**: 2.9.1
* **Operating System**: Windows 10 and macOS 14

Tag: @smithdtyler

**Comment by lwrage** [comment]
This happens only if the BA annex has errors other than syntax errors.
