### ISSUE TITLE
Graphical editor uses inefficient property tester

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#2499]
## Summary

Plugin org.osate.ge has a property tester (class `org.osate.ge.internal.expressions.ResourcePropertyTester`) to test if a file is an AADL package by loading the file into a resource set. This is horribly inefficient.

## Expected and Current Behavior

The plugin should use `org.osate.ui.handlers.AadlFileTypePropertyTester`, instead. (We should put this one in a different package!)

## Environment

* **OSATE Version**: 2.9.0
* **Operating System**: all

**Comment by philip-alldredge** [comment]
`org.osate.ge.internal.expressions.ResourcePropertyTester` also provides an additional `name` property that is no longer used. `ResourcePropertyTester` should be removed completely after switching to the property provided by `aadlFileTypePropertyTester`.
