### ISSUE TITLE
Graphical editor unnecessarily parses AADL file to enable handlers

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#2500]
## Summary

When right clicking on an AADL in the AADL navigator method `setEnabled()` of classes `org.osate.ge.internal.ui.handlers.OpenDiagramHandler` and `...CreateDiagramHandler` is called. In both cases `org.osate.ge.internal.ui.util.SelectionUtil.getDiagramContext(ISelection, IEditorPart)` parses the AADL file. IIUC this is done to check if a package file is selected. This should be simplified to not parse the selected AADL file.

Similarly, right click on an aaxl2 file reads the instance file into memory. Maybe it is sufficient to just check the file extension.

## Environment

* **OSATE Version**: 2.9.0
* **Operating System**: all

**Comment by philip-alldredge** [comment]
Yes, `setEnabled` could have a quicker code path that performs limited checks. When the handlers are executed, the full check will need to be performed and a sensible error displayed if the model object could not be retrieved. This should only occur in cases where there was a file with an "aaxl2" extension but the instance model could not be loaded.
