### ISSUE TITLE
Error report when trying to open excel report

### ISSUE THREAD

**Issue by sholomc** [osate/osate2#2535]
## Summary

When trying to open the excel report, OSATE states that the file name is too long, it must be less that 218 characters.  

## Expected and Current Behavior

When I modify the file name to shorten it, the report opens correctly in Excel

## Steps to Reproduce

1.  Create an implementation with a long name
2. Instantiate the implementation
3. When SCS.singletier1... is instantiated and analyzed, the resulting .csv file opens properly
4.   When SCS.singletier0... is instantiated and analyzed, the resulting .csv file does not open. It does not appear to be over 218 characters.

```aadl
package IntegratedSCS
public
	
	system SCS -- sensor control system template
  	-- Total system weight must comply with Weight_R1
  	-- Bandwidth must comply with Comms_R1
  	end SCS;

	system implementation SCS.singletier1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
		subcomponents
	
			ControlSystem: system;
			sensor1: device;
			sensor2: device;
			actuator:device;
		

	end SCS.singletier1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;

	system implementation SCS.singletier0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
		subcomponents
	
			ControlSystem: system;
			sensor1: device;
			sensor2: device;
			actuator:device;
		

	end SCS.singletier0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
end IntegratedSCS;
```

## Environment

* **OSATE Version**:  2.9.0
* **Operating System**:   Windows

**Comment by lwrage** [comment]
Can you open the file from the Windows Explorer in Excel or in Notepad?

The Windows file name length limitation includes the full path to the file in addition to the file name itself.

**Comment by sholomc** [comment]
Thanks for that suggestion.  The file doesn't open directly from excel.

Sent from Workspace ONE Boxer

On Nov 28, 2020 2:11 PM, Lutz Wrage <notifications@github.com> wrote:

Can you open the file from the Windows Explorer in Excel or in Notepad?

The Windows file name length limitation includes the full path to the file in addition to the file name itself.

**Comment by lwrage** [comment]
If the file doesn;t open in Excel, either, it is not on OSATE issue but the general Windows limitation.
