### ISSUE TITLE
Packages are linking to the wrong default property set resources

### ISSUE THREAD

**Issue by RyanMcilnay** [osate/osate2#2537]
## Summary
Projects/packages that are created after an existing project exists are linking to the existing project's default property sets instead of the new project's property sets.

## Expected and Current Behavior
The newly created package should be linking to the default property sets that are referenced within the owning project.

## Steps to Reproduce
1. Create a project named Test1
2. Create another project named Test2
3. Create a package in Test2 named test
4. Add"with Base_Types;" in the newly created package in Test2 public section.
The new package should look like:
````
package test
public
	with Base_Types;
end test;
````
5. Right click Test1 and select "Close Project"

An error that states "Couldn't resolve reference to ModelUnit 'Base_Types'." occurs.

## Environment

* **OSATE Version**: 2.9.0
* **Operating System**: Windows

**Comment by lwrage** [comment]
This is #2195. The fix for that was inadvertently removed.
