### ISSUE TITLE
Use AGREE as an ALISA verification activity

### ISSUE THREAD

**Issue by sprocter** [osate/osate2#2568]
**Please describe the problem your proposed feature would address**

I would like to be able to use AGREE as an ALISA verification activity. This is, according to [the documentation](https://rawgit.com/osate/alisa/develop/org.osate.alisa.help/contents/VerifyDoc.html#Supported%20Verification%20Method%20Kinds) already supported, but a message on [the mailing list](https://groups.google.com/g/osate/c/MitcS0WqWOc) indicates otherwise 

**What is the impact of the problem?**

Linking AGREE to requirements is far harder than it needs to be, and this reduces the usability of both AGREE and ALISA.

**Describe the solution you'd like**

The functionality, as described in the ALISA documentation, should be implemented.

**Describe alternatives you've considered**

Most papers on AGREE seem to use other specifications of requirements, or ask designers to specify requirements directly in AGREE.

**Additional context**
N / A

**Comment by lwrage** [comment]
- The old integration was broken after a change to AGREE so we removed it (see #1106). The documentation needs to be updated.
- Resolute (probably in newer versions than supported in OSATE) seems to support calling AGREE, which could be a workaround.
- The whole Resolute/AGREE integration needs to be reworked. This would require creation of a proper interface to call Resolute/AGREE.
