### ISSUE TITLE
Generate property set accessor code for org.osate.contribution.sei 

### ISSUE THREAD

**Issue by AaronGreenhouse** [osate/osate2#2573]
## Summary

The property set accessor code the property sets provided by `org.osate.contribution.sei` should be generated (using the tool in `org.osate.propertiescodegen` and put into this project.

**Comment by AaronGreenhouse** [comment]
See <https://github.com/osate/osate2/wiki/Properties-Code-Generator>

**Comment by AaronGreenhouse** [comment]
* Added generated code to `org.osate.contribution.sei` in a new `src-gen` directory.
* Added `@codegen-package` tags to the property set definitions
* Deprecated the classes in `org.osate.contribution.sei.names`
* Deprecated the class `GetProperties` in project `org.osate.xtext.aadl2.properties`
* Removed the the dependency on `org.osate.contribution.sei ` from `org.osate.xtext.aadl2.properties`

**Comment by lwrage** [comment]
Please add "Will be removed in 2.10.0" to the `@deprecated` javadoc tag so people know what to expect.
