### ISSUE TITLE
Typeset with target state of error transition not marked as error

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#2579]
**Summary**
OSATE accepts error transitions where the target state has an arbitrary type set.

**Expected behavior**
Only individual error types should be allowed E.8 rule `target_error_type_instance`.

**Steps To Reproduce**

1. Copy and paste the following model in the AADL text editor in OSATE

```aadl
package emv::transition
public
	annex emv2 {**
		error behavior EB
			events
				ev: error event;
			states
				s: state {ErrorLibrary::CommonErrors};
		end behavior;
	**};
	
	system S
		annex emv2 {**
			use types ErrorLibrary;
			use behavior emv::transition::EB;
			component error behavior
			transitions
				-- this is valid
				s -[ev]-> s{ItemOmission};

				-- these two should be marked as errors
				s -[ev]-> s{CommonErrors};
				s -[ev]-> s{ItemOmission, ServiceOmission};
			end component;
		**};
	end S;
end emv::transition;
```

**Desktop (please complete the following information):**
 - OSATE Version: 2.9.1
 - Operating System: Linux

**Comment by lwrage** [comment]
Add validation to check that there is one error type (or a product type) named with the target state. A type set containing a single error type isn't allowed, either. 

@keh181 Check other places in the standard where `target_error_type_instance` is used for similar bugs.

**Comment by jjhugues** [comment]
Can you check this issue please: https://github.com/saeaadl/emv2/issues/28
It seems related. Thanks
