### ISSUE TITLE
In BA plugin, fail to open provided examples

### ISSUE THREAD

**Issue by Etienne13** [osate/osate2#2583]
**Summary**
 
Some of the Behavior Annex examples, provided with the plugin, cannot be open by the editor. 

**Expected behavior**
Import, open and edit examples provided with the behavior annex plugin

**Actual behavior**
When opening some of these examples, inconsistent error messages appear (due to exceptions in the BA plugin) or the editor crashes.

**Steps To Reproduce**

1. Go to 'File'
2. Click on 'New --> Examples...'
3. Import all the Behavior Annex examples
4. See errors.

**Desktop (please complete the following information):**
 - OSATE Version: 9.2.1
 - Operating System: Linux

**Additional context**
Some of the errors are expected; but I don't think it is a good idea to provide erroneous examples (they are tests, not examples).
Some of the errors are bugs (regressions); either in the models (e.g. modes) or in the plugin (class cast exceptions).

A cleanup is necessary.

**Comment by jjhugues** [comment]
In addition, OSATE now has a different wizard for examples with additional features like showing a README. You might consider migrating and use this one instead

**Comment by Etienne13** [comment]
@jjhugues Can you point to an example so I can see how the new wizard works? Thanks!

**Comment by jjhugues** [comment]
File -> New -> Example

The rest is basic Eclipse plugin machinery, see https://github.com/osate/osate2/tree/master/examples
the core is in this xml file that points to examples, README, etc: https://github.com/osate/osate2/blob/master/examples/org.osate.examples/plugin.xml

**Comment by lwrage** [comment]
@Etienne13 Should this be moved to the next release?

**Comment by Etienne13** [comment]
@lwrage the initial issue is fixed in branch 2583; I could not work on the examples documentation as suggested by Jerôme. I think the release you are preparing should include the existing fix. I will prepare the PR.
