### ISSUE TITLE
Example AADL Project label is missing

### ISSUE THREAD

**Issue by AaronGreenhouse** [osate/osate2#2584]
**Summary**
Open the new project wizard in Eclipse/OSATE.  Under AADL you will see an entry `%_UI_OsateExmpleWizard_label`.  

![Screen Shot 2021-02-18 at 11.30.33 AM.png](https://images.zenhubusercontent.com/5cc7040c07a4ab52d27abe58/8e9ed384-57cd-4699-8662-872d3cb53baf)

**Expected behavior**
The label is not being resolved correctly.  I assume this should say something like "AADL Example Project"

**Desktop (please complete the following information):**
 - OSATE Version: 2.9.1
 - Operating System: Mac OS

**Comment by lwrage** [comment]
That entry shouldn't be there at all. The correct one is under Examples where it belongs.
