### ISSUE TITLE
Mylyn is missing in the OSATE product build

### ISSUE THREAD

**Issue by AaronGreenhouse** [osate/osate2#2585]
**Summary**
Mylyn functionality is missing from the OSATE product builds.  Cannot open the `Task List` view because none of the Mylyns views are missing:

![Screen Shot 2021-02-18 at 11.37.19 AM.png](https://images.zenhubusercontent.com/5cc7040c07a4ab52d27abe58/b2419935-9f36-4f35-871b-e1a40456e745)

**Expected behavior**
Mylyn should be present.  Plug-ins or feature probably needs to be added the build files.

**Actual behavior**
Mylyn is missing.

**Screenshots**

**Desktop (please complete the following information):**
 - OSATE Version: 2.9.1
 - Operating System: Mac OS

**Comment by AaronGreenhouse** [comment]
The OSATE project `org.osate.mylyn.aadl.ui` depends on the following Mylyn plug-ins:
 * `org.eclipse.mylyn.context.core`
 * `org.eclipse.mylyn.context.ui`
 * `org.eclipse.mylyn.monitor.ui`
 * `org.eclipse.mylyn.monitor.core`
 * `org.eclipse.mylyn.resources.ui`
 * `org.eclipse.mylyn.commons.core`

**Comment by lwrage** [comment]
It may be sufficient to add feature `org.eclipse.mylyn.context_feature` to the product configuration. That should pull in everything that is needed.
