### ISSUE TITLE
GetProperties.getDispatchProtocol needs property Thread_Properties::Dispatch_Protocol

### ISSUE THREAD

**Issue by brlarson** [osate/osate2#2587]
**Summary**
Calling GetProperties.getDispatchProtocol when 
properties
	Dispatch_Protocol => Periodic;
returns null.

Calling it on
properties
	Thread_Properties::Dispatch_Protocol => Periodic;
returns "Periodic".

**Expected behavior**
When the optional "Thread_Properties" is omitted, GetProperties.getDispatchProtocol should return an enumeration literal for Dispatch_Protocol (if defined)

**Actual behavior**
Instead it returns null.  However including "Thread_Properties" works fine.

**Steps To Reproduce**
List<ComponentType> componentTypesInPackage = EcoreUtil2.eAllOfType(pr.myAadlPackage, ComponentType.class);
for (ComponentType ct : componentTypesInPackage)
  {
  EnumerationLiteral dispatchProtocol = GetProperties.getDispatchProtocol((NamedElement)ct);
. . .

dispatchProtocol will be null when ct is myThread.

After much futzing, tried Thread_Properties::Dispatch_Protocol, and it works fine. 

```aadl
thread myThread
properties
	Dispatch_Protocol => Periodic;
end myThread;
```

**Desktop (please complete the following information):**
 - OSATE Version:  commit 9c58912e56 on Feb 16, 2021
 - Operating System: macOS Catalina 10.15.7

**Comment by lwrage** [comment]
We are in the process of deprecating GetProperties and providing a new API to access properties. We will post an announcement on the google group once documentation is available.
