### ISSUE TITLE
Wrong icons for calls and parameter connections

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#2605]
**Summary**
The outline view shows a generic icon for calls and parameter connections.

It should use an oval for calls and a line with a P on top for parameter connections.

**Screenshots**
![image](https://user-images.githubusercontent.com/750311/109855599-79437e80-7c26-11eb-9607-2ab8300116b9.png)

**Desktop (please complete the following information):**
 - OSATE Version: 2.9.1
 - Operating System: Linux

**Comment by asazonova** [comment]
![image](https://user-images.githubusercontent.com/65192219/117977346-b4d18780-b2fe-11eb-95cc-f3597e4c8e7e.png)
