### ISSUE TITLE
Missing error/warning markers on instance model elements

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#2612]
**Summary**
Instance editor and AADL navigator no longer show any error or warning markers on instance objects.

This used to work in OSATE 2.9.0.

**Steps To Reproduce**

1. Add model below in an AADL project
2. Instantiate `S.i`
3. Open instance model in instance editor
4. Expand instance model in navigator

```aadl
package Issue2612
public
	
	system S
	end S;
	
	system implementation S.i
		subcomponents
			l: system L;
			m: system M.i;
			r: system R;
		connections
			lm: feature l.o -> m.i;
			mr: feature m.o -> r.i;
		flows
			ee: end to end flow l.src -> lm -> m.pth -> mr -> r.snk;
	end S.i;
	
	system L
		features
			o: out feature;
		flows
			src: flow source o;
	end L;
	
	system M
		features
			i: in feature;
			o: out feature;
		flows
			pth: flow path i -> o;
	end M;
	
	system implementation M.i
		subcomponents
			mm: system M;
		connections
			imm: feature i -> mm.i;
	end M.i;
	
	system R
		features
			i: in feature;
		flows
			snk: flow sink i;
	end R;
	
end Issue2612;
```

**Screenshots**
OSATE 2.9.1:
![image](https://user-images.githubusercontent.com/750311/110171191-60270300-7dc9-11eb-9fbd-186e1b44fa58.png)

OSATE 2.9.0:
![image](https://user-images.githubusercontent.com/750311/110171262-7e8cfe80-7dc9-11eb-92d7-f01badf253e9.png)

**Desktop (please complete the following information):**
 - OSATE Version: 2.9.1
 - Operating System: Linux, Windows 

**Additional context**
Maybe caused by the fix to #2430.

**Comment by AaronGreenhouse** [comment]
Same problem as Issue #2609.  Fix for 2609 fixes this too.

**Comment by lwrage** [comment]
Only navigator markers are #2609. Missing markers in the instance editor are the main issue. This is caused by switching back to the EMF generated model editor which doesn't have that functionality.
