### ISSUE TITLE
OSATE 2.9.1 product should open in AADL perspective

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2#2621]
**Summary**
When I download and open OSATE 2.9.1 product, I have to open the AADL perspective manually.

**Expected behavior**
Install opens in AADL perspective.

**Actual behavior**
See summary

**Steps To Reproduce**
Download OSATE 2.9.1 and launch it.

**Screenshots**

**Desktop (please complete the following information):**
 - OSATE Version: 2.9.1
 - Operating System:  Windows 10

**Additional context**

**Comment by lwrage** [comment]
Duplicate of #2569. The workaround is described in the 2.9.1 release notes.
