### ISSUE TITLE
NPE when instantiating a system with unbound prototype

### ISSUE THREAD

**Issue by jjhugues** [osate/osate2#2631]
**Summary**
In issue https://github.com/saeaadl/aadlv2.2/issues/19, the following example is reported

```
package issue19
public
	system s
		-- ...
	end s;

	system implementation s.i
		prototypes
			X: bus;
			-- ...
		subcomponents
			b: bus X;
			-- ...
	end s.i;

	system T

	end T;

	system implementation T.i
	subcomponents
		sub1: system s.i; -- no prototype binding
		-- ...
	end T.i;
	
end issue19;
```
**Expected behavior**

OSATE should either instantiate the model or reject it. From the original issue, it should be rejected since the prototype is not bound. The OP hints as some specific behavior OSATE implements

**Actual behavior**

OSATE reports a NPE

**Steps To Reproduce**

- Instantiate T.i

**Comment by lwrage** [comment]
Instantiation could be done with a warning on the subcomponent that an unbound prototype was used.

`s.i` from the example can be treated during instantiation as 

```
system implementation s.i
	subcomponents
		b: bus;
end s.i;
```

Whenever an prototype has a classifier that classifier can be instantiated.

**Comment by lwrage** [comment]
No longer reproducible in 2.15.0 nightly.
