### ISSUE TITLE
Cannot create diagram

### ISSUE THREAD

**Issue by kquick** [osate/osate2#2714]
**Summary**
When attempting to "Create Diagram..." or "Open Diagram" from right-click menu in a .aadl file, I get a popup "Error creating diagram: null argument: " and no diagram is created.

**Expected behavior**
The ability to create a diagram or better information about why I cannot create one.

**Actual behavior**
Above

**Steps To Reproduce**

1. File open test.aadl  (see below)
2. Right-click in test.aadl and select "Create Diagram..."
3. See error

```aadl
package test
public
end test;
```

Note that this happens for any AADL file, the above is the minimal example for reproducing the problem.

**Desktop (please complete the following information):**
 - OSATE Version:  2.9.2.vfinal
 - Operating System: ubuntu 20.04.3

**Additional context**
Performed `$ sudo apt install openjdk-8-jre` and downloaded https://osate-build.sei.cmu.edu/download/osate/stable/2.9.2/products/osate2-2.9.2-vfinal.linux.gtk.x86_64.tar.gz, unpacked, and executed the `osate` executable from the unpack.

**Comment by lwrage** [comment]
I tried in an Ubuntu VM (20.04.2) with Java 8 and cannot reproduce the error. Do you have anything in the error log (open with window > show view > other > general > error log)?

**Comment by kquick** [comment]
The errors in the error log are:
`Command 'org.osate.ge.commands.creatediagram' failed  (Plug-in `org.eclipse.e4.ui.workbench`)
`org.osate.ge.internal.ui.handlers.CreateDiagramHandler.execute(): Error creating diagram` (Plug-in `org.osate.ge`)
`org.osate.ge.internal.ui.handlers.CreateDiagramHandler.execute(): CreateDiagramHandler Started` (Plug-in `org.osate.ge`)

Note that only the bottom-most appears after selecting the `Create diagram...` button.  When clicking on `OK` in the error dialog, the next two lines appear above the bottom-most line.

**Comment by lwrage** [comment]
How do you open the aadl file? Is it in an AADL project that is visible in the AADL navigator?

**Comment by kquick** [comment]
Generally just "File -> Open" and select the .aadl file, then in the .aadl contents in the main window, right click and select "Create diagram...".

**Comment by lwrage** [comment]
That explains it. In OSATE we generally assume that AADL files are organized in projects in a workspace. This is inherited from Eclipse, on which OSATE is based. 

If you are not familiar with these concepts see the Getting Started guide: Help > Help Contents, then expand "OSATE Core Documentation" and select "Getting started"
