### ISSUE TITLE
ConnectionInstances need to consider the modes of the endpoints

### ISSUE THREAD

**Issue by AaronGreenhouse** [osate/osate2#2722]
**Please describe the problem your proposed feature would address**

When a semantic connections exists between two components, it should only exist in the system operation modes that both components exist in.

When a semantic connection exists between a component and a feature it should only exist in the system operation modes that the component exists in.  

**What is the impact of the problem?**

Currently semantic connections (`ConnectionInstance` objects) between modal components do not have their `InSystemOperationModes` attribute set.  This attribute is only set if one of the declarative connections that makes up the semantic connection is modal.

This can lead to a view of the instance model where a semantic connection exists, but the components it is connecting do not.

Furthermore, things are complicated by the fact that `ConnectionInstance.isActive()` does take this information into account:

```
        public boolean isActive(SystemOperationMode som) {
                if (getInSystemOperationModes().isEmpty() || getInSystemOperationModes().contains(som)) {
                        if (getSource().getComponentInstance().isActive(som)
                                        && getDestination().getComponentInstance().isActive(som)) {
                                return getContainingComponentInstance().isActive(som);
                        }
                }
                return false;
        }
```

**Describe the solution you'd like**

The process that applies SOMs to connection instances need to be updated to handle this situation.

**Comment by lwrage** [comment]
The connection SOMs are missing when a modal source/destination is the *only* reason for the connection instance to be modal. Otherwise source and destination modes are taken into account correctly.
