### ISSUE TITLE
When I use eclipse to start osate development, an error appears

### ISSUE THREAD

**Issue by Lqs66** [osate/osate2#2735]
![image](https://user-images.githubusercontent.com/62269820/143686654-89918f8a-32b7-4ae4-b3c5-4788605bcaa1.png)

Operating system is macos

**Comment by lwrage** [comment]
This is not an OSATE bug, it looks like you did not set up your development environment correctly. Please check the instructions on osate.org. If you have questions about the development environment please ask on the google group.
