### ISSUE TITLE
OSATE 2.9.2 includes end of life log4j version

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate2#2738]
**Summary**
OSATE 2.9.2 (when downloaded from osate.org) includes log4j version

org.apache.log4j_1.2.15.v201012070815.jar

Per the Apache vulnerability page, this version is ~vulnerable~ EOL and should be updated:

https://logging.apache.org/log4j/2.x/security.html

**Comment by smithdtyler** [comment]
I may have misread the version number (mistaking 1.2.15 for 2.15). Per Apache, Log4j versions 1.x is no longer supported, but is not mentioned in the description of this issue. 

> Please note that Log4j 1.x has reached end of life and is no longer supported. Vulnerabilities reported after August 2015 against Log4j 1.x were not checked and will not be fixed. Users should upgrade to Log4j 2 to obtain security fixes.

**Comment by lwrage** [comment]
Log4J 1.2.15 comes as part of the Eclipse. At least Xtext depends on it, so this cannot be changed in OSATE.
