### ISSUE TITLE
setting up development failed when following guideline

### ISSUE THREAD

**Issue by fg71205902046** [osate/osate2#2739]
**Summary**
setting up development failed when following guideline in website https://osate.org/setup-development.html

**Expected behavior**
I hope a revised version of setup development can be released in website https://osate.org/setup-development.html

**Actual behavior**
When I was doing step 6. Install Eclipse , an error occurred as "ERROR: org.eclipse.equinox.p2.metadata.repository code=1000 No repository found at http://eclipse.py4j.org.". when blocked me to finish install.

**Steps To Reproduce**

follow guideline in https://osate.org/setup-development.html. the same error should be reproduced in step 6.

**Screenshots**
![image](https://user-images.githubusercontent.com/96690140/147875943-24386c30-7709-44e1-8130-45fbcc7bb1c0.png)

**Desktop (please complete the following information):**
 - OSATE Version:2021-03
 - Operating System: windows

**Comment by lwrage** [comment]
Looks like a temporary network error, I cannot reproduce it.
In general, problems with setting up the development environment are best discussed on our google group.
