### ISSUE TITLE
Need way to determine if a property association is explicitly set, inherited, or default

### ISSUE THREAD

**Issue by AaronGreenhouse** [osate/osate2#2765]
**Please describe the problem your proposed feature would address**

Often analyses have several different options for getting information from a model. In particular, there might be a set of properties whose values can be used to derive replacements for each other (e.g, deadline and worst case execution time).  Or, a property can be obtained from a referenced classifier instead of from the feature itself (in the case of the security analysis).  The problem is, this interacts badly with default and inherited property values.  Currently, there is no easy way to determine if a property value in a property association comes from a property's default value, is inherited from a containing component, or is explicitly set on that component.  

Ideally what we want to see in the analysis code is something like

- _If property P1 does not have an explicit association on component C, try to get the value of Property P2 on C; otherwise use the inherited/default value_, or

- _If property P2 does not have an explicit association on component C, try to get the value of property from referenced classifier X, or from component D; otherwise use the inherited/default value._

**What is the impact of the problem?**

This problem impacts analysis implementation in at least 3 ways:

1. It prevents the use of default values in property set definitions because they interfere with checking for the existence of property values in the analysis implementation.

2. You have ugly code where you get the property value, and then explicitly try to check if the value is equal to the default value, but this is hard because it's not easy to actually find what is the default value, and it still doesn't tell you if the property _was explicitly set to that value_, or if it defaulted to that value.

3. Alternatively, default property values are used, but then the analysis has to use convoluted code to check the model trees for the existence of local property associations to see if the property value came from the default value or not.  (This is the case in at least one analysis written by Peter.)

**Describe the solution you'd like**

I can think of at least two ways to address aspects of this problem:

1. Add an attribute to the property association in the the metamodel that indicates where the property value comes from.  I imagine this is best as an enumerations, something like (EXPLICIT, INHERITED, DEFAULT).  This isn't perfect because it doesn't indicate with contained component an inherited value comes from, but so far that isn't something we have cared about.  This attribute would only be meaningful in the instance model, and would have to be set during the final pass through the instance model that adds all the property associations to it.

2. New variants of the generated property lookup methods could take a handle to a helper method that intervenes if the returned property value would be from the default property value, and allows an alternative lookup to occur.  This would allow a standard way to interrupt the lookup process.  Might be problematic though if the alternative property has a different property type.  This needs more thought, but the general idea is there should be some standard programmatic way to introduce an alternative lookup.

**Comment by lwrage** [comment]
After some discussion we decided to not implement support for this. If an analysis wants to allow users to choose to ignore a property value even though it is present on a model element there should be an additional analysis specific property which can be used to make the choice explicit. This is preferable to the implicit choice described above.
Currently only the flow latency analysis uses the implicit approach to ignore the deadline property in some situations.
