### ISSUE TITLE
Stale documentation

### ISSUE THREAD

**Issue by podhrmic** [osate/osate2#2850]
**Summary**
Some documentation at https://osate.org/setup-development.html is stale. Specifically:

* [Run the Installer](Select Eclipse IDE for Java Developers as the base product to install, and select 2022-06 as the product version. DO NOT USE Latest Release (2022-06).)

> the installer crashes on Ubuntu 20.04, downloading Eclipse for Java and then importing OSATE projects works, perhaps it should be documented?

* [Selection Eclipse platform](https://osate.org/setup-development.html#select-the-eclipse-platform) says:

> Select Eclipse IDE for Java Developers as the base product to install, and select 2022-06 as the product version. DO NOT USE Latest Release (2022-06).

This is a contradiction - 2022-06 seems to work OK.

* [Set required variables](https://osate.org/setup-development.html#set-required-variables)
The picture seems to be stale - the 2022-06 release has fewer variables available, even when selecting *Show all variables*

* [Install the Java FX](https://osate.org/setup-development.html#install-the-javafx-sdk)

Version 17 is no longer available for download and compiling Java FX from scratch is rather tedious. [Liberica SDK](https://bell-sw.com/pages/liberica_install_guide-17/) offers the Java FX 17, so the docs should perhaps be updated.

**Comment by lwrage** [comment]
Documentation has been clarified regarding the eclipse version. (**Latest Release(2022-06)** entry was replaced with **Latest Release( 2022-09)** in September with the Eclipse 2022-09 release.)
Clarified JavaFX download instructions.
Added a note that available variables change based on the selections in drop-downs.

Please provide more information about the installer crash. I recently ran it on Ubuntu 20.04 without a problem.

**Comment by podhrmic** [comment]
Thanks for the updates. One more nitpick - the [getting help](https://osate.org/getting-help.html) section recommends using google groups for reporting issue, while the [development section](https://osate.org/setup-development.html#updating-the-development-environment) mentions using github issues. Is the intend to keep the osate user questions on the mailing list, and osate developer/development related issues on github?

> Please provide more information about the installer crash. I recently ran it on Ubuntu 20.04 without a problem.

Looks like a good old reset fixed it, not sure what was wrong the first time.

**Comment by lwrage** [comment]
I've updated the text to point to the Google group. In general we want to direct questions to the group and limit github issues to bugs and feature requests.
