### ISSUE TITLE
Cheddar extension not available in Osate 2

### ISSUE THREAD

**Issue by ahmedwaqar** [osate/osate2#2923]
**Summary**
When installing Cheddar plugin getting error message "Cheddar extension not available".

**Expected behavior**
An installation should be successful or clear error message.

**Actual behavior**
Getting the error popup message: 

"Problems occurred while performing installation: The following extensions are not available: Cheddar Plugin (id=cheddar_osate2_feature.feature.group, site=http://beru.univ-brest.fr/svn/CHEDDAR/trunk/src/osate/osate2-update-site)
The following extensions are not available: Cheddar Plugin (id=cheddar_osate2_feature.feature.group, site=http://beru.univ-brest.fr/svn/CHEDDAR/trunk/src/osate/osate2-update-site)"

**Steps To Reproduce**

1. Go to Help and Choose option "Install Additional OSATE Component"
2. Click on Cheddar Plugin
3. Error message "extension not available" will return.

```aadl
Paste your model here
```

**Screenshots**
<img width="679" alt="Screenshot 2024-10-14 at 3 53 48 PM" src="https://github.com/user-attachments/assets/2399badd-85d6-4492-922a-4f3a71ccdead">

attached

**Desktop (please complete the following information):**
 - OSATE Version: 2.14.0 vfinal
 - Operating System: MacOS Sequoia 15.0.1

**Additional context**
None

**Comment by lwrage** [comment]
The update site for the Cheddar plugin is provided by a team at the University of Brest. I suggest you contact them about the issue. Contact information is at http://beru.univ-brest.fr/cheddar/#RefMail.

**Comment by gon1332** [comment]
I have the same issue with osate2-2.18.0-vfinal-linux.gtk.x86_64 running on Fedora 42.

I think part of the issue is the link.

Cheddar's new link is now adhearing to HTTPS, whereas the link that is hardcoded in OSATE is HTTP.

https://beru.univ-brest.fr/cheddar/

Could you please have a look at it?
