### ISSUE TITLE
Renaming elements in text editor does not work

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#359]
The AADL text editor has an operation to rename identifiers (context menu 'Rename Element' or Alt-Shift-r). This renames the identifier where it is declared but leaves all other occurrences unchanged.
child of #1371
depends on #1466

**Comment by Korny666** [comment]
![bug2](https://cloud.githubusercontent.com/assets/12656521/9033483/9cc4cce4-39c7-11e5-9372-c279decd92c6.png)
Renaming is not working consistently.

**Comment by lwrage** [comment]
What to do about references to component implementations when the component type is renamed?
- Investigate xtext handling of qualifies name segments.
- Maybe handle when adding name at end of classifier.

**Comment by lwrage** [comment]
Mark occurrences now marks type names in references to implementations. Rename refactoring is completely different. First need to create the linked editing regions for the editor, then adapt the actual renaming.

**Comment by lwrage** [comment]
And there are references from annexes and external languages into the core language. It is not clear how these need to be handled.

**Comment by lwrage** [comment]
Xtext 2.13 introduced improved support for semantic editing that may make it easier to implement component type renaming. Postponing this issue until after we've updated to Photon with the newer Xtext.

**Comment by lwrage** [comment]
Look at IDependentElementsCalculator for renaming component implementations.

**Comment by lwrage** [comment]
There is a way to trigger subsequent renamings, see http://koehnlein.blogspot.com/2011/06/rename-refactoring-in-xtext-20.html

**Comment by lwrage** [comment]
None of this seems to work with our meta-model :-(
