### ISSUE TITLE
Source code formatting for annexes

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#385]
Annexes (e.g. EMV2) are not formatted on Shift + Ctrl + F. Maybe use similar mechanism as syntax highlighting to switch to annex formatter.

**Comment by lwrage** [comment]
This is now possible with the new formatter API in Xtext 2.8.

**Comment by lwrage** [comment]
Xtext >2.9.2 is needed for this

**Comment by lwrage** [comment]
Can be implemented because we use the new formatter. Call annex formatters.

**Comment by lwrage** [comment]
Need to process annex node model to create annex semantic regions.

**Comment by lgwagner** [comment]
A quick question on this issue: Should I read this to mean that we need to use the formatter2 (vs the original xtext formatter) to get our annexes that are built in xtext to work properly?

**Comment by lgwagner** [comment]
No answer required. The answer is yes, and I have implemented (feebly) for parts of Resolute.
