### ISSUE TITLE
Synchronize deletion of packages with deletion of AGE diagrams

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2#400]
the graphical editor (AGE) creates multiple diagram files to go along with the content of a package.
When the user deletes the package the diagram files stay around. This clutters up the diagrams folder.

**Comment by lwrage** [comment]
@philip-alldredge It looks like this would fit with the work you're doing related to broken references.

**Comment by philip-alldredge** [comment]
We recently completed the ability to correct the broken references handling. However, that capability doesn't include deletion of diagrams with broken references. 

I consider this a separate issue. I have created a GE issue to track and discuss this further osate/osage-ge#246. As a shorter term goal, I believe showing all the diagrams with broken references may be feasible under the current work effort. I've added a note to osate/osate-ge#214 which covers upcoming UI enhancements with respect to diagrams. While not as ideal of automatic handling, it would make it much easier for the user to remove such diagrams.
