### ISSUE TITLE
Add property group filter to AADL property view

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#521]

**Comment by ArslanIbnDaud** [comment]
First, alter the tree filter viewer's layout to add a non-editable combobox menu to the right. This menu contains the property groups that are defined. Each grouop has a name and a subset of the current properties. Selecting that group makes only that subset of properties visible in the AADL property view. The menu should also contain a 'default' entry which lets all properties be visible (eg the current behavior).

Should also add a resource file to osate-core, which contains the subset names and subsets. For now this can be a raw text file that is read when the property group menu is created.
