### ISSUE TITLE
When renaming and Saveing - Bug (Lower/Upper Case)

### ISSUE THREAD

**Issue by Korny666** [osate/osate2#601]
When You got 

```
abstract aAbstract
end aAbstract;

abstract implementation aAbstract.impl
end aAbstract.impl;
```

and rename in the gui the abstract and then save immediately the following code comes up:

```
abstract aabstract
end aabstract;

abstract implementation aAbstract.impl
end aabstract.impl;
```

This is also reflected in the gui with a different case The impl is still with an A.

**Comment by Korny666** [comment]
This only happens for renaming in the same string. a different string will not provoke the same behavior. so lowerCase/UpperCase special

**Comment by joeseibel** [comment]
Duplicate of #359.
