### ISSUE TITLE
Data classifiers for ports are not instantiated

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#626]
If a port references a data classifier in the declarative model, this there is no trace of it in the instance model. Only subcomponents are instantiated. We could extend the metamodel to include referenced data classifiers somewhere, maybe as part of the top level instance object.
Instantiation is needed to handle properties of referenced classifiers correctly, e.g., to add up data sizes.

This allows implementation of saeaadl/aadlv2.2#5.

**Comment by AaronGreenhouse** [comment]
Main problem is when the data classifier is a prototype instantiation.  There is no record of how the prototype is expanded.
