### ISSUE TITLE
partial end-to-end flow specification

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2#675]
See saeaadl/aadlv2.1#7 for details.

**Comment by lwrage** [comment]
Ignore partial e2e flows during instantiation. It is an instantiation error if an unrefined partial e2e flow is used in another e2e flow that is instantiated.

**Comment by lwrage** [comment]
@reteprelief In the last 2 years nobody has pushed for implementing partial end to end flow support in OSATE. I'm tempted to close the issue as won't fix and document that partial end to end flows are not supported in OSATE.
