### ISSUE TITLE
Plugin_Resources and associated instance files need versioning information

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate2#710]
Files provided in Plugin_Resources when OSATE is installed don't have their OSATE version declared in a comment or header. Similarly, OSATE instance files don't declare which versions of Plugin_Resources property files they rely on. This means that when the OSATE version is changed, instances files referring to specific properties in Plugin_Resources may silently be made invalid.

A declared version would allow tools to evaluate whether a given instance file is valid given the current OSATE version and Plugin_Resources.

For an example of this issue, note that instance files referencing [Timing_Properties.aadl](https://github.com/osate/osate2-core/commits/develop/org.osate.workspace/resources/properties/Predeclared_Property_Sets/Timing_Properties.aadl) or [AADL_Project.aadl](https://github.com/osate/osate2-core/blob/develop/org.osate.workspace/resources/properties/Predeclared_Property_Sets/AADL_Project.aadl) may be broken by additions or deletions to those files.

Here's an example of such a reference (taken from an AAXL2 file). The reference might still be valid if AADL_Project.aadl changes, but it might not mean the same thing.

```
<property href="../../Plugin_Resources/Predeclared_Property_Sets/Timing_Properties.aadl#Timing_Properties.Deadline"/>
        <ownedValue>
          <ownedValue xsi:type="aadl2:IntegerLiteral" value="2">
            <unit href="../../Plugin_Resources/Predeclared_Property_Sets/AADL_Project.aadl#/0/@ownedPropertyType.12/@ownedLiteral.3"/>
          </ownedValue>
        </ownedValue>
```

**Comment by lwrage** [comment]
No resources available to implement this.
