### ISSUE TITLE
OSATE plugin versions should change when its dependencies change

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate2#776]
As an author of plugins which depend on OSATE, it would be really helpful if minor/maintenance version numbers of OSATE builds were incremented when OSATE changes the versions of plugins it uses. This will allow me to better manage transitive dependencies.

For example, if I write a plugin that uses OSATE 2.2.1_xyz and xtext 1.0.0, then OSATE 2.2.1_xzw switches to xtext 2.0.0, I'm unable to constrain my OSATE dependency so that only OSATE versions using xtext 1.0.0 are used by my plugin. If OSATE instead increments from 2.2.1 to 2.2.2, I'm able to constrain my plugins appropriately.

If the top level version number (e.g., 2.2.1) is difficult to change due to its high visibility, I'd like a less visible version number I can rely on to manage transitive dependencies.

I have discussed this issue with @joeseibel 
child of #1538

**Comment by lwrage** [comment]
As a first step we'll enable API analysis and Oomph version management such that we get errors if plugin versions must be changed.

**Comment by lwrage** [comment]
Requires some more experimentation with API tools and Oomph version management.

**Comment by lwrage** [comment]
Closed in 5bb0b0d21c654096781d27c8b34d087fbe653131
