### ISSUE TITLE
method getSystemOperationModesFor fails when null reference are counted in size of parameter mis

### ISSUE THREAD

**Issue by Etienne13** [osate/osate2#907]
Hello,

when executing getSystemOperationModesFor, I noticed that null references are counted in the size of the list mis, passed as a parameter of the method. As a consequence, the call to som.getCurrentModes().containsAll(mis) fails even if the content of mis and som.getCurrentModes() only differ by the number of null references counted in the size of these lists. The code bellow fix the issue by inserting while (mis.remove(null)); at the begining of the method. The System.out.println was used to debug.

	@Override
	public List<SystemOperationMode> getSystemOperationModesFor(List<ModeInstance> mis) 	
	{
		while (mis.remove(null));
		final List<SystemOperationMode> output = new ArrayList<SystemOperationMode>();
		for (SystemOperationMode som : getSystemOperationModes()) {
			System.out.println("Size "+mis.size() +" " +som.getCurrentModes().size());
			if (som.getCurrentModes().containsAll(mis)) {
				output.add(som);
			}
		}
		return Collections.unmodifiableList(output);
	}

Best regards,
Etienne.

**Comment by lwrage** [comment]
I would argue that this is not a bug because `null` references probably point to an issue in the calling code.

@Etienne13 Please re-open if you don't agree.
