### ISSUE TITLE
The core OSATE components are spread over too many git repositories

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#913]
Merge osate2-core, osate2-plugins, ErrorModelV2
What about osate-ge?

**Comment by lwrage** [comment]
According to @philip-alldredge osate-ge should also be merged.

**Comment by philip-alldredge** [comment]
Is the plan to do this in a way that preserves the commit history for all the repositories?

**Comment by lwrage** [comment]
The commit history must be preserved, and as far as I can tell git can support that. I am planning to create one directory in the unified repository for each merged old repository. This means that each file path would change, but git log can follow the renaming. 
I am planning to run an experimental merge soon (hopefully later this week), so we can see what it'll look like.

**Comment by lwrage** [comment]
@philip-alldredge @joeseibel @reteprelief @sprocter  
I've created a preview repo that shows what the merged repo would look like: [osate2-all](http://github.com/lwrage/osate2-all)

- All branches and tags are migrated
- All commit ids are the same as in the individual repos

The real merged repo should end up in osate2-core to keep its issues and the waffle.io board. The merged repos can be set to read-only mode or we could just remove write permission for everyone.

To do:

- [ ] change dir names to core, plugins, ge, emv2
- [ ] should alisa be included?
- [ ] setup: do not clone merged repos
- [ ] setup: generate working sets from directories
- [ ] clean up branches (can be done after merge)

**Comment by lwrage** [comment]
According to @reteprelief ALISA shouldl be included

**Comment by lwrage** [comment]
Everything should be merged into osate2-core repo so issue links can have the form #x. Cross repository links don't always work with waffle.

**Comment by lwrage** [comment]
@philip-alldredge @joeseibel @reteprelief @sprocter  
There is a new version of a merged repo at [lwrage/osate2-core](https://github.com/lwrage/osate2-core).
It contains a setup in to try it out: core/osate.releng/osate2-monorepo.setup 
**Use a fresh eclipse installation and a new git root directory!**
Pros:
- complete history
- identical commit ids
- continuation of osate2-core (no force push was necessary)

Cons:
- complete history can be viewed for individual files only (git limitation because of the rename when files are moved to subdirectories)
- some git history operations take a long time (in eclipse)

Next I'll create a merged repo that uses history rewrite so it'll look like the projects were in subdirectories from the very beginning. The idea is that the history in eclipse should look better and be faster. However, all commit ids will be different in this version.

**Comment by lwrage** [comment]
@philip-alldredge @joeseibel @reteprelief @sprocter 
The merged repo that rewrites the history is now available at lwrage/osate2-all](https://github.com/lwrage/osate2-all). It contains a setup that uses this repository.
With this repository one can see the complete history of directories and projects in Eclipe's History view.

**Comment by philip-alldredge** [comment]
@lwrage I've been looking at the merged repository that rewrites history, but this comments appears to be applicable to both. The various branches besides master and develop appear to only contain a subset of files. I haven't tried to merge one of those branches yet, but that will make it difficult to continue working on existing branches. Is there a way to work around that?

**Comment by lwrage** [comment]
The branches are the same as before. Develop needs to be merged into each branch I didn't make that part of the script because it's trivial to do on the command line. Also, not all branches should be merged and it could lead to merge conflicts, so it's better to this by hand as needed.
In eclipse it's a bit annoying: When you switch to a migrated branch eclipse closes all projects that are not on that branch. After merging develop the closed projects must be reopened.

**Comment by philip-alldredge** [comment]
I experimented with merging develop into one of the branches and then merging the result into develop as this would be the expected workflow when picking up work in unfinished branches.  It seems to work well. As you noted, merging the current develop into these branches could cause merge conflicts.

I think the merge conflicts could be avoided by merging an older version of develop into the branch. It would take a little while to find the appropriate version but should be doable. Of course, eventually the branch would need to be caught up with the latest and merge conflicts will need to be fixed. However, this approach may work if someone is in the middle of working on something and doesn't want to bother with the merge conflicts right after the switch over.

Overall, I couldn't find anything to be concerned about.

**Comment by lwrage** [comment]
- The repositories have been merged into osate/osate2. 
- The repo contains a new setup file in setup/osate2.setup. 
- Maven pom files have been updated for the new directory structure. 
- Local maven/tycho build works.
- Jenkins build configuration has been updated and works.
