### ISSUE TITLE
Regression testing is incomplete

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#919]
Umbrella issue for enhancements to regression testing, needs to be elaborated into a set of detailed issues

- [x] Add code coverage tool (#934)
- [ ] Support running tests without UI (currently required for error reporting)
- [ ] Add GUI testing tool (SWTBot, RCPTT, and/or Jubula)
- [ ] Add tests

**Comment by sprocter** [comment]
Re: Code Coverage -- I've used [JaCoCo](http://www.eclemma.org/jacoco/) in my jenkins-managed tycho builds in the past (detailed as part of [this writeup](https://samprocter.com/2014/06/tying-a-build-together-with-jenkins/)). I have it running on the GTSE builds right now, and it seems to work though some of the XText-generated classes are too large for analysis.

If you want me to look at using JaCoCo to add coverage analysis to other OSATE builds, let me know.
